### ISSUE TITLE
Move Inadyn cache files from /var/run/inadyn/ to /var/cache/inadyn/

### ISSUE THREAD

**Issue by troglobit** [troglobit/inadyn#102]
Leverage the FHS more.  Also, `/var/run` is (per FHS) not persistent across reboots, but `/var/cache` is (per FHS).

Of course, any `cache-dir` setting in `inadyn.conf` take precedence!

**Comment by hw489264** [comment]
Hello, I have started the inadyn service, and I am sure that each parameter in the configuration file is correct, but I do not see any in the /var/run/inadyn/ directory or /var/cache/inadyn directory Cache information, what is the reason?

**Comment by troglobit** [comment]
Hi @hw489264, to help you I need to know a bit more about you context. What version of Inadyn are you using.  Are you running it as root, as a system service, or as a regular user?

Also, please don't open a new discussion in an already closed issue.
