### ISSUE TITLE
Debian Jessie : Inadyn 1.99.4-1 : Server dns returns good but inadyn is killed

### ISSUE THREAD

**Issue by boubaj** [troglobit/inadyn#103]
Hi,

In Debian 8 (Jessie) there is the version inadyn 1.99.4-1 and I have a problem with this release.
I have configured correctly the config file for my provider server but the application inadyn is killed when it recieves the "good" reponse.

Here is the log:
Fri Aug  7 12:24:58 2015: Checking for IP# change, connecting to checkip.dyndns.org(216.146.38.70)
Fri Aug  7 12:24:58 2015: Update needed for alias <xxxxxgilson.xy>, new IP# 87.67.219.220
Fri Aug  7 12:24:58 2015: Sending IP# update to DDNS server, connecting to www.ovh.com(198.27.92.1)
Fri Aug  7 12:24:58 2015: Fatal error in DDNS server response:
Fri Aug  7 12:24:58 2015: [200 OK] good 87.67.219.220

Fri Aug  7 12:24:58 2015: Error response from DDNS server, exiting!
Fri Aug  7 12:24:58 2015: Failed starting daemon: RC_DYNDNS_RSP_NOTOK

You can see that the provider server that I connect returns a successful message but the program decides that it's an error and is killed.

( I have removed my correct alias <xxxxxgilson.xy> ).
I use the system custom@http_srv_basic_auth

Do you know what is wrong?

KR,
Steve,

**Comment by troglobit** [comment]
That's a very old release with known bugs and limitations. But I guess you've figured that out already considering issue #104.

Also, problems with Debian packages should be reported to them.

**Comment by boubaj** [comment]
Hi,

Thank you so much.

Steve,
