### ISSUE TITLE
Debian Jessie : Inadyn 1.99.14 : make generates an error

### ISSUE THREAD

**Issue by boubaj** [troglobit/inadyn#104]
Hi,

I have tried to install the inadyn 1.99.14 in Debian 8 (Jessie).
The commad './configure --enable-openssl' works correctly but when I execute 'make' I have an error.

Here is the error:
Making all in libite
make[1]: Entering directory '/home/boubaj/Downloads/inadyn-master/libite'
make[1]: *** No rule to make target 'all'.  Stop.
make[1]: Leaving directory '/home/steve/Downloads/inadyn-master/libite'
Makefile:322: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

Can you tell me the correct command that I have to run to install inadyn 1.99.14 in Debian 8 please?

KR,
Steve,

**Comment by troglobit** [comment]
Don't use the GitHub Download link. Use the tarball (tar.xz) from the releases page or http://troglobit.com/inadyn.html

(Github can't handle git repositories with submodules correctly.)

**Comment by boubaj** [comment]
Hi,

Thank you so much. 
It's installed and works perfectly.

If I can give a small feedback, there is something that I think could be helpful in inadyn:
If there is this kind of response returned from the server "[200 OK] nochg 109.130.73.174", it would be good to not kill the process inadyn.

Maybe an additional parameter could say to not kill the process if there is an "error" returned by the server.

PS: I had this "error" because I have two servers that update in parralel my dyndns provider. If one machine is down there is still another one that could send the new IP.

Thank you again for the job that you have done and your quick support,
Steve,

**Comment by troglobit** [comment]
@boubaj Great to hear that it's working!

There is a major refactor planned for the Inadyn 2.0 release where I could add the feature support you mention. Other people have also requested it.

However, when you get the `[200 OK] nochg ...` message Inadyn should not exit.  What DDNS provider are you connecting to, i.e., what Inadyn plugin causes this problem?  (HTTP response code 2xx is basically "Status OK".)

**Comment by troglobit** [comment]
OK, sorry. I see from #103 that it's www.ovh.com ... according to the plugin they use the same API as www.changeip.com, which use the same response as www.dyn.com -- where "nochg" is supported as a "good" reply.  

I'm closing this issue again, if you have any problems with Inadyn and how it behaves with your DDNS provider in the future, feel free to report a new issue. Thanks!
