### ISSUE TITLE
SSL.c  SSL_MODE_SEND_FALLBACK_SCSV

### ISSUE THREAD

**Issue by hkjacky8** [troglobit/inadyn#110]
refer to https://wiki.openssl.org/index.php/SSL_MODE_SEND_FALLBACK_SCSV

I need comment this line:
 SSL_set_mode(client->ssl, SSL_MODE_SEND_FALLBACK_SCSV);
 in ssl.c to work with SSL_CTX_new(SSLv23_client_method())

**Comment by troglobit** [comment]
Say what?  I don't understand what you mean.

If you want to make change send a pull-request,
if you want to report a bug then please explain a bit more.

**Comment by hkjacky8** [comment]
I am using openssl 0.9.8zc lib.
config inadyn 1.99.15 with --enable-openssl

When I try to use https to update the ddns like "changeip.com"
it is fail all the time
I checked the SSL_Connect() fail inside the ssl.c of the source of inadyn

Then I refer to https://wiki.openssl.org/index.php/SSL_MODE_SEND_FALLBACK_SCSV
when calling  "SSL_CTX_new(SSLv23_client_method());" 
no need 
#ifdef SSL_MODE_SEND_FALLBACK_SCSV
    SSL_CTX_set_mode(ctx, SSL_MODE_SEND_FALLBACK_SCSV)
#endif

So, I comment this, then I can success to update DNS to Changeip.com using https.

That is my problem to using 1.99.15 with openssl.

**Comment by troglobit** [comment]
Ah, that's much more clear. Thank you! :-)

I'll look into it over the weekend.

**Comment by troglobit** [comment]
Heh, managed to squeeze in some quality time before work this morning, fixed in 446c4ac :-)
