### ISSUE TITLE
Check for libconfuse in configure.ac

### ISSUE THREAD

**Issue by sshimko** [troglobit/inadyn#111]
autconf is not checking for libconfuse which leads to build-time errors.

**Comment by troglobit** [comment]
Yep, it's all new and shiny!  Just integrated support for libConfuse for the upcoming v2.0 release, so things are a bit shaky on master atm.  If you want something a bit more stable, try one of the release tarballs in the meantime :smiley:

**Comment by troglobit** [comment]
Fixed in commit 61d4e2d on master.
