### ISSUE TITLE
Inadyn in afraid isn't update IP

### ISSUE THREAD

**Issue by hernanBeiza** [troglobit/inadyn#112]
Hi!
I need your help. I am running Inadyn in Ubuntu Server Ubuntu 14.04.3 LTS. I setup my credentials, alias and alphanumeric string (everything after ?) from the Direct URL. But I don't know if Inadyn is updating the IP. I saw the log file and this line appears:
```bash
Sun Dec 13 18:45:46 2015: Sending update URL query, connecting to freedns.afraid.org(50.23.197.94)
Sun Dec 13 18:45:46 2015: Update URL query failed
Sun Dec 13 18:46:06 2015: Network error while waiting for reply: Resource temporarily unavailable
```

What I can do? Do you have an idea about what is the problem?
Thanks for your time

**Comment by troglobit** [comment]
Hi @hernanBeiza 

could you help me out a bit by first listing the version of Inadyn you are running and perhaps add the configuration you are using?  

- Is it the Inadyn version shipped with Ubuntu, another version from my GitHub, or perhaps even a clone from latest unstable master?
- If you paste your config, make sure to XXXX out your credentials!

However, from the output of the log you provided it looks like a temporary server error, which is quite common, unless you've set up your config wrong, of course.

**Comment by hernanBeiza** [comment]
HI @troglobit! 
Thanks for your fast reply! Now, the details!
version: shipped with ubuntu server 64 bits, dpkg -s inadyn:
``` bash
Architecture: amd64
Version: 1.99.4-1
```
My config:
``` bash
username xxx
password xxx
update_period_sec 30
forced_update_period 320000
log_file /var/log/inadyn.log
alias mydomain.cl,myalphanumericfromdynamic
dyndns_server_url /dynamic/update.php?myalphanumericfromdynamic
background
dyndns_system default@freedns.afraid.org
verbose 1
```
I don't think is a server error because I am having this response from a long time... and I wrote to Josh from afraid and they don't recognized it as an error.

**Comment by troglobit** [comment]
Oh dear, that's a *very* old release ... lots of bugfixes have been made since then, 2,5 years old :-(

Also, I've never seen this `myalphanumericfromdynamic` that you use (twice). What's it for?  

If you update to, say [v1.99.15](https://github.com/troglobit/inadyn/releases/tag/1.99.15), which you can find here under Releases you should be able to replace your current config with this:

    system default@freedns.afraid.org
      ssl
      username xxx
      password yyy
      alias mydomain.cl

Notice how later versions of Inadyn support HTTPS (ssl) updates! :+1:

**Comment by hernanBeiza** [comment]
Yes, is very old... I don't knew the inadyn package was older than your recent versions... I will try to update inadyn. 

myalphanumericfromdynamic = is a alphanumeric string generated by afraid. each domain has a string. I used this tutorials, check it for you have an idea:
http://ubuntuforums.org/showthread.php?t=1758930
In red appears the alphanumeric string that I mean in the last post 
Thanks for your time!

**Comment by troglobit** [comment]
I don't use the alphanumeric string with my own afraid account, just try
and remove it. I'd wager a guess that the tutorial is probably out of date.

Hope you get it working, I'm off to bed now! :P

**Comment by hernanBeiza** [comment]
OK! Thanks for all!

**Comment by troglobit** [comment]
Did you get it to work?  Can we close this issue?

**Comment by hernanBeiza** [comment]
Ok. Close the issue. But I am looking the log file from yesterday using the old Inadyn version and waiting the IP change. By the way I made the change, removing the alphanumeric string. I will try to compile the new version soon.

**Comment by troglobit** [comment]
OK!  Re-open this issue if you have more questions, or file a new one if you find a new bug!
Good Luck! :smiley:
