### ISSUE TITLE
How to install inadyn in intel edison with yocto image

### ISSUE THREAD

**Issue by neuberfran** [troglobit/inadyn#114]
Hi,

I'm need a dynamic DNS in my intel edison and now I think in inadyn. I tried ddclient but I have very problems.

Will I can install libconfuse ? How to install libconfuse in intel edison with yocto ?

AFTER

How to install inadyn in intel edison with yocto image ?

**Comment by troglobit** [comment]
Hi @neuberfran,

I'm having a little trouble understanding you, but you should be able to set up Inadyn for your purposes, it's very portable. I cannot support you with cross-compiling issues on Yocto, you'll have to consult its documentation for how to build additional software, but please use a stable release of Inadyn, https://github.com/troglobit/inadyn/releases, they are self standing and include pretty much everything you need.

The code on the GitHub `master` branch is still under development to become v2.0, but its not ready yet. One of the things left to do is add libConfuse as a GIT submodule and include it in the release tarball.

**Use the README included in the latest release tarball to see how to build, install, and run inadyn.**

Good Luck
 /Joachim

**Comment by troglobit** [comment]
So, did you figure it out ... can we close this issue?

**Comment by neuberfran** [comment]
No. When going out the version 2.0 of the inadyn with libconfuse build-in?

**Comment by troglobit** [comment]
No? What do you mean? Was not the latest official release, v1.99.15, to your satisfactory? 

I have no time at the moment to work on the upcoming release. Time is unfortunately limited and I'm not payed to work on Inadyn.

**Comment by neuberfran** [comment]
Do You can get on my pc via team to install and configure inadyn on my intel edison?
About fuse zone in Brazil now is 15:10 pm. I have hostname in DynDNS.

**Comment by troglobit** [comment]
Dude, read my first reply.  I cannot help you with personal support on an embedded device and operating system I have no experience with -- nobody pays me for this, you know.

Since you do not have any actual bugs to report with Inadyn, I'm closing this issue. Please refer to Intel Edison or Yocto support pages for how to build and install 3rd party packages.
