### ISSUE TITLE
How to install inadyn in intel edison with yocto image

### ISSUE THREAD

**Issue by neuberfran** [troglobit/inadyn#115]
root@neuberfran:/usr/local/inadyn-master# make
make: *** No targets specified and no makefile found.  Stop.
root@neuberfran:/usr/local/inadyn-master# ls
AUTHORS       ChangeLog.md  NEWS          TODO          include       man
COPYING       LICENSE       README        autogen.sh    indent.sh     plugins
ChangeLog     Makefile.am   README.md     configure.ac  libite        src
root@neuberfran:/usr/local/inadyn-master# make
make: *** No targets specified and no makefile found.  Stop.
root@neuberfran:/usr/local/inadyn-master#

**Comment by troglobit** [comment]
Like I said in the previous issue, don't use the GIT master it's under development. Use a released tarball and consult the README.

**Comment by neuberfran** [comment]
http://dpaste.com/10MN244
