### ISSUE TITLE
OpenSSL build fails on master gdee11ad, 2016-02-03

### ISSUE THREAD

**Issue by rtorrentuser** [troglobit/inadyn#117]
Something is broken after recent changes in v.2.0 beta (on Debian Jessie):

kernel: inadyn[23358]: segfault at 30 ip 00007f1f9b961f34 sp 00007ffe881246e0 error 4 in libssl.so.1.0.0[7f1f9b929000+56000]

**Comment by troglobit** [comment]
Yup, working on it ... v2.0 is still under heavy development, regressions are to be expected. Lots of
things still to be changed for SSL -- splitting up Inadyn HTTPS support in separate GnuTLS and OpenSSL support API's.

In the meantime, if you want something stable, try [the latest release](https://github.com/troglobit/inadyn/releases/tag/1.99.15).

Thanks for the report! :smiley:

**Comment by troglobit** [comment]
Should be fixed on master, as of d7e0ee5 ...
