### ISSUE TITLE
Add a configurable response string to custom providers

### ISSUE THREAD

**Issue by troglobit** [troglobit/inadyn#119]
@svenhoefer mentioned [in pull request 116](https://github.com/troglobit/inadyn/pull/116#issuecomment-179181095):
> Please add the possibility to add a custom response-string to custom providers to avoid commits like > svenhoefer@7ab906e and avoid the use of `--continue-on-error`.
> 
> Then a custom provider can looks like this:

    custom ddnss.de {
        ssl = true
        ddns-server = ddnss.de
        ddns-path = "/upd.php?key=MYLONGLONGKEY&host="
        alias = myhost.ddnss.de
        response = "Updated"
    }

**Comment by raabf** [comment]
If you implement this remember to directly allow a list of valid response strings instead only of a single one. Sometimes there are multiple valid good answers for a single provider like:

     response = { "Updated", "Update not needed" }

**Comment by troglobit** [comment]
Obviously.  This is already in the plugins, so not implementing multiple possible response strings would be a regression.
