### ISSUE TITLE
Empty response from DNS server results in inadyn exit

### ISSUE THREAD

**Issue by geohei** [troglobit/inadyn#120]
Hi.

My DNS providers response to an correct record update is an empty reply (he doesn't respond anything in body text). This leads to an error message and subsequent exit of inadyn. The record is verified being updated correctly.

```
...
Host: dyndns.dns-stock.com
Authorization: Basic dZ9pZ3p2b2lk
User-Agent: inadyn/1.99.15 https://github.com/troglobit/inadyn/issues

Mon Feb  8 07:39:50 2016: DDNS server response: HTTP/1.1 200 OK
Date: Mon, 08 Feb 2016 06:39:50 GMT
Server: Apache/2.2.9
X-Powered-By: PHP/5.2.14-0.dotdeb.0
Vary: Accept-Encoding
Content-Length: 0
Connection: close
Content-Type: text/html

Mon Feb  8 07:39:50 2016: Fatal error in DDNS server response:
Mon Feb  8 07:39:50 2016: [200 OK]
Mon Feb  8 07:39:50 2016: Error response from DDNS server, exiting!
```
Is there any option which I missed in order to avoid this?

**Comment by troglobit** [comment]
Hi, no you haven't missed anything. That's just a case that isn't covered at the moment.

What "plugin" are you using with your provider, or do you have a custom setup?  There have been feature requests for customizing the response from custom providers, issue #119, that I intend to look at for the upcoming v2.0 release.

**Comment by geohei** [comment]
I use DNS Stock (http://ww.dns-stock.com).

My provider/config:
```
system custom@http_srv_basic_auth
server-name dyndns.dns-stock.com
server-url /?hostname=<hostname>&username=<username>&password=<password>&myip=<myip>
```
So ... cutom setup.

The custom response string (#119) would help in my case, but this is only one step in customization. A fully configurable server-url line would be a passe partout for every kind of DNS server response. This would allow customized tag and position definition.

**Comment by troglobit** [comment]
Agreed, a fully customizable server-url/path would be the key here :+1: 

Issue  #121 also brings this up, so it may be a good opportunity to break with the old completely and implement a more custom-friendly approach for the upcoming Inadyn v2.0 ... have lots on my plate at the moment though, so I cannot make any promises for when this will happen.

As always, pull requests and patches are most welcome :smiley:

**Comment by geohei** [comment]
I'll have look at Pull requests. I'm not even familiar with GitHub and autoconf. Last builds I did are ./configure, make, make installl ... so I need to dig myself through a bit before daring a Pull request ... :)

**Comment by troglobit** [comment]
As of commit 777fd5e it should now be possible to accept an empty response body from a provider. (Inadyn will still check that HTTP 200 OK code is returned.)

**Comment by troglobit** [comment]
Postponing fully customizable server-url/path for the future. Closing this issue.
