### ISSUE TITLE
Hostname appended by default to custom providers

### ISSUE THREAD

**Issue by geohei** [troglobit/inadyn#121]
When using `system custom@http_srv_basic_auth` the hostname used in the `alias` line is appended to the GET request is placed (`server-url`). This is sometimes not desired.

However when using `append-myip`, the hostname is not appended but the IP instead.

This is (AFAIK) not documented and discovered only after intense trials.

May I suggest to avoid appending the hostname automatically when append-myip is not used

**Comment by troglobit** [comment]
Although I agree it is confusing, we would need to implement something else to not break backwards compatibility. The default for many moons has been to append the hostname. If we remove it other people's setup will suffer instead.

**Comment by geohei** [comment]
Ok ... I fully understand. An `append-hostname` option might possibly be a long term solution.

If you leave it like it is now, please mention it in man pages. Avoids long lasting troubleshoot if things don't work as expected ... :)

**Comment by troglobit** [comment]
Adding to 2.0 milestone as a minor TODO. Will probably add something similar to `append-hostname`, unclear at the moment, but good idea. Thanks for the report!

**Comment by raabf** [comment]
Is that not a bit too restrictive? If you just always append there is no cache to use both of them (hostname and myip). And for identification you normally need the hostname.

What about an additional option like `myip-prefix` like `myip-prefix = "&myip="` ? inadyn first append the hostname from `alias` to the basic URL, then append the value from `myip-prefix` and then append the IP itself. The result is then something like (where `...&hostname=` ist the basic URL):

    ...&hostname=HOSTNAME&myip=IPADDR

**Comment by troglobit** [comment]
Sure. Patches and pull requests are most welcome, as usual :wink:

**Comment by troglobit** [comment]
I hope everyone will be happy with 1a44c61, it adds support for `printf()` like format specifiers. Supported format specifiers for ddns-path are:
    
* %u - username
* %p - password, if HTTP basic auth is not used
* %h - hostname
* %i - IP address

Which means the following example configuration:

    username  = myuser
    password  = mypass
    ddns-path = "/update?user=%u&password=%p&domain=%h&myip=%i"
    hostname  = YOURDOMAIN.TLD

... would be translated into the following HTTP GET update request:

    /update?user=myuser&password=mypass&domain=YOURDOMAIN.TLD&myip=1.2.3.4
