### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by svenhoefer** [troglobit/inadyn#122]
After https://github.com/troglobit/inadyn/commit/6868f2863807645bdd1fd7eb53f56306453f43ed and https://github.com/troglobit/inadyn/commit/dee11adf8c65cde39007932d33ba179beb1120ba we have segfaults in src/openssl.c:106:
`int err = SSL_write(client->ssl, buf, len);`

When i log _buf_ and _len_ it looks like:
`Thu Feb 11 17:42:24 2016: buf: x, len: 124`

This is a backtrace: http://pastebin.com/sjmrJWV5

When i revert both commits above inadyn runs fine again.

Regards, Sven.

**Comment by troglobit** [comment]
Should be fixed on master now, had a few things left to do to complete the SSL refactor. Thanks for the report! :+1:
