### ISSUE TITLE
google support

### ISSUE THREAD

**Issue by stevebovy** [troglobit/inadyn#123]
My version of Buffallo dd-wrt does not yet have the "google" update.

How can I use the "custom" option to specify googles parms ??

Google::
Add the following to your inadyn.conf

system default@domains.google.com    << is this the  host option <<

username generated_username 

password generated_password 

alias sub.domain.tld                               <<  is this the domain option 

Thanks for your help !!

**Comment by troglobit** [comment]
I don't even know what old version of Inadyn that Buffalos DD-WRT uses. I would suggest asking/looking in a generic DD-WRT forum instead.

**Comment by stevebovy** [comment]
Thanks;  I  have tried many different combinations.  For some reason I do not understand 
entering bad parms causes the   "generated" asp web pages to be incomplete and missing the 
update buttons.  therefore I cannot undo the bad parms.  In the past this occurred after the 3 attempt.
and after a reboot the web page would reset; but this last time I entered an ip address;  and doing
a reboot no longer resets and restores the broken web page.   

I am grasping at straws and post this in the hopes that this will rattle some rusty cobwebs or ring some bells which might lead to a resolution.   dose the functioning of the inadyn server have a gui componenet  and can that component be broken by bad parms?

I ask this question in ignorant innocence so please bear with me 

thanks again

**Comment by troglobit** [comment]
I maintain the upstream inadyn text-only client, it has no web component.  The only interface it has is command line arguments or a configuration file. 

You really need to ask your question to the DD-WRT or Buffalo support forums since I cannot help you.

I'm closing this issue now since your problem is obviously not related to Inadyn, sorry.

**Comment by stevebovy** [comment]
thanks again
