### ISSUE TITLE
Errors in log (v.2-beta)

### ISSUE THREAD

**Issue by rtorrentuser** [troglobit/inadyn#125]
"Failed to get IP address for default@..., giving up!" error appears in log on each address check presumably after changes commited on May, 31...

**Comment by troglobit** [comment]
Hi, thank you for the bug report!  Could you please run with debug logs enabled? It might a be a bug, but it may also be a problem with your setup. 

     ./inadyn -l debug -n -f /path/to/inadyn.conf

**Comment by rtorrentuser** [comment]
Yes, you're right! Something was wrong with my system. Works fine now. Sorry! And thank you!

**Comment by troglobit** [comment]
That's good news, no problem. Good Luck! :smiley:
