### ISSUE TITLE
syslog openlog(3) ident parameter

### ISSUE THREAD

**Issue by Duncaen** [troglobit/inadyn#130]
Hi,

is there a reason to call `openlog` with `NULL` for the ident parameter?
It seems like this is something that each libc handles different, on my musl libc system it is set to the pid of the process.
For me it would be nice to set it to `inadyn` to filter the logs more easily.

Greetings,
Duncan

**Comment by troglobit** [comment]
Slight oversight from my end. I simply hadn't noticed that POSIX does not define the behavior when `ident` is `NULL`.  Too many years in GNU land and I expected all libc's to default to `__progname`.

*fixing*
