### ISSUE TITLE
Freedns 

### ISSUE THREAD

**Issue by rtorrentuser** [troglobit/inadyn#131]
'freedhs.afraid.org' is my DDNS provider, and very often I see 'Failed to get IP address for default@freedns.afraid.org, giving up!' messages in log file.
 
It seems like 'checkip.dyndns.org' server is too busy and is not always able to respond quickly...

I tried to use freedns own checkip url and it worked for me (see the attached patch). No more errors in log. 
[freedns.patch.zip](https://github.com/troglobit/inadyn/files/336693/freedns.patch.zip)

**Comment by troglobit** [comment]
Thanks for the patch! :trophy:
