### ISSUE TITLE
is_address_valid() in ddns.c needs a ntohl() before checking AF_INET address

### ISSUE THREAD

**Issue by ntherning** [troglobit/inadyn#133]
According to http://pubs.opengroup.org/onlinepubs/000095399/basedefs/netinet/in.h.html:

> The sin_port and sin_addr members shall be in network byte order.

I currently have an IP address ending in `.244` (`0xf4`). Im running on Ubuntu 14.04 amd64 which is little endian so without the `ntohl()` the IP address will appear to start with `244.` which happens to  match `IN_EXPERIMENTAL()`

Below is how I changed it. Not sure whether you want to do it this way or put the `ntohl()` call in the macros in `os.h`. Also not sure what to do for IPv6 addresses (if anything).

```diff
diff --git a/src/ddns.c b/src/ddns.c
index b3ea081..f904d66 100755
--- a/src/ddns.c
+++ b/src/ddns.c
@@ -169,7 +169,7 @@ static int is_address_valid(int family, const char *host)
                if (!inet_pton(family, host, &address))
                        return 0;
 
-               addr = address.s_addr;
+               addr = ntohl(address.s_addr);
                if (IN_ZERONET(addr)   || IN_LOOPBACK(addr) || IN_LINKLOCAL(addr) ||
                    IN_MULTICAST(addr) || IN_EXPERIMENTAL(addr))
                        return 0;
```

**Comment by troglobit** [comment]
Good catch!  This is a regression introduced very recently, in [f625fa3](https://github.com/troglobit/inadyn/commit/f625fa35e71aa0d5288bfee11d51e6b52625156a#diff-2cc1c3013f1b47d32ba67e88853ec625L301)

When I added the support for validating IPv6 addresses, which I went over with a fine-toothed comb, I simultaneously refactored the IPv4 validator to this combined `is_address_valid()` function.  Unfortunately I didn't catch it mysefl in my tests, but fortunately this new version is not released yet. 

Thanks a bunch for finding this, and sorry for any problems this might have caused!
