### ISSUE TITLE
Cannot use inadyn with padavan custom firmware router

### ISSUE THREAD

**Issue by arooni** [troglobit/inadyn#137]
Any ideas on how to fix?

Running https://bitbucket.org/padavan/rt-n56u

Jan  1 03:32:36 inadyn[2711]: Failed resolving hostname arooni.jumpingcrab.com: Name or service not known
Jan  1 03:33:16 inadyn[2711]: Failed resolving hostname ip.dnsexit.com: Name or service not known
Jan  1 03:33:16 inadyn[2711]: Will retry again after 5 min...
Jan  1 03:33:16 inadyn[2711]: FORCED_UPDATE command received, updating now.
Jan  1 03:33:56 inadyn[2711]: Failed resolving hostname ip.dnsexit.com: Name or service not known
Jan  1 03:33:56 inadyn[2711]: Will retry again after 5 min...

**Comment by troglobit** [comment]
Yep, the DNS name cannot be resolved to an IP address. So either you have no connection to the Internet or your router does not have DNS set up for services running on the router. Could be misconfigured firewall or that your ISP did not give you a DNS (which you usually get when you receive your IP address).

Either way, it's likely not a problem limited to just Inadyn, or a problem in Inadyn either, for that matter.

**Comment by troglobit** [comment]
Any luck? Maybe we can close this issue?

**Comment by arooni** [comment]
Hey thanks for the followup!  Feel free to do that.  I still don't have it working but I don't think that's your issue.

I'm sure that it's the fault of my router's software and using a stupid at&t dns address even though it's not accessible, and I've already configured it to use google's DNS...

Any way to force inadyn to use a specific DNS entry?

an  2 06:48:32 DHCP WAN Client: deconfig (eth3): lease is lost
Jan  2 06:48:32 RT-N56U: WAN down (eth3)
Jan  2 06:48:32 dnsmasq[397]: read /etc/hosts - 5 addresses
Jan  2 06:48:32 dnsmasq[397]: read /etc/storage/dnsmasq/hosts - 0 addresses
Jan  2 06:48:32 dnsmasq-dhcp[397]: read /etc/dnsmasq/dhcp/dhcp-hosts.rc
Jan  2 06:48:32 dnsmasq[397]: using nameserver 8.8.8.8#53
Jan  2 06:48:32 DHCP WAN Client: bound (eth3), IP: 23.127.123.123, GW: 23.127.68.1, lease time: 600
Jan  2 06:48:32 RT-N56U: WAN up (eth3)
Jan  2 06:48:32 dnsmasq[397]: read /etc/hosts - 5 addresses
Jan  2 06:48:32 dnsmasq[397]: read /etc/storage/dnsmasq/hosts - 0 addresses
Jan  2 06:48:32 dnsmasq-dhcp[397]: read /etc/dnsmasq/dhcp/dhcp-hosts.rc
Jan  2 06:48:32 dnsmasq[397]: using nameserver 192.168.1.254#53
Jan  2 06:48:32 inadyn[11945]: RESTART command received, restarting.
Jan  2 06:48:32 inadyn[12007]: Inadyn version 1.99.15 -- Dynamic DNS update client.
Jan  2 06:48:54 NTP Client: Synchronizing time to pool.ntp.org.
Jan  2 06:49:12 inadyn[12007]: Failed resolving hostname myusername.jumpingcrab.com: Name or service not known
Jan  2 06:49:53 inadyn[12007]: Failed resolving hostname myusername.ddns.net: Name or service not known
Jan  2 06:49:53 inadyn[12007]: Checking for IP# change, querying interface eth3
Jan  2 06:49:53 inadyn[12007]: Update forced for alias myusername.jumpingcrab.com, new IP# 23.127.69.128
Jan  2 06:49:53 inadyn[12007]: Update forced for alias myusername.ddns.net, new IP# 23.127.123.123
Jan  2 06:49:55 NTP Client: Synchronizing time to time.nist.gov.
Jan  2 06:50:33 inadyn[12007]: Failed resolving hostname freedns.afraid.org: Name or service not known
Jan  2 06:51:13 inadyn[12007]: Failed resolving hostname dynupdate.no-ip.com: Name or service not known
Jan  2 06:51:13 inadyn[12007]: Will retry again after 5 min...

**Comment by troglobit** [comment]
Nope, that's a thing of the system. It provides access to its acquired DNS via the C library's resolver.

Good luck mate!
