### ISSUE TITLE
Cannot install in Raspberry Pi

### ISSUE THREAD

**Issue by IgorGanapolsky** [troglobit/inadyn#139]
Hello,
I am trying to install inadyn on my Rasp Pi, but getting this error:
> Reading package lists... Done                                                                                    
Building dependency tree                                                                                         
Reading state information... Done                                                                                
You might want to run 'apt-get -f install' to correct these.                                                     
The following packages have unmet dependencies:                                                                  
 expect : Depends: tcl8.5 (>= 8.5.0) but it is not installed                                                     
 libexpat1-dev : Depends: libexpat1 (= 2.1.0-6+deb8u1) but 2.1.0-6+deb8u3 is installed                           
 tightvncserver : Depends: x11-utils but it is not installed                                                     
                  Recommends: x11-xserver-utils but it is not installed                                          
 xfonts-base : Depends: xfonts-utils (>= 1:7.5+2) but it is not installed     

Please advise,
Igor

**Comment by troglobit** [comment]
Hi Igor,

If you installed the Debian/Ubuntu package you have to report your problem to them. This is the upstream issue tracker where problems building from released tarballs or GIT branches are handled.

Regards
 /Joachim

**Comment by troglobit** [comment]
@IgorGanapolsky Install instructions are available in `README.md`. I'm sorry you dislike my closing this issue, but I am not in control of Debian/Ubuntu or other packaging of my software.
