### ISSUE TITLE
Add a homebrew formula

### ISSUE THREAD

**Issue by gutenye** [troglobit/inadyn#140]

**Comment by troglobit** [comment]
Since I don't have MacOS, all contributions, in any form, are welcome.

**Comment by troglobit** [comment]
After thinking about this for a while, is it really the responsibility of upstream to provide downstream packaging. No, I don't think so.

**Comment by ptz0n** [comment]
A mention in README when this is merged would be nice: https://github.com/Homebrew/homebrew-core/pull/32346

**Comment by troglobit** [comment]
@ptz0n Since I don't know what to reference or what to write in the README to make it relevant to macOS users, I welcome pull requests for said mention.  Also, please don't comment on closed issues, open a new one instead, or a PR :)

**Comment by troglobit** [comment]
Awesome, great work! 👍
