### ISSUE TITLE
How to install the latest version on Ubuntu

### ISSUE THREAD

**Issue by gutenye** [troglobit/inadyn#141]
Current version on Ubuntu is 1.99.4.
Is there a PPA available?

**Comment by troglobit** [comment]
Unfortunately no.

I'm currently working on the big v2 and I'll probably look into setting
something up when that is released.

Regards
/Joachim

**Comment by troglobit** [comment]
Just looked into setting up a PPA, and no. I won't do that, too much work for me unfortunately.

I'll instead investigate getting Debian to upgrade.
