### ISSUE TITLE
./configure fails with PKG_PROG_PKG_CONFIG: command not found

### ISSUE THREAD

**Issue by Papafox** [troglobit/inadyn#142]
Trying to build inadyn from source:
```
./configure: line 13238: PKG_PROG_PKG_CONFIG: command not found
./configure: line 13239: syntax error near unexpected token `lite,'
./configure: line 13239: `PKG_CHECK_MODULES(lite,    libite >= 1.5.0)'
```
System is ArchLinux:
```
lsb_release -a
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
```
I have already installed LibITE, so configure is not complaining about it being missing.  It seems to be about the macro PKG_PROG_PKG_CONFIG.  Do you have any suggestions?

**Comment by troglobit** [comment]
You need pkg-config, which takes care to check for correct versions of libraries.

**Comment by Papafox** [comment]
OK, that fixed it.  Thanks
