### ISSUE TITLE
Service does not start on boot if Master Code is enabled on start

### ISSUE THREAD

**Issue by juanand** [troglobit/inadyn#143]
Hi,
When master code is enabled upon start, the service does not start until master code is entered.

**Comment by troglobit** [comment]
Sorry for my ignorance, but what is "master" mode?

**Comment by troglobit** [comment]
Some more information on this is needed for me to reply, not just the mysterious "master" code, but also things like what version of Inadyn you are using, what provider, etc.

**Comment by juanand** [comment]
Sorry, it is called "Master Lock".
Allows to lock certains Kodi blades like Settings so kids can use Kodi without reconfiguring it :)
It is at System->Settings->Master lock (Expert settings).
When the option "Ask for master lock code in startup", it seems that the update does not run until the code is entered.
Thanks!

**Comment by juanand** [comment]
I am using latest OSMC on RasPi, Inadyn version 1.99.12.
The addon works great for me if I remove the "Ask for master lock code in startup" option, or once I enter it.

**Comment by troglobit** [comment]
I'm sorry but I'm not part of the Kodi project, nor do I maintain that
(old) Inadyn port in Kodi. You should report these problems to them.
