### ISSUE TITLE
inadyn behind NAT

### ISSUE THREAD

**Issue by michael-o** [troglobit/inadyn#144]
Please clarify in the README wether inadyn will work on a machine behind a NAT router (home router with DSL through PPPoE)? Specificly, will it register my public IP with the DNS provider rather than the private address my machine has from the DHCP server on my home router?

**Comment by troglobit** [comment]
I think it's in there already somewhere, but if not I'll clarify as part of the next release cycle.

Meanwhile, the answer is that it depends. You can get it to register your private address if you want (some people actually want that and DNS does not prohibit it), but by default Inadyn registers the public IP it gets by asking your DDNS provider's server.

**Comment by michael-o** [comment]
Aha, a proper clarification would definitively help though. My BSD machine is not directly connected to the internet and having its prive IP address registered doesn't make any sense to me in this case. Just to be sure, you are referring to this code spot in C: https://github.com/troglobit/inadyn/blob/master/src/ddns.c#L152?

**Comment by troglobit** [comment]
Yes, that is one of the parts of the code that is executed in the public IP case.  See the examples
and the man page for more info:

https://github.com/troglobit/inadyn/tree/master/examples

**Comment by michael-o** [comment]
Thanks for the update. This does the trick.
