### ISSUE TITLE
Document necessary dependency versions in README.md

### ISSUE THREAD

**Issue by michael-o** [troglobit/inadyn#145]
Please document in section "Build & Install" which minimal versions inadyn requires to compile and run. Otherwise it is quite tedious with `configure`, trial and error -- just wasted time.

**Comment by troglobit** [comment]
Sure I could do that, or you could submit a pull request with a proposed update, seeing as you've now figured it out.

This is not proprietary software, you don't pay for this and I'm under no obligation to prevent users of software that I provide freely to not "lose time". 

I'm sorry, but there's a certain "try it out for yourself" and "we work together" that's implied in the open source world.

Also, I'm sure there are other DDNS clients out there that are more accommodating to your requirements.

Thank you for submitting this ticket, it will be considered for the next release.

**Comment by michael-o** [comment]
This wasn't an offense whatsoever, I did that actually and it compiled and installed cleanly. I have already gone the hard way. Since nothing is available on the FreeBSD ports tree, I got newest versions. If `configure` spits that out, I see no problem providing a proper PR for the `README.md`. Is that acceptable?

PS: I haven't found a better one it. So, I'd like to stick to the best known to me :D

**Comment by michael-o** [comment]
See #146

**Comment by troglobit** [comment]
I'm very open to pull requests improving Inadyn for everyone in general, and simplifying my work in particular.  Thank you!

**Comment by michael-o** [comment]
I no issue, thanks for merging. I already have several in mind resolving a few FreeBSD issues.
