### ISSUE TITLE
SSL connection to the checkip-server

### ISSUE THREAD

**Issue by sigmoidal** [troglobit/inadyn#147]
How can inadyn v2.0 checkip-server connect to an SSL server? 

I run an SSL server only and see no reason to setup a vhost just to host the checkip over plain HTTP.

thanks for the awesome utility!

**Comment by troglobit** [comment]
It can't.

However, you're now the 2nd person to request this feature, the first person actually even sent a
[patch](https://github.com/troglobit/inadyn/files/567099/inadyn.txt), which I decided to not include
in v2.0.   The reason for my rejecting it was that I considered the server overhead for a simple
HTTP request vs a HTTPS request.

I assume, from your second paragraph, that you are running your own DDNS provider, with a checkip server only available over HTTPS, right?  If not, then there is no need to set up a server
with HTTPS ...

**Comment by sigmoidal** [comment]
Hi Joachim,

Thanks for the patch. If you will not be merging it upstream, then I will consider, but it's definitely something I wouldn't want to have to do on each update. It would be great if you could add support for checkip over HTTPS for those of us who would like to use it, but your call.

Correct, I am running my own DDNS service and both the checkip and ddns services are HTTPS-only.

**Comment by troglobit** [comment]
Hmm, OK I'll think about it.

Maybe if "ssl = true" is set Inadyn could first use HTTPS against the checkip server, with a fallback to HTTP on failure?   I'd really not like to add another (`checkip_ssl`) setting ... 

I'm not sure when I'd get around to it though, but if you could prepare a pull request and test such a thing, based on the patch, I'd be more than willing to merge it.  What do you think?

**Comment by sigmoidal** [comment]
Ok, I spend a bit of time and brought that patch you sent me up to speed, but I don't have time to dig into the code and make the fallback functionality you are discussing, at least for now. At least it works and I can do what I want, so thank you, as well as the patch author!

In my opinion it should not take decisions or have fallback processes. checkip-ssl is a superclean concept as it is which is the equivalent of ssl = true for the ddns server. Especially because inadyn is geared toward an automated process that an administrator won't see or supervise, it is best to not take decisions if things don't work. 

Maybe others can chip in :)

**Comment by troglobit** [comment]
Great work!  Let's see if someone else chips in, I'll let it sit for a while for others to see.

I see your point of view and sort of agree with the automatic fallback argument, in my experience however, increasing the amount of knobs and levers on a product tends to confuse and scare regular users more than having a built-in heuristic that works.  Most users do not even understand the difference between the checkip server and the ddns server ...That said, I'm not against adding a setting to override or control the heuristic.

An example:

    ssl = true

could easily mean `checkip-ssl = true` as well. A user experiencing problems with Inadyn could then check the documentation (it's usually not until that point most users do RTFM anyway) and realize:

    ssl = true
    checkip-ssl = false

was a setting that worked for his/her DDNS provider.

If nobody else pitches in, or you get some time to complete this, that heuristic is what I'll add to before the next official release.

**Comment by sigmoidal** [comment]
Lets agree this contribution is entirely of the original patch author, to give credit where credit is due; at least for now.

I agree with you in all counts; especially I like the idea of having ssl = true to mean ssl for both connections. What I don't quite like is the utility trying to connect over a different protocol as a fallback mechanism, than the one intended or being the default. I hate products with unpredictable or cryptic behavior. The correct thing to do is to fail if the server doesn't send the IP (for whatever reason, be it ssl or not). I am especially against it, because this can expose users to communicate information over an unencrypted channel and we are heading toward the all-encryption era imho.

For example,  think of a password protected area that checkip is provided to registered users only. If those credentials for the checkip server are shared with the ddns, then that could be a security issue if the webserver is misconfigured or down. Of course, I am not sure password authenticated checkip is currently supported, but that's only one case that could emerge in the future. I can think of other reasons (i.e. transmitting more data to the checkip server, than a plain request, i.e. to trigger service/port knocking behavior). extreme cases? maybe, ok :)

I'm for sane defaults, but not for intertwining functionality. I appreciate your work and it's your call for sure. I can always customize, if all else fails. Lets see if anyone else cares :)

Mainly its the testing that is time consuming, not coding the functionality in. I'll see what I can do.

thanks :)

**Comment by troglobit** [comment]
Agreed, I'll update the author field of the commit before I merge.

OK, I have no problem with that, your reasoning is sound. Falling back to unencrypted is inherently bad.  If you can fix the code according to the scheme we've discussed I'll merge immediately! :+1: 

No, thank you!

**Comment by troglobit** [comment]
Merged #148 as 5a6c117 to master.  Will look at updating the code to use the scheme discussed above.
