### ISSUE TITLE
openssl1.1

### ISSUE THREAD

**Issue by rtorrentuser** [troglobit/inadyn#151]
Unable to build inadyn against openssl1.1:
...
checking for confuse.h... yes
checking for OpenSSL... yes
checking for EVP_EncryptInit in -lcrypto... yes
checking for SSL_library_init in -lssl... no
configure: error: *** SSL library (OpenSSL) not found!
make: *** No targets specified and no makefile found.  Stop.
...

Everything was fine with openssl1.0.2

**Comment by troglobit** [comment]
Thanks for the report! I've never tested with that, what distribution had it?

**Comment by rtorrentuser** [comment]
Debian 9 (stretch)

**Comment by troglobit** [comment]
Thanks! 👍

**Comment by troglobit** [comment]
GitHub automatically closes issues when the "Fix #..." is included in the GIT commit message ... anyway, I hope this patch fixes things for you. Let me know otherwise and I'll make sure to reopen this issue :)

**Comment by troglobit** [comment]
With this patch I'll start the release process for v2.1

**Comment by rtorrentuser** [comment]
Still getting errors...
...
openssl.c: In function ‘verify_callback’:
openssl.c:77:45: error: dereferencing pointer to incomplete type ‘X509_STORE_CTX {aka struct x509_store_ctx_st}’
   X509_NAME_oneline(X509_get_issuer_name(ctx->current_cert), buf, sizeof(buf));
                                             ^~
Makefile:749: recipe for target 'inadyn-openssl.o' failed
make[1]: *** [inadyn-openssl.o] Error 1
make[1]: Leaving directory '/var/tmp/inadyn-temp/src'
Makefile:472: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
...

**Comment by troglobit** [comment]
Ah, silly little configure script reverted to GnuTLS of course .. thanks for the quick feedback!

**Comment by troglobit** [comment]
There, should be fixed as of a62e105 :smiley: :+1:

**Comment by rtorrentuser** [comment]
Everything is fine now. Thanx!

**Comment by troglobit** [comment]
@rtorrentuser Awesome, thanks for the feedback!! :heart:
