### ISSUE TITLE
Add support for custom user agent

### ISSUE THREAD

**Issue by eliz82** [troglobit/inadyn#153]
Hello, my dynamic dns provider request to provide a specific browser user agent to it's update.php page for the form to appear in the page.
In my bash script i'm using something like this:
_**curl -A "$AGENT" -d "username=$USERNAME&password=$PASSWORD&domain=$DOMAIN&ipaddr=$IP&change=Update" $URL**_
So i'm making a curl request to a page with a specific user agent and i'm filling a form and submit (POST) 

I have read the inadyn custom examples , but i can't find anyware in the documentation how to specifiy a user agent.
If this is not possible, please add support for this in the future version.

**Comment by troglobit** [comment]
Great idea, and also a good chance for a contributor to chip in and work on Open Source! :smiley: 

I don't have this requirement myself, so this one will have to be up to the community (or yourself) to add support for.

**Comment by troglobit** [comment]
Just added support for a global and per-provider `user-agent = STRING` setting to the GIT master branch.  It will be included in the upcoming v2.2 release of Inadyn.

Thank you for your contribution to Open Source! :smiley:

**Comment by eliz82** [comment]
thanks
