### ISSUE TITLE
Update FreeDNS URL

### ISSUE THREAD

**Issue by dko4er** [troglobit/inadyn#155]
FreeDNS updates fail on this request:

TRY(http_init(&client, "Sending update URL query"));
...
snprintf(buffer, sizeof(buffer), "/api/?action=getdyndns&sha=%s", digeststr);
...
logit(LOG_INFO, "Update URL query failed");

I could not find this URL /api/?action=getdyndns&sha=%s  on their site, it's probably outdated.

They offer many ways to update the IP including the randomized token updates, please check their /dynamic/v2/  API.

All supported update styles:

- Randomized Update Token
- Username and Password, inline
- Username and Password
- /nic/update

**Comment by troglobit** [comment]
Hi!

I have no problem updating my account on FreeDNS. What version of Inadyn are you using?  Have you checked your `inadyn.conf` against the man page? Did you notice the syntax was changed in v2.0?

**Comment by troglobit** [comment]
My config is similar to this:

``` cfg
 In-A-Dyn v2.0 configuration file format
period          = 300

provider default@freedns.afraid.org {
    ssl         = true
    username    = myuser
    password    =  verysecret
    hostname    = some.url.com
}
```

**Comment by dko4er** [comment]
I'm using inadyn 2.1.

The config looks similar:

# 
iface = enp0s3
period = 300

provider default@freedns.afraid.org {
    ssl            = true
    username	   = user
    password	   = pass
    hostname       = hostname.mooo.com
}

inadyn fails to update:

[user@localhost inadyn]$ ./inadyn --foreground --loglevel=7 --once
inadyn[24308]: In-a-dyn version 2.1 -- Dynamic DNS update client.
inadyn[24308]: Resolving hostname hostname.mooo.com => IP# <IP>
inadyn[24308]: Base64 encode user:pass for default@freedns.afraid.org ...
inadyn[24308]: Base64 encoded string: Base64_replaced
inadyn[24308]: Failed creating pidfile: Permission denied
inadyn[24308]: Get address for default@freedns.afraid.org
inadyn[24308]: Checking for IP# change, querying interface enp0s3
inadyn[24308]: Checking IPv4 address 192.168.0.101 ...
inadyn[24308]: IPv4 address 192.168.0.101 is valid.
inadyn[24308]: IPv6 address disallowed, enable with 'allow-ipv6 = true'
inadyn[24308]: Invalid/local address fe80::a00:27ff:fec4:3444 for enp0s3, skipping ...
inadyn[24308]: Checking IPv4 address 192.168.0.101 ...
inadyn[24308]: IPv4 address 192.168.0.101 is valid.
inadyn[24308]: Current IP# 192.168.0.101 at default@freedns.afraid.org
inadyn[24308]: Update forced for alias hostname.mooo.com, new IP# 192.168.0.101
inadyn[24308]: Sending IP# update to DDNS server, connecting to freedns.afraid.org(50.23.197.94:443)
inadyn[24308]: Sending IP# update to DDNS server, initiating HTTPS ...
inadyn[24308]: SSL connection using ECDHE-RSA-AES128-GCM-SHA256
inadyn[24308]: Certificate OK
inadyn[24308]: SSL server cert subject: /OU=Domain Control Validated/OU=EssentialSSL/CN=freedns.afraid.org
inadyn[24308]: SSL server cert issuer: /C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
inadyn[24308]: Sending update URL query, connecting to freedns.afraid.org(50.23.197.94:443)
inadyn[24308]: Sending update URL query, initiating HTTPS ...
inadyn[24308]: SSL connection using ECDHE-RSA-AES128-GCM-SHA256
inadyn[24308]: Certificate OK
inadyn[24308]: SSL server cert subject: /OU=Domain Control Validated/OU=EssentialSSL/CN=freedns.afraid.org
inadyn[24308]: SSL server cert issuer: /C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
inadyn[24308]: Successfully sent DDNS update using HTTPS!
inadyn[24308]: Successfully received DDNS update response (199 bytes) using HTTPS!
inadyn[24308]: Update URL query failed
inadyn[24308]: Sending alias table update to DDNS server: 
inadyn[24308]: DDNS server response: 
[user@localhost inadyn]$

**Comment by troglobit** [comment]
Thank you for the update!  

Not really sure why v2.1 doesn't work and unfortunately I don't have the time atm. to dig deeper into that. Sorry!  Do you think you could try the latest GIT¹ master?  I'm very close to releasing v2.2, which has a lot of fixes and refactoring that, at least on my end, seem to make FreeDNS work.

__
¹ you have to run `./autogen.sh` to get the `configure` script

**Comment by troglobit** [comment]
@dko4er did you manage to test with the latest GIT?

**Comment by dko4er** [comment]
Not yet, i'll test during the weekend.

**Comment by dko4er** [comment]
It's the same issue with the git version:

inadyn[19796]: Sending update URL query, connecting to freedns.afraid.org(50.23.197.94:443)
inadyn[19796]: Sending update URL query, initiating HTTPS ...
inadyn[19796]: SSL connection using ECDHE-RSA-AES128-GCM-SHA256
inadyn[19796]: Certificate OK
inadyn[19796]: SSL server cert subject: /OU=Domain Control Validated/OU=EssentialSSL/CN=freedns.afraid.org
inadyn[19796]: SSL server cert issuer: /C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
inadyn[19796]: Successfully sent DDNS update using HTTPS!
inadyn[19796]: Successfully received DDNS update response (199 bytes) using HTTPS!
inadyn[19796]: Update URL query failed
inadyn[19796]: Sending alias table update to DDNS server: 
inadyn[19796]: DDNS server response:

**Comment by troglobit** [comment]
@dko4er That's just weird. I really cannot reproduce your problem, works for me (see below) ... are you sure the account hasn't expired or anything like that?

Here's my `freedns.conf`:
```
period  = 300
iface   = virbr0

provider default@freedns.afraid.org {
    username   = user
    password   = pass
    hostname   = troglobit.homenet.org
}
```

Here's my slightly anonomized run:

```
$  ./src/inadyn --foreground --loglevel=7 --once -f ~jocke/Troglobit/inadyn/freedns.conf
inadyn[13386]: In-a-dyn version 2.2-rc1 -- Dynamic DNS update client.
inadyn[13386]: Resolving hostname troglobit.homenet.org => IP# 192.168.1.103
inadyn[13386]: Base64 encode user:pass for default@freedns.afraid.org ...
inadyn[13386]: Base64 encoded string: secretstring
inadyn[13386]: Get address for default@freedns.afraid.org
inadyn[13386]: Checking for IP# change, querying interface virbr0
inadyn[13386]: Checking IPv4 address 192.168.122.1 ...
inadyn[13386]: IPv4 address 192.168.122.1 is valid.
inadyn[13386]: Checking IPv4 address 192.168.122.1 ...
inadyn[13386]: IPv4 address 192.168.122.1 is valid.
inadyn[13386]: Current IP# 192.168.122.1 at default@freedns.afraid.org
inadyn[13386]: Update forced for alias troglobit.homenet.org, new IP# 192.168.122.1
inadyn[13386]: Sending IP# update to DDNS server, initiating HTTPS ...
inadyn[13386]: Sending IP# update to DDNS server, connecting to freedns.afraid.org(50.23.197.94:443)
inadyn[13386]: Certificate OK
inadyn[13386]: SSL server cert subject: OU=Domain Control Validated,OU=EssentialSSL,CN=freedns.afraid.org
inadyn[13386]: SSL server cert issuer: C=GB,ST=Greater Manchester,L=Salford,O=COMODO CA Limited,CN=COMODO RSA Domain Validation Secure Server CA
inadyn[13386]: Sending update URL query, initiating HTTPS ...
inadyn[13386]: Sending update URL query, connecting to freedns.afraid.org(50.23.197.94:443)
inadyn[13386]: Certificate OK
inadyn[13386]: SSL server cert subject: OU=Domain Control Validated,OU=EssentialSSL,CN=freedns.afraid.org
inadyn[13386]: SSL server cert issuer: C=GB,ST=Greater Manchester,L=Salford,O=COMODO CA Limited,CN=COMODO RSA Domain Validation Secure Server CA
inadyn[13386]: Successfully sent DDNS update using HTTPS!
inadyn[13386]: Successfully received DDNS update response (787 bytes) using HTTPS!
inadyn[13386]: Sending alias table update to DDNS server: GET /dynamic/update.php?aSTRINGQ=&address=192.168.122.1 HTTP/1.0
Host: freedns.afraid.org
User-Agent: inadyn/2.2-rc1 https://github.com/troglobit/inadyn/issues

inadyn[13386]: Successfully sent DDNS update using HTTPS!
inadyn[13386]: Successfully received DDNS update response (385 bytes) using HTTPS!
inadyn[13386]: DDNS server response: HTTP/1.1 200 OK
Server: nginx
Date: Sun, 05 Mar 2017 18:15:49 GMT
Content-Type: text/plain; charset=utf-8
Connection: close
Vary: Accept-Encoding
Cache-Control: no-store, no-cache, must-revalidate
Cache-Control: post-check=0, pre-check=0
Pragma: no-cache
Expires: Mon, 26 Jul 1997 05:00:00 GMT
X-Cache: MISS

Updated troglobit.homenet.org to 192.168.122.1 in 0.176 seconds
inadyn[13386]: Successful alias table update for troglobit.homenet.org => new IP# 192.168.122.1
```

And if I try to update again, too soon without any IP# change I get:

```
$  ./src/inadyn --foreground --loglevel=7 --once -f ~jocke/Troglobit/inadyn/freedns.conf
inadyn[13795]: In-a-dyn version 2.2-rc1 -- Dynamic DNS update client.
inadyn[13795]: Resolving hostname troglobit.homenet.org => IP# 192.168.122.1
inadyn[13795]: Base64 encode user:pass for default@freedns.afraid.org ...
inadyn[13795]: Base64 encoded string: secretstring
inadyn[13795]: Get address for default@freedns.afraid.org
inadyn[13795]: Checking for IP# change, querying interface virbr0
inadyn[13795]: Checking IPv4 address 192.168.122.1 ...
inadyn[13795]: IPv4 address 192.168.122.1 is valid.
inadyn[13795]: Checking IPv4 address 192.168.122.1 ...
inadyn[13795]: IPv4 address 192.168.122.1 is valid.
inadyn[13795]: No IP# change detected for default@freedns.afraid.org, still at 192.168.122.1
inadyn[13795]: Update forced for alias troglobit.homenet.org, new IP# 192.168.122.1
inadyn[13795]: Sending IP# update to DDNS server, initiating HTTPS ...
inadyn[13795]: Sending IP# update to DDNS server, connecting to freedns.afraid.org(50.23.197.94:443)
inadyn[13795]: Certificate OK
inadyn[13795]: SSL server cert subject: OU=Domain Control Validated,OU=EssentialSSL,CN=freedns.afraid.org
inadyn[13795]: SSL server cert issuer: C=GB,ST=Greater Manchester,L=Salford,O=COMODO CA Limited,CN=COMODO RSA Domain Validation Secure Server CA
inadyn[13795]: Sending update URL query, initiating HTTPS ...
inadyn[13795]: Sending update URL query, connecting to freedns.afraid.org(50.23.197.94:443)
inadyn[13795]: Certificate OK
inadyn[13795]: SSL server cert subject: OU=Domain Control Validated,OU=EssentialSSL,CN=freedns.afraid.org
inadyn[13795]: SSL server cert issuer: C=GB,ST=Greater Manchester,L=Salford,O=COMODO CA Limited,CN=COMODO RSA Domain Validation Secure Server CA
inadyn[13795]: Successfully sent DDNS update using HTTPS!
inadyn[13795]: Successfully received DDNS update response (787 bytes) using HTTPS!
inadyn[13795]: Sending alias table update to DDNS server: GET /dynamic/update.php?aSTRINGQ=&address=192.168.122.1 HTTP/1.0
Host: freedns.afraid.org
User-Agent: inadyn/2.2-rc1 https://github.com/troglobit/inadyn/issues

inadyn[13795]: Successfully sent DDNS update using HTTPS!
inadyn[13795]: Successfully received DDNS update response (367 bytes) using HTTPS!
inadyn[13795]: DDNS server response: HTTP/1.1 200 OK
Server: nginx
Date: Sun, 05 Mar 2017 18:18:10 GMT
Content-Type: text/plain; charset=utf-8
Connection: close
Vary: Accept-Encoding
Cache-Control: no-store, no-cache, must-revalidate
Cache-Control: post-check=0, pre-check=0
Pragma: no-cache
Expires: Mon, 26 Jul 1997 05:00:00 GMT
X-Cache: MISS

ERROR: Address 192.168.122.1 has not changed.
inadyn[13795]: Successful alias table update for troglobit.homenet.org => new IP# 192.168.122.1
```

**Comment by dko4er** [comment]
I'm going to create another account and test

**Comment by dko4er** [comment]
It's the same with brand new account there. What are your settings for Dynamic DNS in the account. Do you use update client v1 or v2 and which type?

**Comment by troglobit** [comment]
Inadyn uses the v1 API still.  Don't know what you mean by "which type"?

**Comment by dko4er** [comment]
Oh wow, figured the problem. I used email id as the username instead of user id. It wasn't obvious from the error...

**Comment by troglobit** [comment]
@dko4er Ah, good to hear you found the root cause! Cheers :smiley:
