### ISSUE TITLE
Performance: should we use sscanf?

### ISSUE THREAD

**Issue by ysc3839** [troglobit/inadyn#160]
For example: [plugins/cloudxns.c](../blob/master/plugins/cloudxns.c).
I use `sscanf` to parse domain info. But I think using `strstr` and `strchr` is better.

**Comment by troglobit** [comment]
It's not optimal, but not too bad. Sometimes code readability is to be preferred, in particular in cases when you look for a string *in a context*. Just looking for a substring with `strstr()` can be deceitful and give false positives unless you also look for surrounding text.

In the case of cloudxns.c I'd probably go for `strtok()` and `strcmp()` to split up the stream in `{`, `}`,  and `:` separated tokens.

**Comment by troglobit** [comment]
Closing. We now have two (!) JSON implementations in Inadyn, so any changes to refactor/optimize performance should probably first start with refactoring this plugin to use `include/jsmn.h` (jasmine).
