### ISSUE TITLE
WiX

### ISSUE THREAD

**Issue by cawilliamson** [troglobit/inadyn#162]
Hey there!

I'm currently in the pursuit of a DDNS client capable of updating WiX records.

Their documentation sucks and there doesn't seem to be a simple process for achieving this - was wondering if anyone is achieving this already via either inadyn (ideally) or another tool / process?

Thanks!

**Comment by troglobit** [comment]
Nope, unfortunately not.

**Comment by ysc3839** [comment]
If you have documentation I can have a try.

**Comment by cawilliamson** [comment]
@ysc3839 Thanks for the offer! I was planning to contribute it myself but sadly can'd find *any* useful documentation for DNS management with WiX. It seems they're keen to take on your domain to point it to their website but dynamic DNS? No interest at all.

What I've done in the meantime is to setup a DuckDNS DDNS domain, added a rundeck script to push my IP to it hourly and pointed a CNAME record from my main domain to that. Not ideal but it works for now.

I'll close off the ticket though unless anyone finds some docs. :)
