### ISSUE TITLE
External IP resolution using DNS

### ISSUE THREAD

**Issue by eskhool** [troglobit/inadyn#166]
Presently a HTTP request is sent to resolve the external DNS address whereas the same can be done with a lighter DNS query? Has this been considered as an option for inadyn?

**Comment by ysc3839** [comment]
I don't think DNS supports this.

**Comment by troglobit** [comment]
@eskhool Curious, could you explain a bit more how this would work? What do you mean by _"a lighter DNS query"_?

I mean, the whole point of using Inadyn is to figure out what IP address your ISP has given you today and then report that IP to a DNS/DDNS provider so your name is in sync with your IP ... the DNS queries I know of do the reverse: look up the IP from the name.

**Comment by eskhool** [comment]
@ysc3839, it indeed does. or at least the popular opendns does. 
@troglobit
dig +short myip.opendns.com @resolver1.opendns.com
This is just a DNS query (UDP in and out) as opposed to a full HTTP session that needs to be established and not to mention the load on the Web server.

The only use case where this won't work is in the case of a proxy and a firewall which blocks direct DNS but other than that this is a great option.

**Comment by troglobit** [comment]
@eskhool Still don't understand what problem you are trying to solve here?

Inadyn works like this, briefly:

1. Startup:
   - Check for a cache file from previous run, answers question: what IP did I report last time?
   - If no cache file: _do DNS lookup_ to figure out the last reported IP
2. Main loop
   - Check current IP using selected checkip method for provider or `.conf` file, can be any of:
     - Read IP from interface
     - Call external script
     - Send HTTP request to DDNS provider's checkip server, or https://api.ipify.org, and parse reply
   - If current IP differs from cached (or DNS) IP, send HTTP update to DDNS provider

Where in the above flow do you want to do what with DNS?

**Comment by ysc3839** [comment]
@eskhool Doesn't work with Google DNS (8.8.8.8).

**Comment by troglobit** [comment]
Ah, now I think I understand, I should've read the topic more closely. Apologies.

@eskhool Is it an OpenDNS plugin to Inadyn you are requesting?  

Similar to #87, requesting support for https://hn.org which uses HTTP POST, support for different query/update API's is currently limited in Inadyn.   If you can cook up a pull request for this, with an OpenDNS plugin as example, we can discuss more around that code.

**Comment by ysc3839** [comment]
@troglobit He mean check current IP without HTTP request.

**Comment by Duncaen** [comment]
`checkip-command =  "dig +short myip.opendns.com @208.67.222.222 @208.67.220.220"`

**Comment by troglobit** [comment]
@ysc3839 Ah, well then @Duncaen had a quite spot on reply :smiley: :+1:

**Comment by eskhool** [comment]
@Duncaen, indeed that is the answer I was looking for. 👍
