### ISSUE TITLE
Inadyn v1 exec function support?

### ISSUE THREAD

**Issue by ysc3839** [troglobit/inadyn#168]
https://github.com/troglobit/inadyn/blob/1.99.15/src/cmd.c#L111-L113
Why it is removed in v2?

**Comment by troglobit** [comment]
It's not, most of the commands and configuration of Inadyn wen through a huge overhaul, not many
commands survived unmodified, but this one remains, although it's not available in `inadyn.conf`,
only from the command line:

    -e, --exec=/path/to/cmd        Script to run on successful DDNS update

**Comment by ysc3839** [comment]
OK.

**Comment by l0ddej0kk0** [comment]
Hi,
i just got bitten by first Ubuntu's deprecated inadyn.conf and then by this.
I do hope i could mitigate that by adding my shell command after --exec= to the DAEMON_ARGS in /etc/init.d/inadyn.

I'd like it very much if this is to come again to inadyn.conf.

regards, l0ddej0kk0
