### ISSUE TITLE
/etc/inadyn.conf:10: no such option 'proxy'

### ISSUE THREAD

**Issue by ysc3839** [troglobit/inadyn#169]
Please check if it's a bug.

**Comment by troglobit** [comment]
It's been disabled for the upcoming v2.2 release, see ddde5c1. If I understood you correctly earlier on it wasn't ready yet?

**Comment by ysc3839** [comment]
Here. https://github.com/troglobit/inadyn/blob/master/src/conf.c#L448

**Comment by troglobit** [comment]
Ah, yeah that needs to be disabled as well. My bad!

**Comment by troglobit** [comment]
Fixed in 897b085
