### ISSUE TITLE
inadyn.service uses ConditionPathExists=/etc/inadyn.conf despite ./configure --prefix

### ISSUE THREAD

**Issue by idodeclare** [troglobit/inadyn#170]
I tested a build and installation per "Building from GIT", but the deployed inadyn.service has a precondition to /etc/inadyn.conf despite also requiring /usr/local/etc/inadyn.conf per the default ./configure --prefix.

I fixed the deployment using a symlink.

**Comment by troglobit** [comment]
Thanks for the report, the bug was in `inadyn.service.in`.  A fix will be pushed shortly.

**Comment by troglobit** [comment]
There, fixed.  As usual with changes like this, remember to run `./autogen.sh` to regenerate the configure when building from GIT.  (Not required foor release tarballs.)

**Comment by idodeclare** [comment]
Thank you—it tests well now.

**Comment by troglobit** [comment]
NP
