### ISSUE TITLE
Fedora 26 problem

### ISSUE THREAD

**Issue by GittyUpTom** [troglobit/inadyn#171]
After updating to Fedora 26, my old copy of inadyn works fine, but I decided to update inadyn.
After a git clone, I ran ./autogen. The last two lines of the output were:
autoconfig: no config.status: cannot re-make
autoconfig: Leaving directory `.'

I ran ./configure anyway and it failed with the errors:
./configure: line 6209: syntax error near unexpected token disabled-shared'
./configure: line 6209: `LT_INIT(disable-shared static)' 

Is it Fedora 26 or am I doing something wrong?

**Comment by troglobit** [comment]
Scary to run bleeding edge like that! 😉
Do you have libtool installed, looks like a problem there.

**Comment by GittyUpTom** [comment]
You're the best! With libtools and libconfuse-devel installed, all is well.

**Comment by troglobit** [comment]
Awesome, glad to be of help! ☺️👍
