### ISSUE TITLE
Interface went wrong after SIGHUP restart

### ISSUE THREAD

**Issue by ysc3839** [troglobit/inadyn#172]
After restart inadyn using `killall -SIGHUP inadyn`. 'iface' went wrong.
For example:
`Jul 24 00:01:03 inadyn[2463]: Checking for IP# change, querying interface �:	`

**Comment by troglobit** [comment]
Did you change the .conf file, out just send SIGHUP? I'll look into it!

**Comment by ysc3839** [comment]
I didn't change the .conf file.
In [conf.c#606](https://github.com/troglobit/inadyn/blob/897b085476cdf71a3e6b92c8e8a41755c5143d8a/src/conf.c#L606), it checks whether 'iface' is empty. When restart, the 'iface' remains not empty, so it won't load at the next time.

**Comment by troglobit** [comment]
Thanks.

Aha, hmmm ... seems I'll have to refactor that code to handle this better.

**Comment by troglobit** [comment]
Should work better as of e91cf44, please reopen this issue if not.

Thank you for the report!
