### ISSUE TITLE
"Error: unexpectedly disconnected from boot status daemon" on startup 

### ISSUE THREAD

**Issue by tuanden0** [troglobit/inadyn#173]
Hi sir,

I'm using Raspibian Jessie and Inadyn version 1.99.4.
Everything is OK except when I reboot or startup, the Inadyn didn't run success for the first. I had to wait for  a 5 min (my period is 5 min) to make it checked again or I had to restart inadyn service. I set up inadyn run as daemon but it's not work. Can you help me, Sir?

My config:
/etc/inadyn.conf

username myusername
password mypassword
system default@freedns.afraid.org
period 300
syslog
verbose 1
cachefile /var/run/inadyn.cache

/etc/init.d/inadyn
RUN_DAEMON=${RUN_DAEMON:-yes}
USER=${USER:-root}
GROUP=${GROUP:-root}

/etc/default/inadyn
RUN_DAEMON="yes"
RUN_IPUP="no"
USER="root"
GROUP="root"

**Comment by troglobit** [comment]
HI,

sorry but that version is simply too old for us to support. The Inadyn version that comes with Rasbian, which is based on Debian, is their responsibility.  The latest official relase from us, this GitHub project, is v2.1 and there I believe this problem you report is not an issue anymore.

Please report your problem to Rasbian/Debian instead.

**Comment by troglobit** [comment]
... or [try our the latest release](https://github.com/troglobit/inadyn/releases/tag/v2.1), of course. Even though that requires building from source.

**Comment by tuanden0** [comment]
I will try the latest release.
Thank You, Sir!

**Comment by tuanden0** [comment]
Sorry for reopen this issue, but I tried to build and install the latest version and still get the issue.

After reboot, I used command "sudo /etc/init.d/inadyn status" to check the service and got this:

"Failed resolving hostname freedns.afra...
Failed to get IP address for default@..."

This is my new config:
/etc/inadyn.conf

period = 3600
provider freedns.afraid.org {
username = myusername
password = mypassword
hostname = myhost
ssl=false
check-ip=false
}

**Comment by troglobit** [comment]
Um, you do need to have a working network set up. Be able to ping or otherwise reach your DDNS provider. Inadyn does not take care of that.

**Comment by troglobit** [comment]
OK, just to be clear.  You need to have basic networking online on your Raspberry Pi first.  A simple ping to an outside host, or DNS lookup with `host`, verifies this. Like this, for instance:

```sh
$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=51 time=3.81 ms
^C
$ host freedns.afraid.org
freedns.afraid.org has address 50.23.197.94
```
If that does not work, then you need to look into your network setup first.

**Comment by tuanden0** [comment]
I can ping to Google (8.8.8.8) and server freedns, and I'm sure that my network is good. But inadyn couldn't start success at first after reboot or startup. I had to run "sudo /etc/init.d/inadyn restart" to restart daemon after reboot to run inadyn. It seem the issue still be there even I install the latest version.

**Comment by troglobit** [comment]
No problem, glad you got it working! ☺️
