### ISSUE TITLE
Build error in inadyn-gnutls.c

### ISSUE THREAD

**Issue by Papafox** [troglobit/inadyn#174]
Just attempted to build the latest master and got:

```
  CC       inadyn-gnutls.o
gnutls.c: In function ‘ssl_open’:
gnutls.c:226:65: error: ‘intptr_t’ undeclared (first use in this function); did you mean ‘__intptr_t’?
  gnutls_transport_set_ptr(client->ssl, (gnutls_transport_ptr_t)(intptr_t)client->tcp.socket);
                                                                 ^~~~~~~~
                                                                 __intptr_t
gnutls.c:226:65: note: each undeclared identifier is reported only once for each function it appears in
gnutls.c:226:74: error: expected ‘)’ before ‘client’
  gnutls_transport_set_ptr(client->ssl, (gnutls_transport_ptr_t)(intptr_t)client->tcp.socket);
                                                                          ^~~~~~

```

Is this a problem with inadyn or do I have a dependency issue?

Matthew

**Comment by troglobit** [comment]
What OS are you on?

`intptr_t` is declared in `/usr/include/stdint.h`, which unfortunately `gnutls.c` doesn't include. I suspect it gets drawn in as a dependency by another system header on Debian/Ubuntu Linux systems.

I'm pushing a fix rn that should help.

**Comment by Papafox** [comment]
It's running ArchLinux on a ARM32 system.  The relevant part of stdint.h is

```
/* Types for `void *' pointers.  */
#if __WORDSIZE == 64
# ifndef __intptr_t_defined
typedef long int                intptr_t;
#  define __intptr_t_defined
# endif
typedef unsigned long int       uintptr_t;
#else
# ifndef __intptr_t_defined
typedef int                     intptr_t;
#  define __intptr_t_defined
# endif
typedef unsigned int            uintptr_t;
#endif
```
so it should have compiled ```typedef int intptr_t```

I looked through the headers and I can't see where ```stdint.h``` is included.  ```gnutls.c``` includes ```gnutls/x509.h```.  ```x509.h``` includes ```gnutls/gnutls.h```, which includes ```stddef.h```, which doesn't include anything else.  So it doesn't look like ```stdint.h``` is included anywhere.

Matthew

**Comment by Papafox** [comment]
Just tested the fix and the problem has been resolved.  Thanks for all the help.

Matthew

**Comment by troglobit** [comment]
Ah, well I should definitely set up a build machine with Arch to catch more such problems in the future.

Glad the fix worked! 😊
