### ISSUE TITLE
error on boot: Failed resolving hostname ip1.dynupdate.no-ip.com: Temporary failure in name resolution

### ISSUE THREAD

**Issue by imthenachoman** [troglobit/inadyn#176]
I have `2.2` installed on Debian 9 (Stretch). If I run `inadyn -1` it properly updates my http://noip.com account. However, if I try to get `inadyn` to start on boot using the supplied `systemd` service I get an error. If I delete the cache files in `/var/cache/inadyn/*` and do a `systemctl restart inadyn.service` then it does work. I cannot figure out why it won't work on boot. 

    Oct 01 22:32:32 myServer inadyn[667]: In-a-dyn version 2.2 -- Dynamic DNS update client.
    Oct 01 22:32:32 myServer inadyn[667]: Guessing DDNS plugin 'default@no-ip.com' from 'no-ip.com:1'
    Oct 01 22:32:32 myServer inadyn[667]: Guessing DDNS plugin 'default@no-ip.com' from 'no-ip.com:2'
    Oct 01 22:32:32 myServer inadyn[667]: Guessing DDNS plugin 'default@no-ip.com' from 'no-ip.com:3'
    Oct 01 22:32:32 myServer inadyn[667]: Failed resolving hostname ip1.dynupdate.no-ip.com: Temporary failure in name resolution
    Oct 01 22:32:32 myServer inadyn[667]: Failed to get IP address for default@no-ip.com, giving up!
    Oct 01 22:32:32 myServer inadyn[667]: Failed resolving hostname ip1.dynupdate.no-ip.com: Temporary failure in name resolution
    Oct 01 22:32:32 myServer inadyn[667]: Failed to get IP address for default@no-ip.com, giving up!
    Oct 01 22:32:32 myServer inadyn[667]: Failed resolving hostname ip1.dynupdate.no-ip.com: Temporary failure in name resolution
    Oct 01 22:32:32 myServer inadyn[667]: Failed to get IP address for default@no-ip.com, giving up!

Here my `/etc/inadyn.conf` file:

    # In-A-Dyn v2.0 configuration file format
    period          = 300

    provider no-ip.com:1 {
        username    = myUserName
        password    = myPassword
        hostname    = url1.noip.me
    }

    provider no-ip.com:2 {
        username    = myUserName
        password    = myPassword
        hostname    = url2.noip.me
    }

    provider no-ip.com:3 {
        username    = myUserName
        password    = myPassword
        hostname    = url3.noip.me
    }

Here is my `/lib/systemd/system/inadyn.service` file:

    [Unit]
    Description=Internet Dynamic DNS Client
    Documentation=man:inadyn
    Documentation=man:inadyn.conf
    Documentation=https://github.com/troglobit/inadyn
    ConditionPathExists=/etc/inadyn.conf
    After=network-online.target
    Requires=network-online.target

    [Service]
    Type=simple
    ExecStart=/usr/sbin/inadyn -n -s

    [Install]
    WantedBy=multi-user.target

**Comment by troglobit** [comment]
Hi,

this is possibly a Debian related problem, the `network-online.target` does not seem to work.  I found this when I googled your problem:

https://unix.stackexchange.com/questions/209832/debian-systemd-network-online-target-not-working

**Comment by imthenachoman** [comment]
Well hot damn. Thank you! I guess this issue can be closed.

**Comment by imthenachoman** [comment]
For anyone else that has this issue I was able to fix it with `systemctl enable systemd-networkd-wait-online.service`.  More information is available at https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/.
