### ISSUE TITLE
is there anyway to ignore the cache?

### ISSUE THREAD

**Issue by imthenachoman** [troglobit/inadyn#177]
Is there anyway to have inadyn ignore the cache? For example, say it sets the IP of my noip account to 1.2.3.4 and then I go to noip and change the IP to 2.3.4.5. My IP is still 1.2.3.4 so it should force update my noip IP. Right now it won't because inadyn has 1.2.3.4 in the cache and since my IP hasn't changed it doesn't bother doing an update.

**Comment by ysc3839** [comment]
killall -SIGUSR1 inadyn

**Comment by imthenachoman** [comment]
I mean when it is in daemon mode. Like it should always ignore the cache and always force an update, regardless if the machine's web/public IP did not change.

**Comment by troglobit** [comment]
The whole point of the cache is to prevent Inadyn from updating when there has been no change -- the reason for this is that most (possibly even all?) DDNS providers lock your account if there are too frequent or unnecessary updates.

If you really want to play with fire, check out the global `forced-update = SEC` setting, setting it to the same or less than the update interval should be sufficient.  Or set up an inotify/dnotify/cronjob script to remove the cache file(s), for a more granular per-provider set up.

**Comment by imthenachoman** [comment]
Understood. You are right. When I think about it there is no reason to force update if the public IP hasn't changed. Thank you!
