### ISSUE TITLE
Easydns plugin seems broken

### ISSUE THREAD

**Issue by nalipaz** [troglobit/inadyn#179]
I was not getting ip updates with the easydns plugin. However, based on [their api](https://fusion.easydns.com/Knowledgebase/Article/View/102/0/dynamic-dns) I used a custom provider and was able to update my ip. The settings I used were:
```
# Inadyn v2.0 configuration file format
allow-ipv6 = true
period = 3600
forced-update = 2419200

custom easydns {
    username         = myusername
    password         = mytoken
    ddns-server      = api.cp.easydns.com
    ddns-path        = "/dyn/generic.php?hostname=%h&myip=%i"
    hostname         = mysubdomain.example.com
}
```

I believe the current plugin uses an outdated server address and endpoint.

**Comment by troglobit** [comment]
Awesome, Inadyn relies heavily on users like you giving feedback like this!  Do you think you could provide a pull request with a patch?

**Comment by nalipaz** [comment]
@troglobit yes I will do so when I get a moment.

Best!

**Comment by nalipaz** [comment]
closing in favor of PR #180
