### ISSUE TITLE
Can't have comma in password

### ISSUE THREAD

**Issue by signo-** [troglobit/inadyn#183]
I generated a password for dnsomatic that has a comma in it and inadyn refuses to start stating "unexpected token ','"

Is there a way around this? I can't seem to escape it or anything.

**Comment by troglobit** [comment]
What version of Inadyn are you using?
What does your .conf file look like?

**Comment by ysc3839** [comment]
@signo- Try `password = "$4Qqwertyu,iop"`.

**Comment by signo-** [comment]
Looks like that works, I tried that initially and it didn't work. Guess I had a typo in it... Thanks for the help!

**Comment by troglobit** [comment]
Great to hear that it worked!  Thank you @ysc3839 for stepping up, again! :smiley: :+1:

**Comment by signo-** [comment]
@troglobit / @ysc3839 , As a heads up after testing a bit it looks like part of the problem is that dnsomatic auth fails if you pass it an `&`.  The original password I was using contained that. 

It looks like a dnsomatic specific issue though since I can pass `&` to other providers and auth succeeds with no issue.

**Comment by troglobit** [comment]
Usually that would indicate an encoding¹ problem with the username/password. If you figure it out we'd appreciate you filing a new issue.

__  
¹ https://tools.ietf.org/html/rfc7617
