### ISSUE TITLE
Wrong example for freedns provider

### ISSUE THREAD

**Issue by allofmex** [troglobit/inadyn#185]
May you please update your example configuration for provider freedns in [https://github.com/troglobit/inadyn/blob/master/README.md](https://github.com/troglobit/inadyn/blob/master/README.md)

This is wrong:
```
provider freedns {
    username ...
}
```
it causes inadyn error "Invalid DDNS provider freedns".

It should be 
`provider default@freedns.afraid.org {
    ...
}`

(On http://troglobit.com/project/inadyn/ you are using "provider freedns.afraid.org..." which is not working too)

Your example here is correct https://github.com/troglobit/inadyn/blob/master/examples/freedns.conf

Thank you very much

**Comment by troglobit** [comment]
What version of Inadyn are you using?  The latest version supports partial matching and has removed the need for `default@`.

**Comment by allofmex** [comment]
The Docker image I use is sadly not yet updated to latest version (still 2.1) and I didn't expected partial matching. This should be the reason why it didn't worked for me. Thanks for your hint. Issue may be closed.

(Just a suggest: using the full name in example would work on older AND latest version.)

**Comment by troglobit** [comment]
I see, that explains it.  OK, closing ...

(It's a good point, although I'd very much like to achieve the opposite -- break with the old completely. Sure, it has the side effect that it might confuse users.  But I'd much rather take on that extra support in this case.  :)

Cheers!
