### ISSUE TITLE
Debian binary install broken

### ISSUE THREAD

**Issue by acolomb** [troglobit/inadyn#194]
Seems we didn't check carefully enough before making some Debian-related changes in #192. The inadyn binary is already installed in `$prefix/sbin/` since commit c7e674d4ab30f8cda5db1b7de90c17b65d18b8d9.

The `debian/links` file (should be `debian/inadyn.links`, see https://www.debian.org/doc/manuals/maint-guide/dother.en.html#links) tries to install a symlink `/usr/sbin/inadyn -> /usr/bin/inadyn`, which overwrites the actual binary in `sbin`. Sorry for messing up the current Debian package, I must have tested an intermediate version in #192.

So I can make a PR to fix this, just wanted to make sure it's actually wise to install in `$prefix/sbin`. By specifying different config and cache files, any local user can benefit from Inadyn. I don't see why it should be handled as a system administration tool, according to the Filesystem Hierarchy Standard. It's rather an "online service helper tool", where access is controlled by the service's authentication.

**Comment by troglobit** [comment]
Ouch, thank you for checking! I didn't test the `.deb` myself either ... I'd very much appreciate if you could look into this with a PR. 

I've spent a lot of time debating with myself the correct location of the binary. My reasoning though, has time and time again come back to the fact that the main intended use-case is to run as a system level daemon, using `/etc/inadyn.conf`, which is also what the `.deb` package (imported from Debian) provides with the new neat debconf dialogs and whatnot. Therefore I'd prefer to keep things like that, but a symlink from sbin to bin is definitely useful for non-root users.

**Comment by acolomb** [comment]
There you go.  I understand the reasoning about it "primarily" being a system service.  After all, the default mode is to periodically check in the background.  Nonetheless, it's a useful tool for any user.  Since the advent of systemd, just about any user-executable binary can easily be invoked as a "system" or "user" service.
