### ISSUE TITLE
Custom repository

### ISSUE THREAD

**Issue by Makishima** [troglobit/inadyn#201]
Hello.
Could you please make custom repository so we can easily install up-to-date version on Ubuntu/Debian and don't build manually from git?

**Comment by troglobit** [comment]
That's in progress, http://deb.troglobit.com/, but currently a low-priority project for me. I've been planning to target the latest stable Debian and Ubuntu LTS releases, but only for 64-bit x86.

**Comment by Makishima** [comment]
I'm glad to hear that you are working on it but on other side last update was on Oct. 2017 as I can see.
If its become available for 16.04+ and Debian 8/9 it would be enough in my opinion.

**Comment by troglobit** [comment]
Yup, it's been a while. It's a low-priority side project of my own, I'm not paid to work on it.

**Comment by troglobit** [comment]
Done, finally.  The v2.6 relase of In-a-dyn can be installed like this:

```sh
curl -sS https://deb.troglobit.com/pubkey.gpg | sudo apt-key add -
echo "deb [arch=amd64] https://deb.troglobit.com/debian stable main" | sudo tee /etc/apt/sources.list.d/troglobit.list
sudo apt-get update && sudo apt-get install inadyn
```
