### ISSUE TITLE
Inadyn does not accept succesful update response from dns server

### ISSUE THREAD

**Issue by Knudch** [troglobit/inadyn#202]
I have used inadyn-mt for a long time without any issues

Now I have updated my server from F19 to F27 (inadyn 2.28)
And suddenly inadyn-mt does not accept the positive response from my dyndns provider
I have tried a lot fidling around with svr_rsp_success parm with no luck
name and PW is replaced with XXXXXX in the attached files
Clip from message file and the inadyn-mt.conf
[f27-messages-cut.txt](https://github.com/troglobit/inadyn/files/1700964/f27-messages-cut.txt)
[inadyn-mt.txt](https://github.com/troglobit/inadyn/files/1700969/inadyn-mt.txt)

**Comment by troglobit** [comment]
Wrong upstream project, dude.
