### ISSUE TITLE
Can't generate Makefile

### ISSUE THREAD

**Issue by arun-gurung** [troglobit/inadyn#206]
[log.txt](https://github.com/troglobit/inadyn/files/1892822/log.txt)

**Comment by troglobit** [comment]
When building from GIT you need to run `./autogen.sh` before calling `./configure` to generate the `Makefile`.

I do however recommend downloading the latest release instead of working directly with the latest GIT master. (Unless you plan to contribute a pull-request :)

**Comment by troglobit** [comment]
This is documented in the README, see https://github.com/troglobit/inadyn#building-from-git for more details.

**Comment by arun-gurung** [comment]
Thanks.
