### ISSUE TITLE
Support for "nochg" answers for generic plugin (applies to selfhost.de)

### ISSUE THREAD

**Issue by RMerl** [troglobit/inadyn#214]
I've been debugging inadyn support for selfhost.de's DynDNS service.  Turns out that it can return "nochg" if the IP hasn't changed since last time.  However, plugins/generic.c isn't listing "nochg" in its generic_responses[] array.  This causes inadyn to return an error when trying to update and your IP hasn't changed.

I would suggest adding "nochg" to that array, in case other custom providers might also be returning this message.  In the meantime I have worked around it by providing a custom ddns-response parameters to inadyn.conf.

If you are interested in natively supporting selfhost.de, here is a working custom config:

```
custom selfhost {
        ddns-server = carol.selfhost.de
        ddns-path = "/nic/update?hostname=%%h&myip=%%i"
        hostname = HOSTNAMEselfhost.eu
        username    = "userid"
        password    = "password"
        ddns-response = {"nochg", "good" }
}
```

**Comment by troglobit** [comment]
Thank you for the report, the issue has been fixed in 4760de0.  Implementing a dedicated plugin for selfhost.de should be a listed in a separate issue.
