### ISSUE TITLE
Add support for selfhost.de

### ISSUE THREAD

**Issue by RMerl** [troglobit/inadyn#215]
Selfhost.de's DynDNS service uses a syntax compatible with inadyn's generic plugin.  The following config file has been successfully tested with inadyn 2.4:

```
custom selfhost {
        ddns-server = carol.selfhost.de
        ddns-path = "/nic/update?hostname=%%h&myip=%%i"
        hostname = HOSTNAMEselfhost.eu
        username    = "userid"
        password    = "password"
        ddns-response = {"nochg", "good" }
}
```

The ddns-response line can be dropped after 2.4, now that plugins/generic.c can recognize the nochg response.

Authentication is done through Basic HTTP.

This could probably be easily be supported natively based on these info.  I have a test account I'd be willing to privately share with the developer if needs be (that account was only used in my own work in adding support for it in my Asuswrt-Merlin project).

**Comment by troglobit** [comment]
Shouldn't be too difficult to fix.  I'm a bit stressed out over other, more pressing, matters and projects atm., but anyone can help out.  It looks very much like you can cut-and-paste a working plugin from just about any of the other ones.

**Comment by jorhett** [comment]
@RMerl god knows you know how to create a PR right? ;-)

**Comment by RMerl** [comment]
@jorhett While I've been doing dev work with Github for 6 years now, it was actually the first time I created a PR for another project.

Don't know if I'll have the time to work on a selfhost plugin myself, currently busy with my own project's release schedule.

**Comment by troglobit** [comment]
Hmm, they do look *very* similar to other Dyn.com clones.  I can whip up speculative support on master if someone else can test it.

Do you know if they have a dedicated, or recommended, checkip-server?

**Comment by troglobit** [comment]
If anyone could test e810cc3 I'd be very happy :)

**Comment by RMerl** [comment]
I should be able to test it later today.

I can also email you my DDNS login credentials if you want to test it right now.

**Comment by RMerl** [comment]
Can't find anything about a dedicated IP checker, but I did find this extended API documetnation:

https://selfhost.de/cgi-bin/selfhost?p=document&name=api

**Comment by troglobit** [comment]
@RMerl Thanks, much appreciated.  If we can have this tested today I can do a new release tomorrow, or Saturday at the latest.

Yeah, I found that PDF too. Nothing much to add from what we (I) already know about how Dyn works,
so chances are good this will work.  The currently hard coded checkip-server uses Dyn's checkip by default.

**Comment by RMerl** [comment]
Login credentials emailed.

**Comment by RMerl** [comment]
I was just about to send a pull request for the register/unregister - just finished testing it successfully on my end.

**Comment by troglobit** [comment]
@RMerl thank you for that, and sorry for missing the register/unregister stuff before. Having loging creds speeded up testing considerably! :)
