### ISSUE TITLE
Build fails on Sierra?

### ISSUE THREAD

**Issue by jorhett** [troglobit/inadyn#222]
The binary builds for Homebrew fail on Sierra as reported in homebrew/homebrew-core#32579

```
../lib/utimensat.c:40:15: error: use of undeclared identifier 'AT_SYMLINK_NOFOLLOW'
        if ((flags & AT_SYMLINK_NOFOLLOW) == AT_SYMLINK_NOFOLLOW)
                     ^
../lib/utimensat.c:40:39: error: use of undeclared identifier 'AT_SYMLINK_NOFOLLOW'
        if ((flags & AT_SYMLINK_NOFOLLOW) == AT_SYMLINK_NOFOLLOW)
                                             ^
2 errors generated.
```

It would appear that this is a common problem where we need an ifdef for older macOS, I think it's well described here: mpartel/bindfs#6

**Comment by troglobit** [comment]
Inadyn has a wrapper for systems that don't have `utimensat()`, the issue seems to be that I did not take into account the systems that also don't have `AT_SYMLINK_NOFOLLOW`.  So it's quite possible a Sierra build would be possible by adding the following to `include/compat.h`:

```C
#ifndef AT_SYMLINK_NOFOLLOW
#define AT_SYMLINK_NOFOLLOW 0x100
#endif
```

**Comment by troglobit** [comment]
I don't know how Homebrew works, but 57bdcc0 should be simple enough to add as a patch, or similar, to the macOS build.
