### ISSUE TITLE
Automated build on Docker Hub

### ISSUE THREAD

**Issue by jeanralphaviles** [troglobit/inadyn#228]
Now that `inadyn` has an [official Dockerfile](https://github.com/troglobit/inadyn/blob/master/Dockerfile), we should have an official automated build on [Docker Hub](https://hub.docker.com).

Searching on Docker Hub for projects named `inadyn`, there are already [9 repositories](https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=inadyn&starCount=0). The most popular of which, [stanback/alpine-inadyn](https://hub.docker.com/r/stanback/alpine-inadyn), is running v2.2.1 which is over a year old.

With an official automated build, users will kept up to date. The Docker website has [a guide](https://docs.docker.com/docker-hub/builds/) for setting up an automated build on Docker Hub.

Perhaps the image should be called `troglobit/inadyn` to reflect the name of the repository and should be mentioned in the README.

**Comment by troglobit** [comment]
Sure, that's a good idea.  I can look into it, thanks for the helpful summary!

**Comment by troglobit** [comment]
Finally got some time over to work on Inadyn again, albeit briefly. A new release, v2.6, is out and I think I've managed to set up Docker Hub properly: https://hub.docker.com/r/troglobit/inadyn
