### ISSUE TITLE
Starting DynDNS client: inadyn: No DDNS provider setup in configuration

### ISSUE THREAD

**Issue by tavishg** [troglobit/inadyn#237]
I'm not sure if this is a bug.

I'm having problems using inadyn client version 1.99 on Debian Stretch running on a Raspberry PI (ARM). I am getting the following error message when I try to start the daemon with systemctl:

 "Cannot find DDNS provider freedns.afraid.org, check your spelling."

I've tried:
freedns
freedns.afraid.org
https://freedns.afraid.org
and http://freedns.afraid.org

My contents for /etc/default/inadyn are:

```
# Please note, /etc/inadyn.conf should be properly configured before 
# running inadyn
# Set to "yes" if inadyn should run in daemon mode
# If this is changed to "yes", RUN_IPUP must be set to "no."
RUN_DAEMON="yes"

# Set to "yes" if inadyn should be run every time a new ppp connection is
# established. This might be useful , if you are using dial-on-demand.
RUN_IPUP="no"

# The user and group that inadyn should be run as. 
USER="debian-inadyn"
GROUP="debian-group"
```

And my contents for /etc/inadyn.conf are:

```
# /etc/indayn.conf

# Output  messages to this file
logfile /var/log/inadyn/inadyn.log

# Or use the system syslog mechanism for log messages
# syslog

# the log debug level, which is an integer between 0 to 5
verbose 1

# How often the IP is checked. The value denotes seconds
period 300

# Set interface to bind to
#bind eth3

# Set the interface to check for IP
# iface eth1

# Full path to external command, or script, to run after a successful DDNS update 
# exec /usr/local/bin/script.sh

# Please edit following options before starting daemon
#Service provider
# Please see inadyn (8) for a complete list of providers
system freedns.afraid.org

# Your username
username tavishgilmour

# Your password
password 

# Your hostname. This option can appear multiple times
hostname tavish.gentile.cc

```

**Comment by troglobit** [comment]
I'm sorry, but such old versions of Inadyn are not supported by this (upstream) project anymore.  The latest release from us is v2.5.  I suggest you report your problem to Debian instead.

**Comment by kiplingw** [comment]
@tavishg, I found a newer downstream package in a PPA that was built for armhf. It's built for bionic, not Debian, but give it a try:

$ wget https://launchpad.net/~t.c/+archive/ubuntu/inadyn/+files/inadyn_2.3.1-2-bionic1_armhf.deb
$ sudo dpkg -i inadyn_2.3.1-2-bionic1_armhf.deb

**Comment by tavishg** [comment]
@kiplingw, Thanks.  

Upon further assistance and research:

$ wget http://launchpadlibrarian.net/384727047/libconfuse-common_3.2.2+dfsg-1_all.deb

And

$ wget https://launchpad.net/ubuntu/+source/confuse/3.2.2+dfsg-1/+build/15291596/+files/libconfuse2_3.2.2+dfsg-1_armhf.deb

were required as well. Now syntax 2.x is confirmed working on my pi.

**Comment by Johennes** [comment]
I think the original issue is you need `system default@freedns.afraid.org` not `system freedns.afraid.org`.
