### ISSUE TITLE
having more than 10 hostname under 1 provider causes inadyn to crash

### ISSUE THREAD

**Issue by fallenczar** [troglobit/inadyn#239]
As above, inadyn crashes on starting via systemd 
journalctl output -
Process 21063 (inadyn) of user 0 dumped core.
                                              
                                              Stack trace of thread 21063:
                                              #0  0x000055fd3a3c7d5b n/a (inadyn)
                                              #1  0x000055fd3a3c8056 n/a (inadyn)
                                              #2  0x000055fd3a3c6d29 n/a (inadyn)
                                              #3  0x000055fd3a3c5775 n/a (inadyn)
                                              #4  0x00007f3bd6bda223 __libc_start_main (libc.so.6)
                                              #5  0x000055fd3a3c5b7e n/a (inadyn)
-- Subject: Process 21063 (inadyn) dumped core
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: man:core(5)
-- 
-- Process 21063 (inadyn) crashed and dumped core.

temporary workaround: create a second provider with remaining hostname.

system: ARCH/4.19.27-1-lts

**Comment by troglobit** [comment]
Thanks for the report.  This bug was introduced when inadyn shifted to libConfuse based .conf files and is caused by missing boundary check.  The fix to this is quite simple, but more importantly; how many aliases is a good enough MAX (before we refactor to support any amount)?

**Comment by troglobit** [comment]
I've fixed the bug and doubled the amount of supported hostname aliases, for now.

**Comment by fallenczar** [comment]
Thanks for fixing it.
will having additional aliases  supported (>20) put any extra load on the system or cause any additional instability with the software, if not then why not support more (say 50). With increasing concerns about privacy, more and more people are turning towards hosting there own content hence the need for additional support.

**Comment by troglobit** [comment]
I see no problem with that, only extra RAM is reserved.  We should refactor the old underlying implementation from statically allocated arrays to, e.g. linked lists or sth, but in the meantime 50 it is!
