### ISSUE TITLE
[dnsexit.com] errors in service log, but working fine anyway!

### ISSUE THREAD

**Issue by ionreflex** [troglobit/inadyn#240]
version : 2.5

tested on 2 systems :

1. Linux v01d 4.20.5-1-ARCH #1 PREEMPT Fri Feb 1 01:50:09 UTC 2019 armv7l GNU/Linux
   * Archlinux-current on BeagleBoneBlack
   * inadyn-fork compiled from AUR
1. Linux lesath 4.18.0-15-generic #16-Ubuntu SMP Thu Feb 7 10:56:39 UTC 2019 x86_64 GNU/Linux
   * Ubuntu18.10-current, libvirt VM
   * inadyn compiled from GitHub

provider : dnsexit.com

I have the following appearing in the service log :

> Mar 10 14:17:24 v01d inadyn[12578]: Failed connecting to ip.dnsexit.com: No route to host
> Mar 10 14:17:24 v01d inadyn[12578]: Failed to get IP address for default@dnsexit.com, giving up!

... but the IP is getting updated, so I'm not sure why I see this!

-|-

**Comment by troglobit** [comment]
Temporary DNS lookups are common. Since the your DNS entry has been updated I assume inadyn managed to connect later.
