### ISSUE TITLE
realloc of cache_dir leaks memory

### ISSUE THREAD

**Issue by nihilus** [troglobit/inadyn#245]
Cppcheck found this in main.c and it is correct as ont should have a temporary pointer when doing reallocation and if it fails free the original memory (which would otherwise leak).

**Comment by troglobit** [comment]
You can safely ignore that warning.  If `compose_paths()` fails to allocate memory it will cause Inadyn to terminate.  Sure, on a no-MMU system like uClinux this would leak memory.

I run Inadyn in Coverity Scan and I periodically also run it through valgrind, and neither of them have reported any problems with memory leaks in a a while.
