### ISSUE TITLE
PID file /var/run/inadyn.pid already exists, inadyn already running? should try to send 'kill -0' to figure out.

### ISSUE THREAD

**Issue by nihilus** [troglobit/inadyn#247]
PID file /var/run/inadyn.pid already exists, inadyn already running? should try to send 'kill -0' to figure out if the PID is running or not. Especially if you have it running as an auto-restarted service this can be a problem if it segmentation faults due to hw or memory accesses.

**Comment by nihilus** [comment]
In fact my run-script is designed to kill the process in the pidfile before restarting the inadyn daemon, so i killed it explicitly and found out this annoying behavior of not being able to restart correctly.

**Comment by nihilus** [comment]
And yes, I've seen a wrongly mapped DMA controller trashing processes in-production.

**Comment by troglobit** [comment]
This seems to annoy you a lot more than other users. My obvious question is; how did you kill it? Inadyn cleans up its PID file if it receives SIGTERM. Sure, it could do all sorts of things to detect if the PID really is running, but how many other UNIX daemons do that, really? A kill -0 sure checks if there's someone at home, but is it really inadyn or some other process with the same PID? 

And surely, if there's badly mapped DMA, I'm sure you don't expect all applications in your system to take that into consideration. Isn't it better to fix the DMA mapping? 

If you care this much about this issue, create a pull request with a fix you consider appropriate and we can discuss it. For me personally, and the company I work for, this has never been a real world problem.

**Comment by nihilus** [comment]
Well it would have been better to fix the DMA-mapping and it was fixed. But since I didn't have the documentation for the SoC I was pretty much unable to figure out why processes started to die spontaneously.

I killed it with a SIGKILL and accidentally with a SIGSEGV.

I could create a pull request; or I could let the run-script remove the pidfile. :) I guess the latter is to prefer.

Now I am stuck at figuring out why a custom user-agent doesn't work with no-ip and TLS whereas it works using curl.

**Comment by nihilus** [comment]
And yes we do run everything supervised by "runit" and it has helped recovering from 3rd party daemons segfaulting. I really recommend that practice.

**Comment by nihilus** [comment]
And yes, we do run everything supervised from the inittab with 'runit' (set as 'respawn') since we don't want the OOM-killer to interfer and we don't want an OOM to restart the system.

**Comment by troglobit** [comment]
I hope 576ea71 was what you meant.
