### ISSUE TITLE
Always run exec-handler, even if no update is required

### ISSUE THREAD

**Issue by nihilus** [troglobit/inadyn#248]
Would make it easier to fwd thing to logger for the script/executable.

**Comment by troglobit** [comment]
Useful, but would require a bump in major version since it breaks the interface with the scripts.

**Comment by troglobit** [comment]
The proposal by @themiron in #305 is a great way to design around the problem of API breakage:

Add a `--exec-mode=[compat|event]`:

   * when set to `event` the script foo, in `--exec foo`, would be called with `$1` set to one of: `update`, `nochg`, `error`, possibly more.  Similar to how BusyBox `udhcpc.script` works.
   * when not set, or set to `compat`, the script foo would be called as-is today.

**Comment by thomas-ha** [comment]
Hi,
I needed inadyn to always run the exec handler. Therefore, I implemented it as suggested in the post above. I opened the pull request https://github.com/troglobit/inadyn/pull/310 for it.
