### ISSUE TITLE
Yandex DNS support (patch from fork)

### ISSUE THREAD

**Issue by taem** [troglobit/inadyn#250]
Hi,

Is it possible to incorporate this [change](https://github.com/dmitrodem/inadyn/commit/f3cee1c2f8b0a39cae3f8bc8c12d48ec788fbc45)?
It adds Yandex DNS support.

Thanks.

**Comment by troglobit** [comment]
Hi Timur! :)

Sure, if someone takes the time to fix the coding style, check the license of the JSON parser (why not use an library like libjansson??), test the result against Inadyn master, and do a pull request.   

Personally I have no time to do that at the moment, but I can audit pull-requests.

**Comment by taem** [comment]
Hi Joachim! :)

> Sure, if someone takes the time to fix the coding style, check the license of the JSON parser (why not use an library like libjansson??),

Not sure. Latest version of jsnm is a header-only library. Are there any recommendations for adding new build-time dependencies?

> test the result against Inadyn master, and do a pull request.
> 
> Personally I have no time to do that at the moment, but I can audit pull-requests.

Ok, need to try to prepare the patch myself.

**Comment by troglobit** [comment]
Not really, other than I'd like to keep link-time dependencies to a minimum, but I'd like to discuss it of course :)

If there's a header-only version, with a proper license header, that's OK with me.

Thank you!

**Comment by troglobit** [comment]
Merged in #251.
