### ISSUE TITLE
Provide a setup function for plugins

### ISSUE THREAD

**Issue by SimonPilkington** [troglobit/inadyn#254]
As the author of the Cloudflare plugin, the amount of setup I do in my request function is gross; it includes sending two other requests and parsing JSON responses for data.

A setup function to do this in would give better separation of concerns, as well as better error reporting in more complex plugins. For example, right now I can get rate limited in either of the two requests mentioned above, but I have to fail with a generic error instead of `RC_DDNS_RESP_RETRY_LATER` because the response function is expected to return the length of the response.

Simple plugins can just have a nullptr setup and have it not called.

**Comment by troglobit** [comment]
Yeah, I've noticed the increased complexity in some of the newer plugins. I cleaned up the first generation Inadyn many years ago, but another refactor is really needed. What you propose is a really good idea. If you (or anyone else) are interested in helping out it would greatly speed up the process.

**Comment by SimonPilkington** [comment]
I can provide the new infrastructure sometime, sure, but I'd only convert my own plugin to it because I am unable to test the others.

**Comment by troglobit** [comment]
That's fine, I can help out with the ones I can test.  Rome wasn't built in a day :)

**Comment by SimonPilkington** [comment]
It did collapse because it was too complex to manage, however, so we'd better do something, hadn't we? I'll open a PR when I have something.

**Comment by SimonPilkington** [comment]
Did what I could in #257. Other candidates for using this are cloudxns.c, dnspod.c, freedns.c, generic.c, and yandex.c.

**Comment by troglobit** [comment]
Cool, I can look at converting the above plugins when I circle back to Inadyn (in a couple of weeks time), unless someone else beats me to it.

**Comment by troglobit** [comment]
@SimonPilkington While refactoring FreeDNS to use your excellent new setup() callback, I noticed a global variable in the Cloudflare plugin.  I've refactored it a bit in #296, and I'd really appreciate your eye on it before I merge to master.

**Comment by troglobit** [comment]
Converted cloudxns.c, dnspod.c, freedns.c, and yandex.c as of f9901fc.
