### ISSUE TITLE
[Google Domains] Document how to use plugin

### ISSUE THREAD

**Issue by RMerl** [troglobit/inadyn#256]
I cannot test this myself as I don't have a Google Domain, but one of my users is reporting that his stopped working.  Could it be an API change from Google, and that 200 nohost result is mistakenly reported as an error?  I remember fixing something similar with another DDNS provider last year.  His log output:

```
Jun 27 12:12:30 rc_service: watchdog 816:notify_rc start_ddns
Jun 27 12:12:30 custom_script: Running /jffs/scripts/service-event (args: start ddns)
Jun 27 12:12:30 start_ddns: update DOMAINS.GOOGLE.COM default@domains.google.com, wan_unit 0
Jun 27 12:12:30 inadyn[21310]: In-a-dyn version 2.5 -- Dynamic DNS update client.
Jun 27 12:12:30 inadyn[21310]: Update forced for alias <my name>, new IP# <my IP>
Jun 27 12:12:30 inadyn[21310]: Fatal error in DDNS server response:
Jun 27 12:12:30 inadyn[21310]: [200 OK] nohost
```

**Comment by RMerl** [comment]
End-user finally spoke with Google about the issue.  They told him to use "@.mydomainname.com" as his hostname, which resolved his issue.  So, that might have been an API change from Google, but the fault wasn't really in inadyn, but the end-user having to update his parameters.

Leaving this open in case you want to investigate any further into this, but at first glance, I assume that inadyn interpreting "nohost" as an error despite the 200 OK result was the correct course of action.  Feel free to close this issue if you agree.

**Comment by troglobit** [comment]
There is just about no documentation in Inadyn for how to use the Google Domains plugin, and since it works with the correct .conf input I guess that's the real issue we should focus on here.

Do you think you, or your end user, could help out here?  At the very least we need an example config for either the README or inadyn.oonf (5) man page.

**Comment by RMerl** [comment]
Apparently, Google is currently experiencing issues, and this change was just a temporary one they recommended to the user.

I asked the user anyway to provide his config content, for reference.

Here is where we're discussing the issue:

https://www.snbforums.com/threads/ddns-problem-suddenly.57305/

**Comment by RMerl** [comment]
The configuration is pretty straightforward, I believe this user's issue is that he wants to update the root entry of his domain, hence the need to use @.mydomain.com.  Here is the config file entry that he`s currently using (I removed the lines that are specific to my firmware):

```
provider default@domains.google.com {
hostname = @.mydomain.com
username = "username"
password = "password"
}
```
From my understanding, if he wanted to use myhome.mydomain.com, then hostname would become that FQDN itself (myhome.mydomain.com).

**Comment by troglobit** [comment]
Awesome, thanks!  I'll add it to the examples in the man page and README when I circle back to Inadyn (in a couple of weeks time :)

**Comment by RMerl** [comment]
No problem.

Slightly off-topic, but do you currently have a timetable for 2.6?  Just want to see how I can fit it with my own development timetable, as I intend to upgrade my own product to 2.6 once it comes out (due to the new DDNS providers recently added to Inadyn).

**Comment by troglobit** [comment]
Nope, no timetable.  As things are I cannot make any such promises.  Hopefully later this summer, during the second phase of my vacation.

**Comment by RMerl** [comment]
No problem.  I might pick up a git snapshot then if I want to go ahead with Cloudflare support ahead of the 2.6 release.  If I do, I'll make sure to pass along any user feedback.

**Comment by troglobit** [comment]
Ah, Cloudflare. Yeah I just merged yet another pull request for that, so there may very well be more changes to that before the final release.  Just a heads up.

**Comment by SimonPilkington** [comment]
Using Cloudflare from @RMerl's firmware is actually what I was hoping for. I don't anticipate any more significant changes to the plugin unless problems are discovered. If you want to make me aware of those please open an issue on my Inadyn fork, although I will check here too from time to time too.

**Comment by troglobit** [comment]
Alright, cool, good to know! I've set up an initial milestone plan for the next release. Hopefully I'll get to it during my next vacation period, at the latest.
