### ISSUE TITLE
Need to handle EAGAIN as error from recv().

### ISSUE THREAD

**Issue by nihilus** [troglobit/inadyn#260]
Need to handle EAGAIN as error from recv(). It just means try again and not stop recving data.

**Comment by nihilus** [comment]
bytes = recv(tcp->socket, buf + total_bytes, chunk_size, 0);
if(bytes == -1 && errno == EAGAIN){ 
continue;
}

**Comment by troglobit** [comment]
Good catch!  Did you run in to it yourself?  Really thought we had `SA_RESTART` set in `.sa_flags`, but you're right!  Same goes for all syscalls basically, so `send()` too and a handful of others. 

Care to whip up a pull request?

**Comment by nihilus** [comment]
Yes, it fixed my issue with a check-in server that must have had some issues.

Yepp, send() should take care of it as well.

**Comment by nihilus** [comment]
I noticed that openssl.c must handle those from SSL_read()/SSL_write() as well. The gnutls.c however looks alright.

**Comment by troglobit** [comment]
Yes, same goes for basically all syscalls, that's why I mentioned `SA_RESTART` previously. 

Care to whip up a pull request?

**Comment by nihilus** [comment]
I am currently testing some fixes.

**Comment by nihilus** [comment]
I found a bug in the PR, since SSL_read is called twice it might fail on 2nd attempt and we should be fine with that (no more data to read).  This bug should also be found in gnutls.c

**Comment by troglobit** [comment]
I think fixes to this was part of PR #271, not the v1 in #269, so I'm closing this issue.  Thank you again for the report and fixes! <3
