### ISSUE TITLE
Debian Buster package forgets to set the permissions for the /var/run/inadyn directory properly

### ISSUE THREAD

**Issue by ThomasKorimort** [troglobit/inadyn#261]
Hi!
I installed inadyn for updating my DNS provider dnsexit with my dynamic IP. It works nicely. When i tried to set it up as systemd daemon, the debian buster package forgot to set permissions properly on the /var/run/inadyn directory. It creates user debian-inadyn:debian-inadyn, but does not set permissions properly for /var/run/inadyn. After changing the ownership of /var/run/inadyn to debian-inadyn:debian-inadyn the service started and got active.

The following /etc/systemd/system/inadyn.service worked nicely at the end:
[Unit]
Description=Internet Dynamic DNS Client
Documentation=man:inadyn
Documentation=man:inadyn.conf
Documentation=https://github.com/troglobit/inadyn
After=network-online.target
Requires=network-online.target

[Service]
Type=simple
User=debian-inadyn
Group=debian-inadyn
ExecStart=/usr/bin/inadyn -s -F /etc/inadyn.conf
restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target

Also i set according to the file /usr/share/doc/inadyn/NEWS.Debian.gz a setting to on in /etc/default/inadyn file.

The Debian Buster package installs the following files (dpkg -L inadyn):
/.
/var
/var/log
/var/log/inadyn
/usr
/usr/bin
/usr/bin/inadyn
/usr/share
/usr/share/doc
/usr/share/doc/inadyn
/usr/share/doc/inadyn/README.md
/usr/share/doc/inadyn/copyright
/usr/share/doc/inadyn/changelog.Debian.gz
/usr/share/doc/inadyn/NEWS.Debian.gz
/usr/share/doc/inadyn/changelog.gz
/usr/share/man
/usr/share/man/man8
/usr/share/man/man8/inadyn.8.gz
/usr/share/man/man5
/usr/share/man/man5/inadyn.conf.5.gz
/usr/sbin
/etc
/etc/inadyn.conf
/etc/default
/etc/default/inadyn
/etc/init.d
/etc/init.d/inadyn
/etc/logrotate.d
/etc/logrotate.d/inadyn
/etc/ppp
/etc/ppp/ip-up.d
/etc/ppp/ip-up.d/inadyn
/usr/sbin/inadyn

**Comment by troglobit** [comment]
Hi Thomas!  This is the upstream Inadyn project and we are (currently) not responsible for the Debian packaging.  So you must unfortunately report all problems to them.

**Comment by troglobit** [comment]
No response, closing issue since not a bug in upstream (packaging).

**Comment by acolomb** [comment]
Note that this was to be expected following @troglobit's [comment](https://github.com/troglobit/inadyn/issues/199#issuecomment-462420842) about the new Debian packaging integration. Unfortunately there was no more progress and no comments on the issue since February.

**Comment by troglobit** [comment]
@acolomb Ah, that's right! I had almost forgotten about #199
