### ISSUE TITLE
Updating Namecheap DDNS incorrectly reports error

### ISSUE THREAD

**Issue by chrisspen** [troglobit/inadyn#265]
I'm attempting to use Inadyn 1.99.4 on Ubuntu to update a Namecheap host using:

    sudo inadyn -S custom@http_srv_basic_auth -N dynamicdns.park-your-domain.com -U "/update?domain=mydomain.com&password=mypass&host=" -u myuser -p mypass -a "myhost" --test

and inadyn is reporting the "failure":

    Mon Sep 23 19:50:58 2019: Fatal error in DDNS server response:
    Mon Sep 23 19:50:58 2019: [200 OK] <?xml version="1.0"?><interface-response><Command>SETDNSHOST</Command><Language>eng</Language><IP>123.45.67.890</IP><ErrCount>0</ErrCount><ResponseCount>0</ResponseCount><Done>true</Done><debug><![CDATA[]]></debug></interface-response>
    Mon Sep 23 19:50:58 2019: DDNS server response:
    Mon Sep 23 19:50:58 2019: HTTP/1.1 200 OK
    Cache-Control: private
    Content-Type: text/html
    Set-Cookie: ASPSESSIONIDCSSTSDBR=MGHEOFBALCFECFAPAEBIAGKJ; path=/
    Date: Mon, 23 Sep 2019 23:50:57 GMT
    Connection: close
    Content-Length: 236

    <?xml version="1.0"?><interface-response><Command>SETDNSHOST</Command><Language>eng</Language><IP>123.45.67.890</IP><ErrCount>0</ErrCount><ResponseCount>0</ResponseCount><Done>true</Done><debug><![CDATA[]]></debug></interface-response>
    Mon Sep 23 19:50:58 2019: Error response from DDNS server, exiting!
    Mon Sep 23 19:50:58 2019: Failed starting daemon: RC_DYNDNS_RSP_NOTOK

Why does Inadyn think the request failed when Namecheap is responding with "200 OK"?

**Comment by troglobit** [comment]
Hi, glad you took the time to report this problem!  However, v1.99.4 is more than six years old and not supported by the upstream Inadyn project (this) anymore.  Unless the bug you are reporting apples to the [latest official release, v2.5](https://github.com/troglobit/inadyn/releases/tag/v2.5), then you should file this bug with Debian.
