### ISSUE TITLE
Guessing DDNS plugin 'default@spdyn.de' from 'spdyn'

### ISSUE THREAD

**Issue by 1Luc1** [troglobit/inadyn#270]
Hello,

after configuring inadyn with spdyn client i'll get the following warning if i ran ` inadyn --check-config`

`Guessing DDNS plugin 'default@spdyn.de' from 'spdyn'`

What does it mean? I can't realy tell if the update was successful or not. Is the creation of the cache file a success?

Running the deamon shows the following text:

```
Oct 29 12:14:51 alarm systemd[1]: Started Internet Dynamic DNS Client.
Oct 29 12:14:51 alarm inadyn[1925]: In-a-dyn version 2.5 -- Dynamic DNS update client.
Oct 29 12:14:51 alarm inadyn[1925]: Guessing DDNS plugin 'default@spdyn.de' from 'spdyn'
Oct 29 12:14:51 alarm inadyn[1925]: Update forced for alias <host>.spdns.eu, new IP# <ip>
Oct 29 12:14:52 alarm inadyn[1925]: Updating cache for <host>.spdns.eu

```
My configuration file looks like this:
```
provider spdyn {
        username        = <username>.spdns.eu
        password        = <password>
        hostname        = <host>.spdns.eu
}
```
Did i miss something with the configuration?

Thanks for some info.
Luc

EDIT: replaced actual credentials with <...>

**Comment by nihilus** [comment]
```
provider default@spdyn.de:1 {
        username        = <username>.spdns.eu
        password        = <password>
        hostname        = <host>.spdns.eu
}
```

**Comment by 1Luc1** [comment]
> ```
> provider default@spdyn.de:1 {
>         username        = <username>.spdns.eu
>         password        = <password>
>         hostname        = <host>.spdns.eu
> }
> ```

`default@spdyn.de:1` did the trick!
Thanks!
