### ISSUE TITLE
Option to update once without force

### ISSUE THREAD

**Issue by jorhett** [troglobit/inadyn#276]
I'm finding more and more embedded linux units using inadyn (yay!) which call it from cron with `--once`. Unfortunately this option does two things:

- runs once and quits when done (desired)
- forces an update (even if it's not needed)

I think we should make a new flag `--force` and separate these two features. I realize this will be a change in behavior, but it will reduce significant amounts of redundant updates on these builds which don't need to force an update, but want to run the update and exit when done.

**Comment by troglobit** [comment]
Good idea, I agree.
