### ISSUE TITLE
Issue 'Update fail for dynv6 #235' seems to be back again in latest.

### ISSUE THREAD

**Issue by dprus** [troglobit/inadyn#277]
This issue seems to be back again. I'm seeing the exact same issue now with the latest 2.6-dev:

> inadyn    | inadyn[1]: In-a-dyn version 2.6-dev -- Dynamic DNS update client.                                                                                                                  
inadyn    | inadyn[1]: Update forced for alias router.home.my.domain, new IP# x.x.x.x
inadyn    | inadyn[1]: Update forced for alias server.home.my.domain, new IP# x.x.x.x
inadyn    | inadyn[1]: Update forced for alias login.home.my.domain, new IP# x.x.x.x
inadyn    | inadyn[1]: Fatal error in DDNS server response:                                                                                                                                    
inadyn    | inadyn[1]: [200 OK] addresses unchanged                                                                                                                                            
inadyn    | inadyn[1]: Error response from DDNS server, exiting!                                                                                                                               
inadyn    | inadyn[1]: Error code 48: DDNS server response not OK

_Originally posted by @dprus in https://github.com/troglobit/inadyn/issues/235#issuecomment-562973079_

**Comment by troglobit** [comment]
Are you by any chance using the ipv4.dynv6.com service instead of the default dynv6.com?  The ipv4 has a different plugin that, I just noticed, doesn't check for `unchanged`.

**Comment by dprus** [comment]
I'm not explicitly using it but it looks like it's falling back to it - maybe because it can't access the ipv6 server? (which is strange since ipv6 is configured correctly from what I can tell).

**Comment by troglobit** [comment]
OK, that explains it.  I'll apply the same patch to the ipv4 plugin, and close this issue.   The IPv6 problem we'll have to address in a separate issue methinks
