### ISSUE TITLE
how to install on debian?

### ISSUE THREAD

**Issue by scorpiorooster** [troglobit/inadyn#281]
Where is the .deb package mentioned in README.debian for installing this?

**Comment by troglobit** [comment]
Every project on GitHub has a 'releaes' link at the very top of the first page; https://github.com/troglobit/inadyn/releases

**Comment by troglobit** [comment]
Debian/Ubuntu packages have moved. Use the following to install and get automatic updates:

```sh
curl -sS https://deb.troglobit.com/pubkey.gpg | sudo apt-key add -
echo "deb [arch=amd64] https://deb.troglobit.com/debian stable main" | sudo tee /etc/apt/sources.list.d/troglobit.list
sudo apt-get update && sudo apt-get install inadyn
```
