### ISSUE TITLE
Failed resolving hostname freedns.afraid.org: Temporary failure in name resolution

### ISSUE THREAD

**Issue by fx6666** [troglobit/inadyn#282]
Hi, thanks for this great project!

I build the latest (2.5) source from github on armhf and always get the above mentioned error on startup. This is the output of systemctl status:

● inadyn.service - Internet Dynamic DNS Client
   Loaded: loaded (/lib/systemd/system/inadyn.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-01-06 07:51:27 CET; 22min ago
     Docs: man:inadyn
           man:inadyn.conf
           https://github.com/troglobit/inadyn
 Main PID: 579 (inadyn)
    Tasks: 1 (limit: 4035)
   Memory: 6.2M
   CGroup: /system.slice/inadyn.service
           └─579 /usr/sbin/inadyn -n -s -t 5

Jan 06 07:51:27 raspberrypi systemd[1]: Started Internet Dynamic DNS Client.
Jan 06 07:51:27 raspberrypi inadyn[579]: In-a-dyn version 2.5 -- Dynamic DNS update client.
Jan 06 07:51:28 raspberrypi inadyn[579]: Guessing DDNS plugin 'default@freedns.afraid.org' from 'freedns'
Jan 06 07:51:28 raspberrypi inadyn[579]: Startup delay: 5 sec ...
Jan 06 07:51:33 raspberrypi inadyn[579]: Failed resolving hostname freedns.afraid.org: Temporary failure in name resolution
Jan 06 07:51:33 raspberrypi inadyn[579]: Failed to get IP address for default@freedns.afraid.org, giving up!

I added the startup delay because otherwise the clock wouldn't be set fast enough at startup but still no dice. The DNS updates seem to work though.

Is this a bug or am I missing something here?

**Comment by troglobit** [comment]
Hi there!

This could definitely be a bug, but lets see. Could you post your .conf file (*without your credentials of course*) and perhaps run inadyn manually from the command line with debug enabled?  Like this:

    ./src/inadyn -f freedns.conf -1 -l debug -n

(-1 is for oneshot mode, and -n is to prevent backgrounding)

**Comment by fx6666** [comment]
Ok, sure - here goes...

inadyn.conf
`
# In-A-Dyn v2.0 configuration file format
period          = 300
user-agent      = Mozilla/5.0

# The FreeDNS username must be in lower case
# The password (max 16 chars) is case sensitive
provider freedns {
    username    = xxx
    password    = xxx
    hostname    = wagner.oroki.de
}`

Output of  inadyn -1 -l debug -n:
`inadyn[1046]: In-a-dyn version 2.5 -- Dynamic DNS update client.
inadyn[1046]: Guessing DDNS plugin 'default@freedns.afraid.org' from 'freedns'
inadyn[1046]: Base64 encoded string: Zng2NjpoZW5zY2hhZg==
inadyn[1046]: Get address for default@freedns.afraid.org
inadyn[1046]: Checking for IP# change, initiating HTTPS ...
inadyn[1046]: Checking for IP# change, connecting to freedns.afraid.org([50.23.197.94]:443)
inadyn[1046]: Certificate OK
inadyn[1046]: SSL server cert subject: OU=Domain Control Validated,OU=EssentialSSL,CN=freedns.afraid.org
inadyn[1046]: SSL server cert issuer: C=GB,ST=Greater Manchester,L=Salford,O=COMODO CA Limited,CN=COMODO RSA Domain Validation Secure Server CA
inadyn[1046]: Querying DDNS checkip server for my public IP#: GET /dynamic/check.php HTTP/1.0
Host: freedns.afraid.org
User-Agent: Mozilla/5.0

inadyn[1046]: Successfully sent HTTPS request!
inadyn[1046]: Successfully received HTTPS response (400 bytes)!
inadyn[1046]: Server response: HTTP/1.1 200 OK
Server: nginx
Date: Mon, 06 Jan 2020 09:34:35 GMT
Content-Type: text/plain; charset=utf-8
Connection: close
Vary: Accept-Encoding
Cache-Control: no-store, no-cache, must-revalidate
Cache-Control: post-check=0, pre-check=0
Pragma: no-cache
Expires: Mon, 26 Jul 1997 05:00:00 GMT

Detected IP : 84.167.8.60
HTTP_CLIENT_IP :
HTTP_X_FORWARDED_FOR :
REMOTE_ADDR : 84.167.8.60
inadyn[1046]: Checked my IP, return code 0: OK
inadyn[1046]: IP server response:
inadyn[1046]: HTTP/1.1 200 OK
Server: nginx
Date: Mon, 06 Jan 2020 09:34:35 GMT
Content-Type: text/plain; charset=utf-8
Connection: close
Vary: Accept-Encoding
Cache-Control: no-store, no-cache, must-revalidate
Cache-Control: post-check=0, pre-check=0
Pragma: no-cache
Expires: Mon, 26 Jul 1997 05:00:00 GMT

Detected IP : 84.167.8.60
HTTP_CLIENT_IP :
HTTP_X_FORWARDED_FOR :
REMOTE_ADDR : 84.167.8.60
inadyn[1046]: Checking IPv4 address 84.167.8.60 ...
inadyn[1046]: IPv4 address 84.167.8.60 is valid.
inadyn[1046]: Current IP# 84.167.8.60 at default@freedns.afraid.org
inadyn[1046]: Update forced for alias wagner.oroki.de, new IP# 84.167.8.60
inadyn[1046]: Sending IP# update to DDNS server, initiating HTTPS ...
inadyn[1046]: Sending IP# update to DDNS server, connecting to freedns.afraid.org([204.140.20.21]:443)
inadyn[1046]: Certificate OK
inadyn[1046]: SSL server cert subject: OU=Domain Control Validated,OU=EssentialSSL,CN=freedns.afraid.org
inadyn[1046]: SSL server cert issuer: C=GB,ST=Greater Manchester,L=Salford,O=COMODO CA Limited,CN=COMODO RSA Domain Validation Secure Server CA
inadyn[1046]: Fetching account API key, initiating HTTPS ...
inadyn[1046]: Fetching account API key, connecting to freedns.afraid.org([50.23.197.94]:443)
inadyn[1046]: Certificate OK
inadyn[1046]: SSL server cert subject: OU=Domain Control Validated,OU=EssentialSSL,CN=freedns.afraid.org
inadyn[1046]: SSL server cert issuer: C=GB,ST=Greater Manchester,L=Salford,O=COMODO CA Limited,CN=COMODO RSA Domain Validation Secure Server CA
inadyn[1046]: Successfully sent HTTPS request!
inadyn[1046]: Successfully received HTTPS response (517 bytes)!
inadyn[1046]: Received API key(s), rc=0:
wagner.n0p.at|79.192.76.88|https://freedns.afraid.org/dynamic/update.php?xxx
wagner.netlord.de|84.157.121.205|https://freedns.afraid.org/dynamic/update.php?xxx
wagner.oroki.de|84.167.8.60|https://freedns.afraid.org/dynamic/update.php?xxx
inadyn[1046]: Sending alias table update to DDNS server: GET /dynamic/update.php?xxx&address=84.167.8.60 HTTP/1.0
Host: freedns.afraid.org
User-Agent: Mozilla/5.0

inadyn[1046]: Successfully sent HTTPS request!
inadyn[1046]: Successfully received HTTPS response (365 bytes)!
inadyn[1046]: DDNS server response: HTTP/1.1 200 OK
Server: nginx
Date: Mon, 06 Jan 2020 09:34:36 GMT
Content-Type: text/plain; charset=utf-8
Connection: close
Vary: Accept-Encoding
Cache-Control: no-store, no-cache, must-revalidate
Cache-Control: post-check=0, pre-check=0
Pragma: no-cache
Expires: Mon, 26 Jul 1997 05:00:00 GMT
X-Cache: MISS

ERROR: Address 84.167.8.60 has not changed.
inadyn[1046]: Successful alias table update for wagner.oroki.de => new IP# 84.167.8.60
inadyn[1046]: Updating cache for wagner.oroki.de`

[config.log](https://github.com/troglobit/inadyn/files/4025581/config.log)

**Comment by troglobit** [comment]
Hey, everything seems to be working now, right?  At least this latest log suggest there were no problems resolving the IP address of freedns.afraid.org, like in your first log.

The reason for your *"The DNS updates seem to work though."* may be that your network is not properly up when the box starts, but after a while inadyn will retry and when it has connectivity again, send the IP address update to FreeDNS.

You mentioned clock problems, maybe the systemd unit file's `After=network-online.target` doesn't work properly. I dunno.  It could be any kind of environment specific problem with the network that affects Inadyn.  Maybe increase the startup delay more would help?

**Comment by fx6666** [comment]
I increased the delay to 60 secs and the error is gone. I'll tune that value after work but for now I just want to say thank you for the amazing  support.

I' ll add the tuned value here for others to find and close this issue after that. Thanks again!

**Comment by troglobit** [comment]
No problem, glad to help! :)

Your tuned value is likely very site dependent. Personally I'd look into adding some kind of network-connectivity check to systemd instead. Obviously `network-online` isn't sufficient to have access to your DNS or ISP.

**Comment by fx6666** [comment]
The solution was to add -t 15 to the line ExecStart in file inadyn.service:

`ExecStart=/usr/sbin/inadyn -n -s -t 15`

You can find this file with:

`sudo find / -name inadyn.service`

In my case (Raspi 4 with Raspbian Buster) it was in

/etc/systemd/system/multi-user.target.wants
