### ISSUE TITLE
Invalid DDNS provider cloudflare.com

### ISSUE THREAD

**Issue by userj** [troglobit/inadyn#295]
I'm using the snap version on Ubuntu Core 18

channels:
  stable:    –                        
  candidate: –                        
  beta:      –                        
  edge:      2.5 2020-01-14 (283) 2MB -
installed:   2.5            (283) 2MB 

It seems to be a recent release but when i run check-config:
"Invalid DDNS provider cloudflare.com"

Here is the config:
/var/snap/inadyn/283/inadyn.conf
```
# In-A-Dyn v2.0 configuration file format
period          = 300
user-agent      = Mozilla/5.0


provider cloudflare.com {
     username = username
     password = [key here]
     hostname = [hostname.com here]
}
```
There are actual values in password and host name.

Thanks for your help.

**Comment by troglobit** [comment]
The plugin for Cloudflare was added after the 2.5 release.

**Comment by userj** [comment]
Ok. Thanks for the update. Any idea when the 2.6 will release?

**Comment by troglobit** [comment]
Nope. Like most volunteer open source projects; when it's done ... I have a few other important projects to get out the door first.

**Comment by userj** [comment]
Ok. Good luck with the projects!

**Comment by troglobit** [comment]
The v2.6 release ships tomorrow afternoon, CET :)

**Comment by userj** [comment]
Great news. Thank you!
