### ISSUE TITLE
Home Assistant support (as in Add-on)

### ISSUE THREAD

**Issue by deku-m** [troglobit/inadyn#298]
I use this in a build that someone has made but currently no support for this anymore since 2.2.1.
https://github.com/nalipaz/hassio-addons/tree/master/inadyn

Can you build support for HASS (Home assistent). Many use your build for updating there environment to the outside with dyndns.

**Comment by troglobit** [comment]
Hi, it seems that project use the custom provider mechanism in inadyn. So it's possible for you to set it up already.

I don't use Home Assistant myself, so I cannot help you with any details around what do.

**Comment by deku-m** [comment]
Ticket can be closed.

This awesome man build a addon for it:
https://github.com/alexbelgium/hassio-addons/tree/master/inadyn
