### ISSUE TITLE
--force not working in 2.6

### ISSUE THREAD

**Issue by RMerl** [troglobit/inadyn#299]
I haven't fully investigated yet, but --force doesn't seem to work here.  All it does is return the usage summary when I try to invoke it like this:

```
inadyn -1 --force --loglevel=debug -n -f /etc/inadyn.conf
```

**Comment by RMerl** [comment]
There's no case for '4' (which corresponds to --force longopt).

I will provide a pull request in a bit that fixes it.

**Comment by RMerl** [comment]
PR submitted.

**Comment by troglobit** [comment]
My bad, new (late) feature introduced in 2.6.  Thank you for taking the time to report, and fix this :)

**Comment by RMerl** [comment]
No problem.  I was merging 2.6 into my router firmware project today, and found out during testing that it was broken.  Seemed simple enough to fix :)
