### ISSUE TITLE
Need conf file format for DuckDNS.org with Inadyn client v1.99.15

### ISSUE THREAD

**Issue by sekharnadiminti** [troglobit/inadyn#304]
Hi Troglobit,

Can you please help in finding the right configuration for DuckDNS with Inadyn client v1.99.15 ?

BTW, I see DuckDNS does not require password . But when I am having conf file without password,  client is not accepting.

Also I have a limitation to upgrade my client to higher versions than this.

Thanks
Sekhar

**Comment by sekharnadiminti** [comment]
Hi, 

Found the right configuration with little more experimentation  for duckdns

background 
verbose        1
cache-dir      /var/tmp 
startup-delay  20
period         300 
 
logfile /var/log/ddns.log
system default@duckdns.org
alias <your host name >
username <token given by duck dns>
password  <random string>

Note : Password filled with random string just to satisfy client.

This configuration worked upon taking below fix 

https://github.com/troglobit/inadyn/pull/109/files

Otherwise , you may see 301 Moved Permanently response 

Thanks
Sekhar

**Comment by troglobit** [comment]
Great to see you found a solution! :)

Closing ...
