### ISSUE TITLE
Made easy support for providers with flaky/unreliable checkip servers

### ISSUE THREAD

**Issue by troglobit** [troglobit/inadyn#306]
In #305 @themiron came up with the brilliant idea to simplify using another checkip server for providers with a flaky/unreliable service.

  1. Update documentation with helpful hints and recommendations
  2. Add syntax sugar a-la `checkip-server=default` to tell inadyn to use its built-in default (ipify) instead of the provider provided one
  3. Possibly also detect bad checkip servers and warn in syslog?

**Comment by RMerl** [comment]
For 3., maybe see if throttled ipcheck servers return something else than a 200 or a 30x HTTP code, and in which case act accordingly (fallback to default server perhaps?)

**Comment by troglobit** [comment]
@RMerl ah, great idea!  I was thinking about checking for timeout, but just tracking the HTTP return codes (maybe with a counter and threshold?) is quite a bit more obvious :)

**Comment by RMerl** [comment]
@themiron, did you get a particular HTTP response code when you were throttled in your test case?

**Comment by themiron** [comment]
For 2 - currently get_address_backend() uses cmd, iface and remote in order, seems easy to add last resort with default ip checker. after that, same default server can be removed from plugin for simplicity

**Comment by themiron** [comment]
> @themiron, did you get a particular HTTP response code when you were throttled in your test case?

ARAIR yes, something either 4xxx or 5xx, not really sure.

**Comment by RMerl** [comment]
So, code >=400 could be handled as a failure then.

**Comment by troglobit** [comment]
Agree to all above!  Thank you guys for the awesome feedback :)

**Comment by themiron** [comment]
> So, code >=400 could be handled as a failure then.

already is
