### ISSUE TITLE
Dynu.com DDNS support?

### ISSUE THREAD

**Issue by LewisW-J** [troglobit/inadyn#311]
Hi, I've tried a few things to get the provider to work but it doesn't seem to recognise Dynu.com which is on the list of supported DDNS. In the config file I see that it refers to it as default@dynu.com but when I put that in, it just says "Invalid DDNS provider default@dynu.com".

I've tried dynu.com and dynu. Am I missing something here? 

From the log for when I tried dynu as the provider:
inadyn[15]: In-a-dyn version 2.2.1 -- Dynamic DNS update client.
inadyn[15]: /usr/local/etc/inadyn.conf:6: Invalid DDNS provider dynu
inadyn[15]: Parse error in /usr/local/etc/inadyn.conf

**Comment by acolomb** [comment]
Support for Dynu was added in a more recent release, 2.6 if I remember correctly.
