### ISSUE TITLE
Cloudflare plugin does not handle third-level domain zones correctly

### ISSUE THREAD

**Issue by SimonPilkington** [troglobit/inadyn#312]
E.g. whatever.co.uk is currently not handled correctly (the plugin attempts to get the id for co.uk). I will produce a fix as soon as I have time.

**Comment by SimonPilkington** [comment]
Before I start, how do you think we should handle this @troglobit? I could write detection of zones that are likely to be third-level, but that seems finicky to me. I would prefer to just have the user specify their zone as the username, which is a field we currently don't use, although that would be a breaking change for existing configs. What do you think?

**Comment by troglobit** [comment]
I think it's a good idea.  The problem with `username` is slightly annoying, of course, but I don't see any other way forward.  The README, which presumably ppl have read/copy-pasted from, says `unused`, so maybe we could model any error message based on that, just as friendly reminder to the user?

**Comment by RichardVine** [comment]
@SimonPilkington Appreciate you weren't asking me but I'm going to give you my opinion  anyway...  :-)

Just to explain my use case, under my single Cloudflare account (with single email address), I have two zones. One of them is the same as my email address, the other isn't.

If the username field had to 'correctly' identify my Cloudflare account and was then used to determine which zone to update, I wouldn't be able to update one of my zones. In that regard, having a new 'zone' parameter would be preferable. However, as you've said, if the username field isn't actually used, re-purposing it to be the zone name would work anyway.

**Comment by SimonPilkington** [comment]
@RichardVine, your API token is what matters here, not your address. The token should have the edit permission for all zones, or else nothing works because Cloudflare's API is buggy. Assuming we switch to using username, if you have more than one zone, you can create an entry for each and use the same API token. @troglobit, please confirm this works, I'm not sure.

**Comment by troglobit** [comment]
Yup, that should work.  Inadyn doesn't care if it's the same, as long as you use the index/identifier `:NUM`.   I'm guessing something like this would be preferable in this case:
```
provider cloudflare:1 {
    username    = foo
    password    = token
   ...
}

provider cloudflare:2 {
    username    = bar
    password    = token
   ...
}
```

**Comment by SimonPilkington** [comment]
@RichardVine Could you build and check if Inadyn is usable for you now? If there are still problems, it would be better to fix them before they end up in Merlin.

**Comment by troglobit** [comment]
If there still are issues we can reopen this bug.

**Comment by RichardVine** [comment]
Thanks guys. I'm using inadyn as part of the firmware of an Asuswrt-merlin router and don't know enough about how to update this (particularly without bricking my router!). I'll see if I duplicate the issue from a Linux VM, then update to confirm the issue is resolved. I might be some time!

**Comment by SimonPilkington** [comment]
That's fine. Inadyn should behave the same on Merlin and amd64 or whatever you are using. There are also switches to make it run in the foreground for testing (see --help). If you would rather not bother building it let me know and I will post a binary for you.

**Comment by RichardVine** [comment]
Oh, using a binary (for amd64/x64) would be perfect. Many thanks.

**Comment by SimonPilkington** [comment]
Here's a binary built from this repository's master branch. You may need to install dependencies using your distro's package manager.

[inadyn.zip](https://github.com/troglobit/inadyn/files/4643467/inadyn.zip)

**Comment by RichardVine** [comment]
I ran this on an Opensuse VM after installing libconfuse. I can confirm a forced update worked perfectly for my .co.uk domains. Inadyn is clearly logging 'Zone: example.co.uk' correctly and using that in the Cloudflare queries and updates.

Nice job!

**Comment by SimonPilkington** [comment]
Great. Thanks for verifying.

**Comment by troglobit** [comment]
Great work guys, thank you for verifying, @RichardVine :)
