### ISSUE TITLE
twoDNS stopped working, new API v2

### ISSUE THREAD

**Issue by 1Luc1** [troglobit/inadyn#314]
Hello,

[twoDNS](http://www.twodns.de) have a new way to update the host ip. http://www.twodns.de/api
So the listet example within the [readme.md](https://github.com/troglobit/inadyn/blob/master/README.md) doesn't work anymore.

Does someone know how to set inadyn up to handle the new api v2?

Thanks,
Luc

**Comment by troglobit** [comment]
Hi Luc!  Previously the custom In-a-dyn provider could be used, it's a generic HTTP GET backend similar to what Dyn.com uses.  The new twoDNS API seems to require sending a JSON payload as well, so I don't think there's an easy way to fix.  Probably we need a dedicated C-plugin.

**Comment by 1Luc1** [comment]
Thanks for your reply. I thought about that too. For now i will abandon the use of twoDNS and use another dynDns service.

**Comment by troglobit** [comment]
Reopening just as a reminder to myself to update the docs
