### ISSUE TITLE
Docker: Multi-arch builds

### ISSUE THREAD

**Issue by owine** [troglobit/inadyn#315]
Hi

Would you consider adding multi-arch builds to your official Docker Hub image? I want to run on a Raspberry Pi but the image does not support arm. The apt repository version is very outdated (1.99) so running the latest in Docker would be preferred.

Thanks

**Comment by troglobit** [comment]
I have nothing set up myself, but if someone contributes sth I'd be happy
to merge it.

**Comment by troglobit** [comment]
Fixed by the relentless @ntkme :smiley:
