### ISSUE TITLE
Cloudflare wildcard record is not updated

### ISSUE THREAD

**Issue by AlphaJack** [troglobit/inadyn#316]
The `wildcard = true` option doesn't seem to work with Cloudflare:
```ini
provider default@cloudflare.com {
    username = user@mail.tld
    password = TOKENTOKENTOKEN
    hostname = domain.tld
    wildcard = true
}
```

My working `ddclient` configuration is:
```ini
protocol=cloudflare
use=web, web=icanhazip.com
ssl=yes
login=user@mail.tld
password=GLOBALGLOBALGLOBAL
zone=domain.tld
domain.tld,*.domain.tld
```

If I try to use `hostname = { domain.tld, *.domain.tld }` it updates the record for the first domain, but returns:
```
In-a-dyn version 2.7 -- Dynamic DNS update client.
Failed resolving hostname .domain.tld: Name or service not known
Update forced for alias .domain.tld, new IP# 150.50.50.50
HTTP 403: Provided API token does not have the required permissions.
Zone '.domain.tld' not found.
Error response from DDNS server, exiting!
Error code 50: Authentication failure
inadyn.service: Main process exited, code=exited, status=50/n/a
inadyn.service: Failed with result 'exit-code'.
```

**Comment by troglobit** [comment]
Maybe @SimonPilkington can provide some insight on this one?  He's the main developer behind this plugin :)

**Comment by SimonPilkington** [comment]
I'll check what's happening here as soon as I have time. I don't use wildcard domains myself so it's basically uncharted waters right now.

**Comment by troglobit** [comment]
Thanks @SimonPilkington, maybe @AlphaJack can help debug the issue further meanwhile?

**Comment by SimonPilkington** [comment]
This took a while, sorry about that.

Per my analysis, the `wildcard` option is unsuitable for use with Cloudflare. Unlike other providers supporting wildcard records (which simply that this be put in the query string) Cloudflare allows defining  wildcard records in a zone by using an asterisk in the name (e.g. `*.one.example.com` and `*.two.example.com`).

That said, I can update wildcard records on my domain using @AlphaJack's suggested method if I put the wildcard name in quotes. @AlphaJack please try that.

@troglobit Any particular reason the parser drops the asterisk if the quotes are left out?

**Comment by troglobit** [comment]
@SimonPilkington thank you for taking the time to look at this!  I greatly appreciate your help with the Cloudflare plugin <3

I'm not sure why it drops the asterisk.  I've just reproduced it myself, separate from In-a-dyn, using libConfuse.  I'll continue investigating.

**Comment by AlphaJack** [comment]
@SimonPilkington thank you, this configuration now works:

```ini
provider default@cloudflare.com {
    username = user@mail.tld
    password = TOKENTOKENTOKEN
    hostname = { domain.tld, "*.domain.tld" }
}
```

Logs says the following
```
In-a-dyn version 2.7 -- Dynamic DNS update client.
Failed resolving hostname *.domain.tld: Name or service not known
Update forced for alias *.domain.tld, new IP# 150.50.50.50
Updating cache for *.domain.tld
```
---

> Per my analysis, the wildcard option is unsuitable for use with Cloudflare

I would suggest adding this note to the CloudFlare documentation section, along with a multiple hostname array example

**Comment by troglobit** [comment]
@AlphaJack to prevent In-a-dyn from updating too often¹, it caches each update.  So unless there's a fixed record in the config for a given provider, I'm wondering how we should do the caching.  Maybe open up for disabling caching when there's only a wildcard hostname?

At the very least we should skip the initial DNS query for wildcard hostnames to prevent the above "error" message.

Anything still left we can document as a comment in the example configs :)
____
¹ this caching came about when Dyn started blocking accounts that updated "too often".  They didn't care to detail how often "too often" is, so we implemented this caching mech. for all providers.  When In-a-dyn starts up it does a DNS query for each hostname to check against what it has as a cached value, if the the cached value differs, or the modification time² of the cached value is too old, an update/ping is sent to the DDNS provider.
²  Yes, modification times are fragile, in particular on embedded systems that don't have a battery backed RTC.  We run into this often at $DAYJOB.

**Comment by troglobit** [comment]
@SimonPilkington, I found why the asterisk is dropped.  Turns out it's a limitation in libConfuse due to a fix to an earlier issue, martinh/libconfuse@3da6a559.  Not sure it's possible to fix easily, may be better to just improve Inadyn docs+examples with quotes around all strings ... or even drop libConfuse in favor of rolling our own.

**Comment by SimonPilkington** [comment]
Eschewing the entire config parser library over one, relatively specific use case seems excessive. If the parser can't be fixed easily then I think improving our documentation would suffice for now.

**Comment by SimonPilkington** [comment]
As for caching, I don't really have a great idea. If we had a resolvable name in the list along with a wildcard name, we could cache using that, but detecting this would not be trivial, nor would implementing caching in this way, I assume, and there is also no guarantee we will have it at all.

**Comment by AlphaJack** [comment]
Why don't use a dummy subdomain?
`drill a wilcardwildcard.domain.tld`
```
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 63427
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; wildcardwildcard.domain.tld.       IN      A

;; ANSWER SECTION:
wildcardwildcard.domain.tld.  300     IN      A       150.50.50.50

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 1 msec
;; SERVER: 127.0.0.1
;; WHEN: Mon Aug  3 16:23:57 2020
;; MSG SIZE  rcvd: 92

```

**Comment by SimonPilkington** [comment]
That isn't a bad idea, actually. As long as there isn't actually a separate A record with the same name as whatever we're testing, this would work. If we pick a sufficiently random string, the risk would probably be negligible.

**Comment by troglobit** [comment]
@SimonPilkington there are other open issues, like #317, and other issues over the years that have made me regret libConfuse for inadyn.  It's not a huge amount of work, but definitely not something I have time for right now.

Personally I think it might be best to disable caching for wildcards, and keep it at `*.foo.bar`, or probe the "basename", e.g. try a DNS lookup of `foo.bar` in this case.

**Comment by SimonPilkington** [comment]
I see. If it really is causing multiple problems then a different solution may be worth considering.

I cannot say what would be best myself since I do not use wildcard records so I have a poor idea of what may go wrong. Even with caching disabled I believe Cloudflare would handle too frequent updates gracefully (with a HTTP 429 response, which the plugin handles), so that is certainly an option as well.

**Comment by SimonPilkington** [comment]
The [limits](https://support.cloudflare.com/hc/en-us/articles/200171456-How-many-API-calls-can-I-make-) are quite generous as well.

**Comment by troglobit** [comment]
Yup, I'll see what I can come up with timewise .. but this has at least started a background process which will undoubtedly one day wake me up itching to be fixed :)

Over the years I've been thinking about the caching and how to improve responsiveness to IP address changes.  It is mostly there to protect against strict DDNS providers, as I mentioned. So if we can allow for automatic disabling of caching or provide safe default poll intervals per provider, I think that would be a great win.

Wow, 1200 req/5 min ... that's indeed generous, but I guess they are in the (D)DoS protection business ;)

**Comment by mohd-akram** [comment]
Is it possible to let the `wildcard` option generate the asterisk format automatically?

**Comment by troglobit** [comment]
Anything is possible, we just need someone to work on implementing and testing the feature for this particular DDNS provider.

**Comment by BrainSlayer** [comment]
@troglobit havent checked this but this patch here might work. 

`--- cloudflare.c        (revision 51306)
+++ cloudflare.c        (working copy)
@@ -34,7 +34,7 @@
        "Authorization: Bearer %s\r\n"  \
        "Content-Type: application/json\r\n\r\n";

-static const char *CLOUDFLARE_HOSTNAME_ID_REQUEST      = "GET " API_URL "/zones/%s/dns_records?type=%s&name=%s HTTP/1.0\r\n"   \
+static const char *CLOUDFLARE_HOSTNAME_ID_REQUEST      = "GET " API_URL "/zones/%s/dns_records?type=%s&name=%s%s HTTP/1.0\r\n" \
        "Host: " API_HOST "\r\n"                \
        "User-Agent: %s\r\n"                    \
        "Accept: */*\r\n"                               \
@@ -59,7 +59,7 @@
        "Content-Length: %zd\r\n\r\n" \
        "%s";

-static const char *CLOUDFLARE_UPDATE_JSON_FORMAT = "{\"type\":\"%s\",\"name\":\"%s\",\"content\":\"%s\",\"ttl\":%li,\"proxied\":%s}";
+static const char *CLOUDFLARE_UPDATE_JSON_FORMAT = "{\"type\":\"%s\",\"name\":\"%s%s\",\"content\":\"%s\",\"ttl\":%li,\"proxied\":%s}";

 static const char *IPV4_RECORD_TYPE = "A";
 static const char *IPV6_RECORD_TYPE = "AAAA";
@@ -328,6 +328,7 @@
                       CLOUDFLARE_HOSTNAME_ID_REQUEST,
                       data->zone_id,
                       record_type,
+                      info->wildcard ? "*." : "",
                       hostname->name,
                       info->user_agent,
                       info->creds.password);
@@ -361,6 +362,7 @@
        content_len = snprintf(json_data, sizeof(json_data),
                               CLOUDFLARE_UPDATE_JSON_FORMAT,
                               record_type,
+                              info->wildcard ? "*." : "",
                               hostname->name,
                               hostname->address,
                               info->ttl >= 0 ? info-> ttl : 1, // Time to live for DNS record. Value of 1 is 'automatic'
`

**Comment by troglobit** [comment]
@BrainSlayer thank you for the PR! <3

I hope someone with a cloudflare login can verify that it works as expected when checking the wildcard setting.
