### ISSUE TITLE
How to compile statically

### ISSUE THREAD

**Issue by irontigran** [troglobit/inadyn#320]
Do you have any advice on compiling statically? I've tried commands like `./configure PKG_CONFIG="pkg-config --static" LDFLAGS=-static` from within the provided Docker container with no luck - configure will fail.

The specific error is with the crypto library (and I've tried both gnutls and openssl), for example:

```bash
checking for GnuTLS... yes
checking for gnutls_init in -lgnutls... no
configure: error: *** SSL library (GnuTLS) not found!
```

**Comment by troglobit** [comment]
A static build with dynamic libraries, or anything else in between, is nothing I'd recommend. I've never tried it with inadyn myself, but it's a configure-based project, so I'd suggest looking around for support around the GNU web/man pages for autoconf/pkg-config etc.

**Comment by irontigran** [comment]
For the benefit of later readers, I did manage to get it to compile inside the Docker container with: 

```bash
apk add openssl-dev
./configure --enable-openssl LDFLAGS="-static -no-pie" && make
```

Only works when linking against musl and openssl, though.
