### ISSUE TITLE
Certificate Verification Failed

### ISSUE THREAD

**Issue by matrixcowboy** [troglobit/inadyn#321]
When updating/upgrading Ubuntu 20.04.1 LTS Focal error occurs during update. 

Err:13 https://deb.troglobit.com/debian stable Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 138.68.65.229 443]
E: The repository 'https://deb.troglobit.com/debian stable Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Seems like the certificate expired. Please update when you have an opportunity.

**Comment by troglobit** [comment]
Thanks for the heads-up, seems the HTTP-01 update with certbot failed for some reason.  I'll see what I can do.

**Comment by troglobit** [comment]
Should be fixed now. Thanks again for taking the time to report this!
