### ISSUE TITLE
Cloudflare Proxy support

### ISSUE THREAD

**Issue by Schueni1** [troglobit/inadyn#323]
I would like to use the cloudflare proxy feature. The problem is, that after every IP update the the proxy feature gets disabled and reverts back to 'DNS only'.

This is my current config:
```
provider cloudflare.com {
     username = me@example.com
     password = myAccessToken
     hostname = subdomain.mydomain.com
}
```

**Comment by troglobit** [comment]
I don't know what the "cloudflare proxy" feature is.  Inadyn only sends HTTP GET (sometimes POST) requests to tell DDNS Providers, like Cloudflare, the current IP of a certain account.

**Comment by Schueni1** [comment]
Enabling Cloudflare Proxy is possible with their api.
It's just a boolean.

**Comment by troglobit** [comment]
Aha, will I don't use Cloudflare myself. Maybe you can submit a pull request?

**Comment by Schueni1** [comment]
Not sure wether I'm skilled enough :sweat_smile:

**Comment by Salvora** [comment]
Cloudflare API says:

```
curl -X PUT "https://api.cloudflare.com/client/v4/zones/023e105f4ecef8ad9ca31a8372d0c353/dns_records/372e67954025e0ba6aaa6d586b9e0b59" \
     -H "X-Auth-Email: user@example.com" \
     -H "X-Auth-Key: c2547eb745079dac9320b638f5e225cf483cc5cfdda41" \
     -H "Content-Type: application/json" \
     --data '{"type":"A","name":"example.com","content":"127.0.0.1","ttl":120,"proxied":false}'
```
I think the only thing that needs to be done is to change proxied to true.
