### ISSUE TITLE
Google Cloud DNS support? (ACME)

### ISSUE THREAD

**Issue by rayfoss** [troglobit/inadyn#324]
Because of let's encrypt I switched to Cloud DNS, ... can this be made to work with it?
https://cloud.google.com/dns

The API https://cloud.google.com/dns/docs/reference/v1

**Comment by troglobit** [comment]
Not as-is, we only have support for google domains rn.  To manage the cloud dns, inadyn needs a dedicated plugin.  From a quick glance at the docs it certainly looks possible.

**Comment by rayfoss** [comment]
ACME is a little bit overkill right now. I'm sure some docker exists to that can translate between dyndns2 and ACME. I think a graphical flutter/electron layer or easier apple daemon/dockerized systemd creation are better upgrades.

**Comment by rayfoss** [comment]
For reference some one already made a dynamic dns client in python https://github.com/conorcunningham/google-ddns/blob/master/gcp_ddns.py

**Comment by troglobit** [comment]
Cool, thanks for following-up! :)
