### ISSUE TITLE
v2.8 Release

### ISSUE THREAD

**Issue by ntkme** [troglobit/inadyn#337]
@troglobit Thank you for quickly respond to issues and pull requests.

Any chance we can tag a new release soon?

Changes since v2.7: https://github.com/troglobit/inadyn/compare/v2.7...master

**Comment by troglobit** [comment]
I'd like to finish the outstanding issues planned for the [v2.8](https://github.com/troglobit/inadyn/milestone/6) milestone first.  Not very difficult, minor fix and doc update. I need to do some regression testing as well, but that goes with every release so.

**Comment by ntkme** [comment]
Did not see there is a milestone already there. Closing. Thanks!

**Comment by troglobit** [comment]
There, released! :) https://github.com/troglobit/inadyn/releases/tag/v2.8

Thank you again for your invaluable contributions <3
