### ISSUE TITLE
no cache - Update forced spam

### ISSUE THREAD

**Issue by erichegit** [troglobit/inadyn#338]
In the documentation it is written, that the default cache is located at "/var/cache"
But when I look inside the container (bin/ssh) this folder is empty

In the Log I can see that my IP-Address is updated without a need because it didn`t change

**inadyn[1]: Update forced for alias ...**

When trying to add --cache-dir in the entrypoint - I can not start the container - doesn`t matter which path I choose,...

**Comment by erichegit** [comment]
I looked into the container and there is nothing logging my current IP-Address in the cache folder!

Also your readme is not consistant in this point

> We also define a custom cache directory, default is to use /var/cache. In our case /mnt is a system specific persistent store for caching your IP address as reported to each provider. Inadyn use this to ensure you are not locked out of your account for excessive updates, which may happen if your device Internet gateway running inadyn gets stuck in a reboot loop, or similar.

**Comment by troglobit** [comment]
Honestly, I've never used the docker container personally. It was contributed by other users.  The project README, and the UNIX manual pages, document how to use the program when it runs as a regular application.  

To get a persistent store from your host available in your container use `docker run -v /path/to/host/dir:/var/cache`.  That's what I do when I run other containers.  Without it your container is fully isolated from your host ...

**Comment by erichegit** [comment]
Of course I can let docker also run this way

`docker run --rm -v "$PWD/volume/inadyn.conf":"/etc/inadyn.conf" -v "$PWD/volume/cache":"/var/cache" troglobit/inadyn:latest`

But 2 Problems

1. after Update the container isn`t exiting
2. doesn`t matter what I am doint - the cache with my IP-Address is not written

> inadyn[1]: In-a-dyn version 2.8-rc1 -- Dynamic DNS update client.
> inadyn[1]: Guessing DDNS plugin 'default@freedns.afraid.org' from 'freedns'
> inadyn[1]: Update forced for alias xxx, new IP# 62.x.y.z

Because of the effect, that my IP-Address is not saved, Inadyn ALWAYS forces it to update.
This might cause to account deactivations because of "flood".

So please take a look into your cache directory - if you find a file with your IP-Address.

**Comment by troglobit** [comment]
OK, I just tested this and I have no problems.

Maybe you're not familiar with inadyn and its options. I recommend reading the manual page.   Here's one way, my HTML generated page: <https://man.troglobit.com/man8/inadyn.8.html> there is a link at the bottom to `inadyn.conf(5)` as well.

Also, when running in a docker container run with less privileges than usual. So you must make sure to create the cache directory first. In your case:

    mkdir -m 0777 $PWD/volume/cache/inadyn

Notice the subdirectory name here.

The default args in the container is `--foreground`, so to just run once and exit, append `-1` to your command line.

To debug things, use `-l debug` and use `docker run -ti ...`

**Comment by troglobit** [comment]
Any comment, or can we close this?

**Comment by erichegit** [comment]
Thanks for your help - I closed it
