### ISSUE TITLE
Socks5 proxy support of inadyn.

### ISSUE THREAD

**Issue by hongyi-zhao** [troglobit/inadyn#339]
Does inadyn support the host's IP address updating behind a socks5 proxy?

Regards,
HY

**Comment by troglobit** [comment]
In simple terms, In-a-dyn works like this; when starting up in sends a GET request to a public "checkip" server, e.g., http://checkip.dyndns.com/, the text returned contains the IP address the rest of the world sees you with.  This IP address (the text string) is then sent to your preferred DDNS provider using another GET request along with your account details.  This is then what  determines what your DNS name is then associated with.

I hope that answers your question.

For future reference, there is a Discussion tab in GitHub these days for questions like this.  The Issues tab is more for actual problems/bugs or feature requests.

**Comment by hongyi-zhao** [comment]
Thanks a lot, got it. If so, the GET request through a socks5 proxy will return the IP address of the socks5 proxy, so this is not applicable for this scenario.

**Comment by troglobit** [comment]
Ah, almost forgot! You can optionally, instead of asking an external server, send the IP address of an interface or call an external script.  

More info here: <https://man.troglobit.com/man5/inadyn.conf.5.html>

**Comment by hongyi-zhao** [comment]
Wonderful, thanks a lot for your elaborate design.
