### ISSUE TITLE
Option parsing errors since v2.8

### ISSUE THREAD

**Issue by acolomb** [troglobit/inadyn#340]
I updated to the just-release v2.8.0 version from the provided DEB file. Now no IP update works anymore, giving such error messages during config parsing:

    Jan 31 16:44:33 offspring systemd[1]: Started Internet Dynamic DNS Client.
    Jan 31 16:44:33 offspring inadyn[572959]: In-a-dyn version 2.8 -- Dynamic DNS update client.
    Jan 31 16:44:33 offspring inadyn[572959]: /etc/inadyn.conf:15: no such option 'ttl'
    Jan 31 16:44:33 offspring inadyn[572959]: /etc/inadyn.conf:15: no such option 'proxied'
    Jan 31 16:44:33 offspring inadyn[572959]: /etc/inadyn.conf:37: no such option 'ttl'
    Jan 31 16:44:33 offspring inadyn[572959]: /etc/inadyn.conf:37: no such option 'proxied'
    Jan 31 16:44:33 offspring inadyn[572959]: /etc/inadyn.conf:71: no such option 'ttl'
    Jan 31 16:44:33 offspring inadyn[572959]: /etc/inadyn.conf:71: no such option 'proxied'
    Jan 31 16:44:33 offspring inadyn[572959]: /etc/inadyn.conf:105: no such option 'ttl'
    Jan 31 16:44:33 offspring inadyn[572959]: /etc/inadyn.conf:105: no such option 'proxied'

The mentioned lines always contain the closing brace of a custom provider section.

UPDATE: The process does not terminate because of these errors, but they are supposedly just warnings.

**Comment by troglobit** [comment]
This fix is now part of the v2.8.1 release.
