### ISSUE TITLE
How inadyn as a service supposed to work? 

### ISSUE THREAD

**Issue by Makishima** [troglobit/inadyn#343]
Hello!
My setup is `Ubuntu 20.04.2 LTS` and `inadyn 2.8.1`

Inadyn is running as service looks normal `sudo service inadyn status`
```
● inadyn.service - Internet Dynamic DNS Client
     Loaded: loaded (/lib/systemd/system/inadyn.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2021-02-10 21:01:49 CET; 11h ago
       Docs: man:inadyn
             man:inadyn.conf
             https://github.com/troglobit/inadyn
   Main PID: 1999751 (inadyn)
      Tasks: 1 (limit: 2254)
     Memory: 5.4M
     CGroup: /system.slice/inadyn.service
             └─1999751 /usr/sbin/inadyn -n -s

Feb 10 21:01:49 vps.hetzner.de systemd[1]: Started Internet Dynamic DNS Client.
```

My conf is 
```
# Do not edit this file directly unless you select 'Advanced' during
# your next invocation of dpkg-reconfigure inadyn
#
#
# For details on the syntax of this file, see inadyn.conf(5)
period = 300

#custom twoDNS {
#    ssl            = false
#    username       = XXXX
#    password       = XXXX
    #checkip-server = checkip.two-dns.de
#    checkip-server = api.ipify.org
#    checkip-path   = /
#    ddns-server    = update.twodns.de
#    ddns-path      = "/update?hostname="
#    hostname       = XXXX
#}

provider default@dynu.com {
        username        = XXXX
        password        = XXXX
        hostname        = XXXX
}

provider default@freedns.afraid.org {
    username    = XXXX
    password    = XXXX
    hostname    = { XXXX, XXXX }
}

#provider default@freedns.afraid.org {
#     username    = XXXX
#     password    = XXXX
#     hostname    = XXXX
#}
```
`sudo inadyn  --check-config` is ok

If I run `sudo inadyn --force -n` it will be update dynu and freedns domains.

**Comment by Makishima** [comment]
`sudo tail -n 100 /var/log/syslog`
show up that inadyn is not running every 5 minutes as I expected it would be as `period` settings

**Comment by troglobit** [comment]
Are you sure, have you run with `-l debug` on command line?

**Comment by Makishima** [comment]
`sudo inadyn -1 -n -l debug` does not update IP as well 
I figure out that there is an old value (A) in `/var/cache/inadyn/*.cache`
But `dig <domain>` shows a new value (B) that I want to change to (A)

**Comment by troglobit** [comment]
Hmm, odd. Nothing I've seen in my (personal) setups or at $DAYJOB.  I'll have to spend some time to investigate/replicate to give a proper answer.

**Comment by Makishima** [comment]
So it looks like `inadyn` do not update its cache or check an actual IP of the domain upon running without --force

**Comment by troglobit** [comment]
That should not be necssary, so unless there's something else at play here to mess things up, then it's a regression I do not know about.

**Comment by Makishima** [comment]
To be more clear what I'm doing

1. Get some domains at freeDNS and dynu.com
2. Setup them some initial IPs
3. Prepared `inadyn` conf and run it as `sudo inadyn -1 -n -l debug`. This run changed IP from initial to actual on both providers
4. Revert IP to initials and leave them
5. Check and restart `inadyn` to ensure how its work as a service in the evening
6. In the mornings figure out that IPs is still initial but not actual
7. Start this topic

**Comment by troglobit** [comment]
I just tested this with my own setup and could not find anything wrong with this. I even tested setting `fake-address = true` and sending SIGUSR1 (as mentioned in the manual), and it clearly both 1) checks every 300 sec, and 2) updates the IP address.

When you say "setup some initial IPs", what do you mean by that?  In-a-dyn by default only checks if your public IP address has changed.  So if you have a NAT firewall behind you and the DDNS provider, a local IP address change is ignored.

**Comment by Makishima** [comment]
> When you say "setup some initial IPs", what do you mean by that?

I have the VPS IP that I want to be assigned via inadyn, it's a dedicated address not behind the NAT.
By "initial IP" I mean that I set my home IP (it's dedicated too) to DDNS hostname so I can check that inadyn will change it to VPS  IP

**Comment by troglobit** [comment]
OK.  Just checking.

**Comment by troglobit** [comment]
Does inadyn have write permissions to the cache directory?  The default cache directory is /var/cache/inadyn, but since #309 we no longer try to create/chmod this directory, so i must be created and writable by the UID that inadyn runs as before it starts.

**Comment by Makishima** [comment]
Yes, it is writeable because inadyn creates *.cache files
`drwxr-xr-x  2 debian-inadyn debian-inadyn 4096 Feb 11 09:18 inadyn`
```
-rw-r--r-- 1 root root 12 Feb 11 09:18 xxxx.dynu.net.cache
-rw-r--r-- 1 root root 12 Feb 11 09:18 xxxx.roothome.de.cache
-rw-r--r-- 1 root root 12 Feb 11 09:18 xxxx.routemehome.com.cache
```

**Comment by troglobit** [comment]
Hmm, weird.  OK, I'll have to dig deeper, but unfortunately not now because of $DAYJOB. Will have a look at it again later tonight (CET).

**Comment by Makishima** [comment]
Also, send SIGHUP to inadyn via htop, maybe reloading conf will help.

**Comment by Makishima** [comment]
Should `inadyn service` write anything in `/var/log/syslog` if he performs checks?
Last entry is `Feb 11 11:58:35 vps inadyn[2011906]: In-a-dyn version 2.8.1 -- Dynamic DNS update client.` when I restart service

**Comment by troglobit** [comment]
Not by default, then it only logs updates.  But you can change the command line argument to `-l info` to get address probe logging as well.

**Comment by troglobit** [comment]
Sorry, I can't reproduce your problem.  This is what I see on my end when I change the IP address of my interface:

```
$ systemctl status inadyn
● inadyn.service - Internet Dynamic DNS Client
     Loaded: loaded (/lib/systemd/system/inadyn.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2021-02-11 19:39:27 CET; 10min ago
       Docs: man:inadyn
             man:inadyn.conf
             https://github.com/troglobit/inadyn
   Main PID: 186029 (inadyn)
      Tasks: 1 (limit: 18778)
     Memory: 4.2M
     CGroup: /system.slice/inadyn.service
             └─186029 /usr/sbin/inadyn -n -s

Feb 11 19:39:27 luthien systemd[1]: Started Internet Dynamic DNS Client.
Feb 11 19:39:27 luthien inadyn[186029]: In-a-dyn version 2.8.1 -- Dynamic DNS update client.
Feb 11 19:39:27 luthien inadyn[186029]: Update needed for alias troglobit.homenet.org, new IP# 192.168.1.195
Feb 11 19:39:30 luthien inadyn[186029]: Updating cache for troglobit.homenet.org
Feb 11 19:49:31 luthien inadyn[186029]: Update needed for alias troglobit.homenet.org, new IP# 192.168.1.42
Feb 11 19:49:32 luthien inadyn[186029]: Updating cache for troglobit.homenet.org
```

**Comment by Makishima** [comment]
Thanks.
There is almost the same lines as I run `inadyn -1 -n `manually
```
Feb 11 19:50:49 vps inadyn[2017762]: Cached IP# XXXX for XXXX.routemehome.com from previous invocation.
Feb 11 19:50:49 vps inadyn[2017762]: Last update of XXXX.routemehome.com on Thu Feb 11 09:18:15 2021
Feb 11 19:50:49 vps inadyn[2017762]: Cached IP# XXXX for XXXX.roothome.de from previous invocation.
Feb 11 19:50:49 vps inadyn[2017762]: Last update of XXXX.roothome.de on Thu Feb 11 09:18:16 2021
Feb 11 19:50:49 vps inadyn[2017762]: Cached IP# XXXX for XXXX.dynu.net from previous invocation.
Feb 11 19:50:49 vps inadyn[2017762]: Last update of XXXX.dynu.net on Thu Feb 11 09:18:17 2021
Feb 11 19:50:49 vps inadyn[2017762]: Checking for IP# change, initiating HTTPS ...
Feb 11 19:50:49 vps inadyn[2017762]: Checking for IP# change, connecting to freedns.afraid.org([69.42.215.252]:443)
Feb 11 19:50:49 vps inadyn[2017762]: SSL server cert subject: CN=freedns.afraid.org
Feb 11 19:50:49 vps inadyn[2017762]: SSL server cert issuer: C=GB,ST=Greater Manchester,L=Salford,O=Sectigo Limited,CN=Sectigo RSA Domain Validation Secure Server CA
Feb 11 19:50:49 vps inadyn[2017762]: No IP# change detected for default@freedns.afraid.org, still at XXXX
Feb 11 19:50:49 vps inadyn[2017762]: Checking for IP# change, initiating HTTPS ...
Feb 11 19:50:49 vps inadyn[2017762]: Checking for IP# change, connecting to checkip.dynu.com([104.207.143.23]:443)
Feb 11 19:50:50 vps inadyn[2017762]: SSL server cert subject: OU=Domain Control Validated,OU=PositiveSSL Wildcard,CN=*.dynu.com
Feb 11 19:50:50 vps inadyn[2017762]: SSL server cert issuer: C=GB,ST=Greater Manchester,L=Salford,O=Sectigo Limited,CN=Sectigo RSA Domain Validation Secure Server CA
Feb 11 19:50:50 vps inadyn[2017762]: No IP# change detected for default@dynu.com, still at XXXX
```

I think there is something wrong with the cache but I can't figure it out.
`Cached IP# XXXX for XXXX.routemehome.com from previous invocation.`

**Comment by Makishima** [comment]
> Sorry, I can't reproduce your problem. This is what I see on my end when I change the IP address of my interface

Thank you for helping, I will try to resolve this issue with `--purge` reinstall

**Comment by Makishima** [comment]
Nope, reinstall didn't help, IP is updated only for a first run while inadyn invoke force update

`This is what I see on my end when I change the IP address of my interface:`
If possible could you please check my case?

1. Set IP "A" in freeDNS web interface
2. Reload inadyn service or/and purge cache file so inadyn will update IP
3. After inadyn updated IP, change it back via freeDNS web interface to IP "A"
4. Wait for `period` settings and see what happens

**Comment by troglobit** [comment]
Um, I don't have to test that to tell you what happens.  It's nothing.  

This is mentioned in the documentation already, but Inadyn doesn't query DNS or ask the DDNS provider what the IP is. It only checks with an external service what IP the rest of the Internet sees it coming from.  If that IP address differs from the last one it recorded in its cache, or if the cache file is missing, then a HTTP GET (yes get, not post/put) is sent to the DDNS provider to update the record.

**Comment by Makishima** [comment]
I'm sorry for wasting your time.
It is was a bit unclear for me about this nuance from docs.
Is it configurable to query DNS value?

**Comment by troglobit** [comment]
Please see the documentation for how to use a script to do the work you need.
