### ISSUE TITLE
Docker Hub should have tags corresponding to git tags

### ISSUE THREAD

**Issue by ericlathrop** [troglobit/inadyn#344]
Would it be possible to setup the GitHub Actions to push a Docker tag corresponding to any git tags that are pushed? I don't want to run `latest`, which is equivalent to `master`.

**Comment by troglobit** [comment]
I'll have a look at it for the next release cycle.

**Comment by troglobit** [comment]
Should be fixed in 330dfa63, so 2.9.0 (due today) should be tagged also on docker hub (and ghcr). Please let me know otherwise.
