### ISSUE TITLE
Support for dynu.com DNS

### ISSUE THREAD

**Issue by steveharman** [troglobit/inadyn#348]
Hi,

These guys offer a "free forever" DYN DNS service across a globally distributed network of nameservers and have been for some years.  It would be nice to see "native" support for them.

https://www.dynu.com/en-US/DynamicDNS

Thanks

**Comment by troglobit** [comment]
Already supported in the dyndns.so plugin; along with 9 others:

 https://github.com/troglobit/inadyn/blob/master/plugins/dyndns.c#L220 

Unless they've changed their API and we're now suddenly incompatible, I propose closing this.

**Comment by steveharman** [comment]
Ah right, yes - please close.  Is it worth highlighting the support for Dynu et.al, to stop other idiots like me creating a ticket?  ;-)

**Comment by troglobit** [comment]
I dunno what else I can do, it's listed on the front-page of the project, in the README @ https://github.com/troglobit/inadyn#supported-providers
