### ISSUE TITLE
Can't find Windows x86 in release versions

### ISSUE THREAD

**Issue by f1ames0ff** [troglobit/inadyn#349]
Can't find Windows x86 in release versions. Could someone elaborate where I can download the latest build?

**Comment by troglobit** [comment]
Best laugh I've had in a long time, thank you! 😂

**Comment by troglobit** [comment]
No builds available, Windows not supported.

**Comment by f1ames0ff** [comment]
> No builds available, Windows not supported.

Why not?

**Comment by troglobit** [comment]
With software its rarely a technical issue.   It's simply because I'm the single (unpaid) maintainer of this project and have no personal interest in supporting that platform.  There are plenty of other DDNS client alternatives for Windows anyway.

**Comment by f1ames0ff** [comment]
@troglobit Thanks. I already found another one.
