### ISSUE TITLE
Cannot find DDNS provider ip4@nsupdate.info, check your spelling.

### ISSUE THREAD

**Issue by ioogithub** [troglobit/inadyn#350]
I can't figure out what I am doing wrong:

`inadyn -S ipv4@nsupdate.info -a server.nsupdate.info -p xxxxx -u server.nsupdate.info --L /var/log/inadyn/inadyn.log -t`

I always get:

```
Wed Mar 24 18:54:35 2021: Cannot find DDNS provider ipv4@nsupdate.info, check your spelling.
Wed Mar 24 18:54:35 2021: Error parsing option -S
Wed Mar 24 18:54:35 2021: Failed starting daemon: RC_CMD_PARSER_INVALID_OPTION_ARGUMENT

```
I have also tried to edit the config file and start the sysdemd server using the recommended config on the nsupdate.info site:

```
# /etc/inadyn.conf

logfile /var/log/inadyn/inadyn.log
verbose 5
period 300

system ipv4@nsupdate.info
    ssl
    username user.nsupdate.info
    password xxx
    alias server.nsupdate.info

# note: no IPv6 support in inadyn yet.
```

When I do a:

`inadyn --check-config`

I get:

```
Wed Mar 24 19:02:46 2021: Invalid option name at position 2: --check-config
Wed Mar 24 19:02:46 2021: Failed starting daemon: RC_CMD_PARSER_INVALID_OPTION
```

According to these sites, it should all work:

https://github.com/troglobit/inadyn/blob/master/README.md
https://www.nsupdate.info/generate_secret/xxxx/?#inadyn

What am I doing wrong?

```
pi@raspberrypi:/var/log/inadyn $ apt list inadyn
Listing... Done
inadyn/stable,now 1.99.4-1 armhf [installed]

```

**Comment by troglobit** [comment]
Your report is for a software version I released in 2013.  I have made 17 releases, including a major redesign of the software. I'm not able to support such old releases.   Also, since this is distributed to you from Debian, or the Raspberry Pi foundation as a Debian derivative, your bug report, questions, and support is handled by them.

Sorry, but I'm closing this report.

**Comment by ioogithub** [comment]
So basically you are saying that your software can't be used on a Raspberry Pi?

I will look for another solution, thanks.

**Comment by acolomb** [comment]
> So basically you are saying that your software can't be used on a Raspberry Pi?

No, that is absolutely not true. Just that the version of this software that gets offered for installation on the Pi is based on an ancient version. For which only the respective distribution is to blame, although blaming doesn't help.

It can be built from source on the Pi, or maybe you can find a pre-built binary of the current version somewhere that works.

**Comment by troglobit** [comment]
Like André says. Modern versions of inadyn may very well work fine, that old version you unfortunately have probably doesn't. 

Your case is not uncommon. Many users show up here asking for support, but we cannot support such old versions. Not only is it ancient and no longer distributed by us, but we're also not payed by you or anyone else to support it.
