### ISSUE TITLE
Wildcard Option On Google Domains

### ISSUE THREAD

**Issue by Thecat8413** [troglobit/inadyn#351]
Currently using the following conf (I have removed Username, Password, and Domain Name details)

(I added a slash to commented parts to prevent weird GitHub formatting)
/# Inadyn v2.0 configuration file, automatically generated by debconf
/# Do not edit this file directly unless you select 'Advanced' during
/# your next invocation of dpkg-reconfigure inadyn
/#
/# 
/#
/# For details on the syntax of this file, see inadyn.conf(5)
period = 300

provider domains.google.com:1 {
        hostname = @.example.com
        username = ~
        password = ~
}

provider domains.google.com:2 {
        hostname = example.com
        wildcard = true
        username = ~
        password = ~
}

When run, it seems to run properly: 
inadyn[46092]: Guessing DDNS plugin 'default@domains.google.com' from 'domains.google.com:1'
inadyn[46092]: Guessing DDNS plugin 'default@domains.google.com' from 'domains.google.com:2'

But upon checking my Domain, the wildcard entry remains at 0.0.0.0, while the root entry resolves to the correct IP. 

I assume this is an error on my part.

**Comment by troglobit** [comment]
Hmm, to be perfectly honest, I don't know.  In #256 we discussed the lack of proper documentation here, and as a result the root example was added.   Maybe you don't need to set the wildcard flag?  Iirc that appends a flag to the URL used for the update to Google.  

There are variations between DDNS providers, but many use the exact same protocol as Dyn.com first published.  The Google plugin is just a variant of the Dyn plugin, with other default servers.  But how the servers themselves respond and interpret client requests is not always straight forward. Sometimes the providers publish their API.  

If you feel up to it, we'd really appreciate someone with an account looking into this and perhaps even help document.  (Documentation is by far the most important thing of Open Source projects).   At the very least we'd be happy with your discoveries in this thread.

**Comment by Thecat8413** [comment]
I have tried entering the host name as *.example.com (which is how the wildcard input is set up on the Google Domains DDNS entry) but that errored out. 

(I have stripped out identifying info, example.com and the ~.~.~.~ IP have the correct details in actual log)

inadyn.conf:
period = 300

provider domains.google.com:1 {
hostname = @.example.com
username = ~
password = ~
}

provider domains.google.com:2 {
hostname = *.example.com
username = ~
password = ~
}

output:
inadyn[46157]: In-a-dyn version 2.8.1 -- Dynamic DNS update client.
inadyn[46157]: Guessing DDNS plugin 'default@domains.google.com' from 'domains.google.com:1'
inadyn[46157]: Guessing DDNS plugin 'default@domains.google.com' from 'domains.google.com:2'
inadyn[46157]: Failed resolving hostname .example.com: Name or service not known
inadyn[46157]: Update forced for alias .example.com, new IP# ~.~.~.~
inadyn[46157]: Fatal error in DDNS server response:
inadyn[46157]: [200 OK] notfqdn
inadyn[46157]: Error response from DDNS server, exiting!
inadyn[46157]: Error code 48: DDNS server response not OK

From Google's API: 
notfqdn	Error	The supplied hostname is not a valid fully-qualified domain name.

My assumption is that inadyn is not passing the '*' char, at least from what is being returned in the output.

**Comment by troglobit** [comment]
Try with `"*.example.com"` and/or check the transaction with Wireshark/tcpdump/tshark/termshark.  Would be neat to see what goes on on the wire for this.  You can also run inadyn with `-l debug` to get some more info.

**Comment by Thecat8413** [comment]
Adding the quotes worked! Thank you very much!

**Comment by troglobit** [comment]
Cool, do you mind posting the last working config?  Sans your credentials of course.

**Comment by Thecat8413** [comment]
period = 300

/# Root Domain Entry
provider domains.google.com:1 {
        hostname = @.example.cc
        username = ~
        password = ~
}
/# Wildcard Subdomain Entry
provider domains.google.com:2 {
        hostname = "*.example.com"
        username = ~
        password = ~
}

**Comment by troglobit** [comment]
Awesome, thank you! <3

**Comment by Thecat8413** [comment]
@troglobit Regarding the update to documentation, I would put the google examples after the no-ip examples since the google example uses the multiple usernames sub index explained in the no-ip examples.

**Comment by troglobit** [comment]
Good point! I'll see if I get some time to do it later tonight ... unless you best me to it with a quick PR? ;-)
