### ISSUE TITLE
dnspod plugin's bug

### ISSUE THREAD

**Issue by jgh004** [troglobit/inadyn#352]
When the A record is updated without sub_domain, the A record of the root domain name will be updated
For example, I want to update ddns.xxx.com
Actually it updated xxx.com
Forgive my bad english

**Comment by troglobit** [comment]
That plugin was submitted by @ysc3839, maybe he or someone else can give some input here.

**Comment by ysc3839** [comment]
Sorry, I'm not using dnspod now, and I'm not interesting in fixing this issue.
Maybe I will have a look when I have time.

**Comment by troglobit** [comment]
No problem, thanks for checking back! <3

Anyone else using dnspod can help out by reproducing the problem, locating their API documentation, and suggesting a fix.

**Comment by imess** [comment]
Looks like the subdomain is missing from line 177 of plugins/dnspod.c, 

`login_token=%s%%2C%s&format=json&domain=%s&record_id=%d&record_line=%s&value=%s**&subdomain=%s**`

and line 179
`domain, record_id, "%E9%BB%98%E8%AE%A4", alias->address**, prefix**);`

try fixing it and compiling yourself

**Comment by troglobit** [comment]
Anyone had a chance to test this latest suggestion yet?  Since I don't have dnspod myself I cannot test, and would likely risk breaking the plugin even further if I do the change speculatively.  

A new release is coming soonish, so if someone can submit a pull request, or at least help out testing that would be much appreciated!

**Comment by troglobit** [comment]
OK, no response in this thread. I've added the suggested fix to the plugin in b6e7ea9.  It's a speculative change and completely untested, but will at least be part of v2.9.0

**Comment by imess** [comment]
Sorry for the delay. I have been using this fix for over two months, it
works flawlessly.

**Comment by troglobit** [comment]
@imess OK, thanks! Let's hope I got it right ...
