### ISSUE TITLE
Error parsing option --period

### ISSUE THREAD

**Issue by moguls753** [troglobit/inadyn#353]
Hey,

i got this parsing error, checked the man page and still didn´t get it.

`Jul 05 23:14:31 truenas.local systemd[1]: Starting LSB: DynDNS client...`
`Jul 05 23:14:31 truenas.local inadyn[449325]: Starting DynDNS client : inadyn`
`Jul 05 23:14:31 truenas.local inadyn[449329]: Mon Jul  5 23:14:31 2021: Error parsing option --period`
`Jul 05 23:14:31 truenas.local inadyn[449329]: Mon Jul  5 23:14:31 2021: Failed starting daemon: RC_DYNDNS_INVALID_OPTION`
`Jul 05 23:14:31 truenas.local inadyn[449330]:  failed!`
`Jul 05 23:14:31 truenas.local systemd[1]: Started LSB: DynDNS client.`

This is my inadyn.conf
`period = 300`
`provider default@dnsomatic.com {`
    `ssl = true`
    `checkip-ssl = true`
    `checkip-server = "checkip.org:443"`
    `checkip-path = "/"`
    `username = "user"`
    `password = 'password'`
    `hostname = { "all.dnsomatic.com" }`
`}`

Can someone help?

Regards,
Eike

**Comment by troglobit** [comment]
What version of inadyn are you running? Modern versions, supported here, don't have those error messages anymore.

If you are trying a config file from this project on an older version of inadyn, it won't work.

**Comment by moguls753** [comment]
Indeed, it's this version: inadyn (1.99.4-1) (TrueNas Scale)
Where can i look to find the correct syntax for configuration?

**Comment by troglobit** [comment]
Oh dear lord ... that's an old version! :-/

OK, maybe we can close this issue then?

**Comment by moguls753** [comment]
Yes we can, thx.
