### ISSUE TITLE
arm64 .deb?

### ISSUE THREAD

**Issue by chiphead2332** [troglobit/inadyn#357]
Any chance you could provide a pre-compiled arm64 version on the apt repo? I'm running 64-bit ubuntu on a raspberry pi and there are no binaries for my architecture. I'm building from source for now but the extra convenience would be appreciated.

**Comment by troglobit** [comment]
I don't have the time or resources to support other archs atm.  I'd propose pushing Ubuntu to in turn push Debian to update their package instead.  I've tried to help out (downstream), but the effort seems to have died out.

**Comment by chiphead2332** [comment]
Fair enough, thanks.
