### ISSUE TITLE
Issue with multiple hosts using custom Namecheap definition

### ISSUE THREAD

**Issue by tsanga13** [troglobit/inadyn#367]
I followed the template to create a custom Namecheap config per README.md:

```
custom namecheap {
    username    = YOURDOMAIN.TLD
    password    = mypass
    ddns-server = dynamicdns.park-your-domain.com
    ddns-path   = "/update?domain=%u&password=%p&host=%h"
    hostname    = { "host1", "host2", "host3" }
}
```

However, host2 and host3 fail to update. When I inspect the debug log for the three HTTP GET update requests, I find that https://dynamicdns.park-your-domain.com/update?.... is made for host1, host1host2, and host1host3. 

It appears that inadyn is concatenating the second and third requests. I'm using version 2.8.1, tested as bundled in Asus Merlin and also via Homebrew.

My current workaround is just to make multiple namecheap:index entries.

**Comment by troglobit** [comment]
Ouch, thanks for taking the time to report this!  A v2.9.1 is already planned, and this issue may help expedite it.

**Comment by tsanga13** [comment]
Thanks for the quick response!
