### ISSUE TITLE
Can't build with OpenSSL 1.1.1k

### ISSUE THREAD

**Issue by maxisam** [troglobit/inadyn#370]
Thanks for the great project. 

I tried to build it on Raspbian GNU/Linux 11 (bullseye) with enableOpenSSL and it failed with error message like no openssl

However, it actually has OpenSSL 1.1.1k installed. 

It built without the flag.

**Comment by troglobit** [comment]
You need the libssl-dev package, do you have that installed?

**Comment by troglobit** [comment]
Just verified the build on Debian unstable with libssl-dev v1.1.1m, works fine.  Closing since no reply from op
