### ISSUE TITLE
Inadyn does only update my IP the first time 

### ISSUE THREAD

**Issue by exaveal** [troglobit/inadyn#371]
I have the problem, that inadyn only updates the ip the first time, when I start inadyn. When the ip address changes (e.g. reconnect to the internet on my router), inadyn recognizes the new ip, but does not update the ip at my dyn-dns-provider (/or sends a request).

In the status of the inadyn service you see:

1. at 19:47:21 the system started and the ip was send to my dyn-dns-provider and was updated. so this is the prove everything regarding the request to my dyn-dns-provider is working correctly.
2. at 20:27:25 the new ip was recognized, also the cache-file is updated, but no request was send to my dyn-dns-provider.

```
wolf@wolf-desktop:~$ sudo systemctl status snap.inadyn.daemon.service
[sudo] Passwort für wolf: 
● snap.inadyn.daemon.service - Service for snap application inadyn.daemon
     Loaded: loaded (/etc/systemd/system/snap.inadyn.daemon.service; enabled; vendor preset: disabled)
     Active: active (running) since Wed 2021-12-29 19:47:21 CET; 1h 7min ago
   Main PID: 5463 (inadyn)
      Tasks: 1 (limit: 9402)
     Memory: 4.7M
        CPU: 184ms
     CGroup: /system.slice/snap.inadyn.daemon.service
             └─5463 /snap/inadyn/335/usr/sbin/inadyn -n -s -f /var/snap/inadyn/335/inadyn.conf --cache-dir=/var/snap/inadyn/335/cache -P /var/snap/inadyn/335/inadyn.pid

Dez 29 19:47:21 wolf-desktop systemd[1]: Started Service for snap application inadyn.daemon.
Dez 29 19:47:21 wolf-desktop inadyn[5463]: In-a-dyn version 2.7 -- Dynamic DNS update client.
Dez 29 19:47:21 wolf-desktop inadyn[5463]: Update forced for alias cloud.konzeptgeil.com, new IP# 91.40.16.191
Dez 29 19:47:21 wolf-desktop inadyn[5463]: Updating cache for cloud.konzeptgeil.com
Dez 29 20:27:25 wolf-desktop inadyn[5463]: Update needed for alias cloud.konzeptgeil.com, new IP# 62.226.207.203
Dez 29 20:27:26 wolf-desktop inadyn[5463]: Updating cache for cloud.konzeptgeil.com
```

I tried this configuration on Ubuntu Server and Manjaro installed via snap. Same result on both systems.

**Comment by troglobit** [comment]
Hi @exaveal, the v2.7 release is too old for us upstream to support.  I have a vague recollection of this being a regression that was fixed in a later release.

I suggest you either test the [latest release](https://github.com/troglobit/inadyn/releases/latest), or report this problem to the maintainers of the snap package, so they can test and update their package -- the maintenance of that package is not the responsibility of this project.

**Comment by exaveal** [comment]
Thanks for your feedback. I "tried" to request a update of the snap package on github. Unfortunately I am not that skilled to install the latest version on my Ubuntu Server. The version of inadyn in the ubuntu repository is version 1.92 and even older than the snap-package. To fix my problem I switched to ddclient unfortunately. But I hope inadyn gets updated for ubuntu/snap soon!
