### ISSUE TITLE
Proxied option for Cloudflare not working

### ISSUE THREAD

**Issue by jjpinom** [troglobit/inadyn#372]
I have the folowing config:

provider cloudflare.com {
        username = xxx@domain.com
        password = abcdefg
        hostname = host.mydomain.com
        proxied = true *This line does not work
}

This is the syntax explained in the inadyn example, but the daemon responds:

/etc/config/inadyn:7: no such option 'proxied'

**Comment by troglobit** [comment]
Hi @jjpinom, what version of Inadyn are you using? This proxied option was introduced in v2.8

**Comment by jjpinom** [comment]
Hello. Thanks for answering me. 

The inadyn -v says: 2.7

So, I suppose that's the reason this option is not working.

I installed inadyn on a OpenWRT Router (OpenWrt 21.02.1 r16325-88151b8303).

The Inadyn Package version is: 2.7-1

I don't know who is in charge of OpenWRT package for Inadyn.

**Comment by troglobit** [comment]
Yup, that's why.  Unfortunately I don't know either.

Anyway, it's definitely no longer an issue with this (upstream) project.  I recommend you report your issue, or feature request to upgrade, to the downstream OpenWRT project.

Closing bug report.

**Comment by jjpinom** [comment]
Thanks!.

Now the OpenWRT package is updated.

I included the 'proxied' option, but had to change the 'username' option from email to zone

**Comment by troglobit** [comment]
Great!

Yeah, the zone.name is used in all examples in the documentation and examples since a while back.  If you find any other mention of the email as username, please let me know (in a separate bug report). Thanks!
