### ISSUE TITLE
Enabling HTTPS for duckdns

### ISSUE THREAD

**Issue by fahimscirex** [troglobit/inadyn#377]
Not sure if I can use ssl certificates here for duckdns, didn't find anything about it in the readme. How do I serve ssl certificates, so that domain can be accessible from HTTPS?

**Comment by troglobit** [comment]
HTTPS support for updating your DNS entry at DuckDNS is supported, yes.  I don't know about your other questions, they do not seem to have anything to do with In-a-dyn?

**Comment by fahimscirex** [comment]
I thought inadyn supports adding SSL certificates.

**Comment by troglobit** [comment]
I think you have confused things a bit.  In-a-dyn is a HTTP/HTTPS *client*, it's only responsible for updating central DNS/DDNS servers with your current IP address using a per-provider specific protocol.  HTTPS is supported as a means to securely notify the DNS/DDNS provider of the change.  The only setting related to certificates is the `ca-trust-file`, which is only needed if the root certificates are installed in a non-standard path on your system.

**Comment by troglobit** [comment]
`ETIMEDOUT`
