### ISSUE TITLE
Inadyn writes the pidfile AFTER dropping priveleges

### ISSUE THREAD

**Issue by iain-henderson** [troglobit/inadyn#378]
This doesn't seem to affect running Inadyn as a service on Linux when using systemd to manage things.

However, when inadyn is run directly it does not seem to have permission to write the pidfile when it wants to.

**Comment by troglobit** [comment]
I suggest you use the `-P /path/to/pidfile` if your use-case is outside systemd/finit/init land.

**Comment by iain-henderson** [comment]
It’s rc.d , but inadyn should probably be able write a pid to /run or /var/run without help.

**Comment by troglobit** [comment]
Well, maybe you can set up /run/inadyn/ as writable/owned by the USER[:GROUP] and use -P /run/inadyn/pid ... ?

**Comment by iain-henderson** [comment]
I am closing this, it turns out that doing this "properly" would make inadyn unnecessarily complicated while providing marginal benefit.
