### ISSUE TITLE
Include configuration option not working

### ISSUE THREAD

**Issue by rockstorm101** [troglobit/inadyn#383]
I get the following messages when trying to run a configuration file with an "include" option:

```
In-a-dyn version 2.9.1 -- Dynamic DNS update client.
/etc/inadyn.conf:12: no such option 'include'
Parse error in /etc/inadyn.conf
Error code 74: Missing .conf file
```
Interestingly the "include" option is not on line 12 of `/etc/inadyn.conf` file but actually on line 6:

```
# Inadyn v2.0 configuration file format
# 12 hours = 12x60x60 = 43200 s
period          = 43200
#verify-address  = false

include("/run/secrets/dyndns_password")

custom strato {
    <omitted>
}
```

What I'm trying to do here is to load the password from a file which is separate from the rest of the configuration. I was under the impression the "include" option was the way to go for this.

For completeness, these are the contents of `/run/secrets/dyndns_password`:

`password = <omitted>`

I believe permissions on both files are OK. Basically because commenting out the "include" bit makes the setup work.
```sh
$ ls -al /run/secrets/dyndns_password
-rw-r--r--    1 1000     1000            32 Apr 19 20:16 dyndns_password
$ ls -al /etc/inadyn.conf 
-rw-r--r--    1 1000     1000           610 Apr 19 20:26 /etc/inadyn.conf
```
Please let me know what I'm doing wrong or if you need any other info for troubleshooting.

**Comment by troglobit** [comment]
The `include()` .conf option is only available from within a provider or custom context, not from the global level.  See the manual page [inadyn.conf(5)](https://man.troglobit.com/man5/inadyn.conf.5.html) for details.

**Comment by rockstorm101** [comment]
Thanks a lot for your quick reply! That makes much sense. I was using [Fossies man page][1] and that detail wasn't obvious (for me). I wasn't aware of the more ["official" man page][2] at your website. Sorry about that. Might want to add a link to it on the README? Sadly even [Debian's man page][3] is not even at 2.9.1 yet.

[1]: https://fossies.org/linux/inadyn/man/inadyn.conf.5
[2]: https://man.troglobit.com/man5/inadyn.conf.5.html
[3]: https://manpages.debian.org/unstable/inadyn/inadyn.8.en.html

**Comment by troglobit** [comment]
Yeah I have it in my backlog of updates to all projects to do just that. I'll see to put it on my checklist for new releases, at least. Thanks!
