### ISSUE TITLE
About update of dnspod

### ISSUE THREAD

**Issue by SadBoen** [troglobit/inadyn#389]
Hope there cloud be a new update of dnspod.com
I use this plugin in Truenas Core, Thank you very much!

**Comment by troglobit** [comment]
Hi! Not following. Is there something wrong with the existing plugin, is it malfunctioning?

**Comment by troglobit** [comment]
Any logs or additional information would be very helpful since I don't have a login to dnspod myself.  This project exists solely with the help from all its contributors.

**Comment by troglobit** [comment]
@SadBoen PING?  Could you please give some feedback on my question above, otherwise I'll have to close this since I don't know what the problem is.

**Comment by BrainSlayer** [comment]
usually he was talking about ipv6 support. i added this now
