### ISSUE TITLE
No arm platform packages on github

### ISSUE THREAD

**Issue by queeup** [troglobit/inadyn#396]
There is no `linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le` platfom containers on github packages.

**Comment by troglobit** [comment]
Correct, those are on docker hub instead.

**Comment by queeup** [comment]
I request to put here ass well. On docker hub there is a pull limit. Sometimes it's annoying. 

If you don't want to put here fell free to close this issue.

Thank you for your great work on this project.

**Comment by troglobit** [comment]
There are two separate workflows in GitHub actions for this.  I have not had a need to add this myself, but someone else is free to sink a few hours into getting it working the same way also for ghcr.

**Comment by Gontier-Julien** [comment]
> I'm leaning towards splitting the `container.yml` workflow into two:
> 
>     * one for docker hub to run only on releases, since it takes a good while to build,
> 
>     * and another for ghcr, which is very quick and good for regression testing during development cycles
> 
> 
> This is the main reason for me to support ghcr, and I also don't want to end up paying for docker hub, which has been rumored from time to time.

That could be the solution yeah, and i hope too that docker hub won't be paid only it would be a shame..

**Comment by troglobit** [comment]
Cool, I'll have a commit splitting them up in a while.  With that we'll be closing this issue, full arch support will only be available via Docker Hub and GHCR will be solely for regression testing the Dockerfile (and the maintainer's primary $ARCH for reference).
