### ISSUE TITLE
Not properly linking binaries on brew installation

### ISSUE THREAD

**Issue by jpcastberg** [troglobit/inadyn#401]
After installing via homebrew, the `inadyn` binary was not in my PATH. I had to manually symlink `/usr/local/Cellar/inadyn/2.10.0/sbin/inadyn` -> `/usr/local/bin/inadyn` to make it available.

**Comment by troglobit** [comment]
I suggest you take it up with the [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core) project.  They maintain the latest packaging for their distribution.

(Locally we have `HomebrewFormula/inadyn.rb`, but it was contributed by a 3rd party and is not maintained.)
