### ISSUE TITLE
fail to update dynv6 and duckdns

### ISSUE THREAD

**Issue by whjiang** [troglobit/inadyn#416]
My conf is this:
```
period          = 300
user-agent      = Mozilla/5.0
allow-ipv6 = true
verify-address = false
provider dynv6.com {
    username = "xxx"
    password = na
    hostname = {zone1,zone2}
}

provider duckdns.org {
    username = tokenyyy
    password = na
    hostname = {zone3}
}
```

When I run `inadyn --once --force --loglevel=info -n `, I get following output:
```
inadyn[42]: In-a-dyn version 2.10.0 -- Dynamic DNS update client.
inadyn[42]: Guessing DDNS plugin 'default@duckdns.org' from 'duckdns.org'
inadyn[42]: Resolving hostname zone3 => IP# 198.xx.xx.14
inadyn[42]: Resolving hostname zone1 => IP# 180.yy.yy.66
inadyn[42]: Resolving hostname zone2 => IP# 180.yy.yy.66
inadyn[42]: Communication with checkip server wtfismyip.com failed, run again with 'inadyn -l debug' if problem persists
inadyn[42]: Retrying with built-in 'default', api.ipify.org ...
inadyn[42]: Failed to get IP address for default@duckdns.org, giving up!
inadyn[42]: Checking for IP# change, connecting to checkip.dyndns.com([158.101.44.242]:80)
inadyn[42]: Current IP# 180.zz.zz.170 at ipv6@dynv6.com
inadyn[42]: Update forced for alias zone3, new IP# 198.xx.xx.14
inadyn[42]: Update forced for alias zone1, new IP# 180.zz.zz.170
inadyn[42]: Update forced for alias zone2, new IP# 180.zz.zz.170
```

What I expect: all these 3 zones are updated to 180.zz.zz.170 which is the right address. But, after this command, all these zones keep the old value.

**Comment by troglobit** [comment]
Please re-run the above with `--loglevel=debug` and make sure to include the complete log. (Masking your credentials and IP addresses, like above, is of course OK.)

**Comment by whjiang** [comment]
I will run it several days later as I am on a business travel. Actually, I had run it with `--loglevel=debug` and the output seems the check ip logic had more output lines, but the force update logic `Update forced for alias` had the exact same lines as `--loglevel=info`.

**Comment by agalakhov** [comment]
I observe a very similar issue. While inadyn says that the address was successfully updated, actually it wasn't.

```
inadyn[33310]: Sending IP# update to DDNS server, connecting to dynv6.com([159.69.43.243]:443)
inadyn[33310]: Sending IP# update to DDNS server, initiating HTTPS ...
inadyn[33310]: SSL connection using TLS_AES_128_GCM_SHA256
inadyn[33310]: Certificate OK
inadyn[33310]: SSL server cert subject: /CN=dynv6.com
inadyn[33310]: SSL server cert issuer: /C=US/O=Let's Encrypt/CN=R3
inadyn[33310]: Sending alias table update to DDNS server: GET /api/update?ipv6=auto&hostname=XXXX.v6.army&token=ZZZZZZZ HTTP/1.0
Host: dynv6.com
User-Agent: inadyn/2.10.0 https://github.com/troglobit/inadyn/issues

inadyn[33310]: Successfully sent HTTPS request!
inadyn[33310]: Successfully received HTTPS response (276/8191 bytes)!
inadyn[33310]: DDNS server response: HTTP/1.0 200 OK
Alt-Svc: h3=":443"; ma=2592000
Content-Length: 19
Content-Type: text/plain; charset=UTF-8
Date: Fri, 31 Mar 2023 17:37:52 GMT
Server: Caddy
Strict-Transport-Security: max-age=31536000;
Vary: Origin
X-Xss-Protection: 1; mode=block

addresses unchanged
inadyn[33310]: Successful alias table update for XXXX.v6.army => new IP# 2002:ZZZZ:ZZZZ:0:ZZZZ:ZZZZ:ZZZZ:ZZZZ
inadyn[33310]: Updating cache for XXXX.v6.army
```

**Comment by agalakhov** [comment]
I found the cause. The `ipv6=auto` in the URL does not work for me. For some reason the server does not detect my IP correctly (perhaps the connection uses IPv4) and one MUST explicitly specify the address.

**Comment by troglobit** [comment]
> I found the cause. The `ipv6=auto` in the URL does not work for me. For some reason the server does not detect my IP correctly (perhaps the connection uses IPv4) and one MUST explicitly specify the address.

Interesting, how did you format the update IP request URL for dynv6, was it `ip=x.x.x.x` or `myip=x.x.x.x` as in the regular dyn.com plugin?

**Comment by troglobit** [comment]
I don't have accounts at all providers, so it would be great if someone with an account on any of these could help test and provide a patch or, even better, a pull request. 

It would be great to fix these issues before the next release.

**Comment by troglobit** [comment]
> > I found the cause. The `ipv6=auto` in the URL does not work for me. For some reason the server does not detect my IP correctly (perhaps the connection uses IPv4) and one MUST explicitly specify the address.
> 
> Interesting, how did you format the update IP request URL for dynv6, was it `ip=x.x.x.x` or `myip=x.x.x.x` as in the regular dyn.com plugin?

Patch proposal:

```diff
diff --git a/plugins/dynv6.c b/plugins/dynv6.c
index 34294cc..44739cc 100644
--- a/plugins/dynv6.c
+++ b/plugins/dynv6.c
@@ -24,7 +24,7 @@
 
 #define DYNV6_UPDATE_IP_REQUEST                                                \
        "GET %s?"                                                       \
-       "%s=auto&"                                                      \
+       "%s=%s&"                                                        \
        "hostname=%s&"                                                  \
        "token=%s"                                                      \
        " "                                                             \
@@ -66,14 +66,19 @@ static ddns_system_t plugin6 = {
 static int request(ddns_t *ctx, ddns_info_t *info, ddns_alias_t *alias)
 {
        const char *ver = "ipv6";
+       char *addr;
 
        if (strstr(info->system->name, "ipv4"))
                ver = "ipv4";
+       if (alias->address[0])
+               addr = alias->address;
+       else
+               add = "auto";   /* ipv6=auto, or ipv4=auto */
 
        return snprintf(ctx->request_buf, ctx->request_buflen,
                        DYNV6_UPDATE_IP_REQUEST,
                        info->server_url,
-                       ver,                    /* ipv6=auto, or ipv4=auto */
+                       ver, addr,
                        alias->name,
                        info->creds.username,
                        info->server_name.name,
```

**Comment by troglobit** [comment]
> I will run it several days later as I am on a business travel. Actually, I had run it with `--loglevel=debug` and the output seems the check ip logic had more output lines, but the force update logic `Update forced for alias` had the exact same lines as `--loglevel=info`.

@whjiang I really don't know what's the root cause of your issues, one of the logs above show failure to connect to checkip server, that may be one issue.  Another is that you are using only IPv4 but connecting to dynv6.  Have you tried `provider default@ipv4.dynv6.com` instead?

**Comment by troglobit** [comment]
Pushed the proposed fix to the `master` branch in commit 91d274f.  I would still like some feedback from you @agalakhov on the change I made, hopefully I'm on my mark.  A bit weird fixing bugs when you have no means of testing them :-D

Should the issue persist we can reopen it.

**Comment by agalakhov** [comment]
This looks correct and seems to work for me, although my address hasn't been changed recently and thus I can't be 100% sure.

**Comment by troglobit** [comment]
Great, thank you for the audit anyway!
