### ISSUE TITLE
Inadyn say DDNS server response not OK, even tho it is for Desec.io

### ISSUE THREAD

**Issue by Gontier-Julien** [troglobit/inadyn#422]
Desec respond with a `good` page, but inadyn think it not OK and so try again.

```
inadyn[1]: Sending alias table update to DDNS server: GET /?username=DOMAIN.dedyn.io&password=TOKEN&hostname=DOMAIN.dedyn.io&myipv4=MYIP HTTP/1.0
Host: update.dedyn.io
User-Agent: Mozilla/5.0
inadyn[1]: Successfully sent HTTPS request!
inadyn[1]: Successfully received HTTPS response (225/8191 bytes)!
inadyn[1]: DDNS server response: HTTP/1.1 200 OK
Server: nginx
Date: Sun, 23 Apr 2023 17:13:44 GMT
Content-Type: text/plain
Content-Length: 4
Connection: close
Allow: GET, HEAD, OPTIONS
Vary: Origin
Strict-Transport-Security: max-age=31536000
good
inadyn[1]: Fatal error in DDNS server response: DDNS server response not OK
inadyn[1]: good
inadyn[1]: Error response from DDNS server, exiting!
inadyn[1]: Error code 48: DDNS server response not OK
```

It does update successfully on desec too, it just that inadyn doesn't think the response is good.

> PS: an since it try again & again, it is rate limited at one point, so it would be a good idea to wait & retry every 1 minute.
> Desec doc:  dyndns | 1/min | dynDNS updates (per domain).

**Comment by Gontier-Julien** [comment]
More info from Desec doc:

Update Response:

If successful, the server will return a response with status `200 OK` and `good` as the body (as per the dyndns2 protocol specification). For error status codes, see above.

**Comment by troglobit** [comment]
We're getting closer, the original contributor of this plugin must not have tested it at all.  Pushing a fix now.

**Comment by troglobit** [comment]
My guess is that this was the last fix needed to this plugin.  Thank you so much for your time and patience while debugging this!

**Comment by Gontier-Julien** [comment]
> We're getting closer, the original contributor of this plugin must not have tested it at all. Pushing a fix now.

Seems like it haha

**Comment by Gontier-Julien** [comment]
> My guess is that this was the last fix needed to this plugin. Thank you so much for your time and patience while debugging this!

And no problem!! Thank you for you time and effort for fixing it too! ^^

**Comment by Gontier-Julien** [comment]
Just as an update on the latest build, everything is working perfectly now!!

**Comment by troglobit** [comment]
That's great, thank you for reporting back! 😎
