### ISSUE TITLE
[Suggestion] Check if domain is still reachable on period

### ISSUE THREAD

**Issue by Gontier-Julien** [troglobit/inadyn#423]
That just a suggestion to potentially make the url of the domain always reachable whatever happen if the ip got wiped out from the dynserver or whatever could happen.

How it could work:
```
When the xx period come to the end, check if the hostname still as an ip associated with it.

If it return an ip that is the same as the current one (unless the current one return nothing)*, don't do anything and restart the period.

If it doesn't return an ip, grab the current one (unless the current one return nothing)* and update it.
```
>*to prevent wiping with nothing the hostname (like ddclient do if it fail to grab an ip)

Why do this?
Reliability and to ensure that the hostname can always be reachable if for example the dyndns server doesn't have it anymore for xx reason.

It may not seem useful at first, but it would be a nice mechanism to have when not home and not being worried to not being able to access it (unless there a power outage or internet one).

Let me know what do you think about it ^^

**Comment by Gontier-Julien** [comment]
And inform the user about it even if it all good.

**Comment by Gontier-Julien** [comment]
That what inadyn kinda currently do, but only at startup if i'm not mistaken

**Comment by troglobit** [comment]
The `period = SEC` setting in the .conf file controls this to a certain degree. We cannot really trust DNS¹, due to proxies and caching, so inadyn maintain a local cache of what it last sent to the DDNS provider.
__  
¹ the initial DNS check is only done to check the cached value against.

**Comment by Gontier-Julien** [comment]
Thank for the info ! Closing this now ^^
