### ISSUE TITLE
Period not to find in logs

### ISSUE THREAD

**Issue by ThorstenUm** [troglobit/inadyn#466]
I have installed inadyn 2.10.0 on my debian machine. I have defined the config for the provider. Works so far. In the inadyn file I set RUN_DAEMON="yes". I restarted the service. I have the feeling that the IP is not queried regularly. I can't find it in the log, even though I set period to 300. If I trigger this manually by entering inadyn, then I find something in the log. I've already looked at iftop for connections; just found nothing. How can I determine whether the service is working regularly? Nothing is entered in the cron.

**Comment by troglobit** [comment]
I think you should report this downstream to Debian, not here. This is true for all packaged software. Downstream projects like Debian ABs others are responsible for your support. 

Also there's nothing RUN_DAEMON in Inadyn proper, and there are newer releases than 2.10 and we barely have resources to support the latest.

**Comment by ThorstenUm** [comment]
Thanks for the info. How can I actually load the latest version into Debian? The debian repo is usually older. The old version apparently doesn't include goip as a plugin either. I wanted to try this out and ran into an error.

**Comment by troglobit** [comment]
Experienced users can have a look at the top-level [README.md](https://github.com/troglobit/inadyn/#build--install) of this project.  Most people should however report this to their distro, or see if there is a newer version packaged in a later distro release.
