### ISSUE TITLE
Missing .conf file, and can not create a new one

### ISSUE THREAD

**Issue by DZ65367709** [troglobit/inadyn#476]
When I use cmd “inadyn —check-config “, it responses: “ Cannot read configuration file /usr/etc/inadyn.conf”—in logs I find it’s missing, so I attempt to create a directory and copy an prepared in, first-step: “mkdir -p /usr/etc”, it said :” mkdir: can't create directory '/usr/etc': Read-only file system” …
Anyone please help telling me how to create this directory so as to copy an existing config file into it.  …or any other method let it work. Thanks.

**Comment by acolomb** [comment]
You can specify any other file location as config file, like this:

    inadyn --config=/path/to/your/file

**Comment by DZ65367709** [comment]
Thanks for your help. 

> 在 2024年3月18日，01:03，André Colomb ***@***.***> 写道：
> 
> inadyn --config=
