### ISSUE TITLE
Inadyn does not validate SSL certificates

### ISSUE THREAD

**Issue by ThomasWaldmann** [troglobit/inadyn#61]
This is somewhere documented even, but I think it deserves a place in the issue tracker also.

The transmission will be still encrypted, but the client is basically not knowing whether it really talks to the right server.

**Comment by troglobit** [comment]
In b3b83b3 certificate validation when using GnuTLS was added.  I'm leaning towards closing this issue now, as-is, and leaving it up to someone else to fix the OpenSSL/LibreSSL cert validation support.

**Comment by Duncaen** [comment]
fyi latest HEAD compiled fine with libressl.

**Comment by troglobit** [comment]
Friggin' AWESOME! :raised_hands: thanks a LOT @Duncaen for reporting this!

Saves me a lot of testing during integration, cheers! :smiley:
