### ISSUE TITLE
Test both OpenSSL and GnuTLS builds in Travis

### ISSUE THREAD

**Issue by ThomasWaldmann** [troglobit/inadyn#65]
And make sure it passes the Coverity Scan as well ... -- Joachim @troglobit Nilsson

**Comment by troglobit** [comment]
Both OpenSSL and GnuTLS is now tested using GCC *and* Clang, as of commit b958392.  Currently Coverity seem to have some issues with their infrastructure, but both compiler builds (using the default GnuTLS) are passed on to Scan.
