### ISSUE TITLE
Use GnuTLS native API for HTTPS

### ISSUE THREAD

**Issue by ThomasWaldmann** [troglobit/inadyn#67]
After looking at GnuTLS' OpenSSL compatiblity layer, it somehow left a mediocre impression:

- some essential stuff is missing (see hack for SNI support in inadyn ssl.c)
- some of the implemented API calls are not fully implemented (e.g. does not dynamically allocate a buffer if you give a NULL pointer)
- GnuTLS 3.0.5 NEWS: "gnutls-extra: is no more" - so it was killed in 2011.

So, I think if one wants to support both OpenSSL and GnuTLS, it should be by directly using their native APIs (not: that dead OpenSSL compatibility wrapper).

**Comment by troglobit** [comment]
GIT commit b3b83b3 adds initial support, including certificate validation.  Very little testing done.
