### ISSUE TITLE
Support LibreSSL in addition to OpenSSL and GnuTLS

### ISSUE THREAD

**Issue by queeup** [troglobit/inadyn#72]
Is it possible to add LibreSSL support too?
http://www.libressl.org/

**Comment by troglobit** [comment]
Hey @queeup did you ever manage to get it to work?

**Comment by Duncaen** [comment]
Compiles and works with `libressl` without problems.
To get `libite` with `musl` libc compiling, I removed the `error.h` import from `libite/lite.h`.

I added a build template to void linux.
https://github.com/voidlinux/void-packages/commit/914cf3f38451edd9982a7e94a1c3debf5fadb825 
Build logs:
http://build.voidlinux.eu/builders/x86_64-musl_builder/builds/7754/steps/shell_3/logs/stdio
http://build.voidlinux.eu/builders/x86_64_builder/builds/19573/steps/shell_3/logs/stdio
http://build.voidlinux.eu/builders/armv7l-musl_builder/builds/7096/steps/shell_3/logs/stdio
http://build.voidlinux.eu/builders/armv7l_builder/builds/20510/steps/shell_3/logs/stdio

**Comment by troglobit** [comment]
This is awesome news, @Duncaen thanks! :smiley: 

I should definitely try out `musl`! Should be quite simple to `#ifdef` the `error.h` include if I knew what/if `musl` defines something special ... you don't happen to have a clue?

**Comment by Duncaen** [comment]
@troglobit I think the musl devs dont want conditions for musl, glibc specific things should be conditional instead by checking `__GLIBC__`.

**Comment by troglobit** [comment]
@Duncaen Ah, not surprising ... but still slightly tiresome considering what's the norm and what is not ;)

Oh well, all add it to libite (LITE) and update the version in Inadyn for the upcoming v2.0.  Thank you so much for taking the time to help out! :+1:

**Comment by Duncaen** [comment]
Yes this issue can be closed no problems related to LibreSSL.
BSDs `err.h` sounds good, thank you for your fast response and maintaining inadyn :smile:.

**Comment by troglobit** [comment]
@Duncaen cheers!
