### ISSUE TITLE
Add variables to the custom@http_srv_basic_auth system

### ISSUE THREAD

**Issue by thenktor** [troglobit/inadyn#73]
Hi,

I've got a DDNS provider here that expects username, password and IP in the server url, e.g.
`/ddns.php?user=myname&password=mypass&ip=1.2.3.4`

So it would be nice if it could be configured like this in the config file
`server-url /ddns.php?user=<username>&password=<pass>&ip=<ipaddr>`
and `<username>`, `<pass>` and `<ipaddr>` will be replaced with the actual values.

**Comment by troglobit** [comment]
Pull request #86 merged as 5debb18
