### ISSUE TITLE
No rule to make target CHANGELOG

### ISSUE THREAD

**Issue by thenktor** [troglobit/inadyn#82]
Hi,

building version 1.99.13 fails with message "No rule to make target CHANGELOG". You probably have renamed CHANGELOG to ChangeLog and you also have to change this in the Makefile's doc_DATA variable.

**Comment by troglobit** [comment]
Thanks for the heads up, thought I'd tested that. I renamed NEWS to CHANGELOG only to have GNU configure/autoconf barf on me. Problem seems to be that there was an old ChangeLog file that should've been used instead. LOL

I'll fix it later today/tomorrow!

**Comment by troglobit** [comment]
Should be fixed as of 7256141. Cheers!
