### ISSUE TITLE
Template "ipv6tb@he.net" for ipv4.tunnelbroker.net is wrong

### ISSUE THREAD

**Issue by hvenzke** [troglobit/inadyn#83]
The inadyn template "ipv6tb@he.net" for ipv4.tunnelbroker.net is wrong. See the reference documentation at https://forums.he.net/index.php?topic=1994.0

    Mon Mar 30 10:17:15 2015: Current public IP# xxx.xx.xxx.xxx
    Mon Mar 30 10:17:15 2015: Update needed for alias 286216, new IP# xxx.xxx.xxx.xxx
    Mon Mar 30 10:17:15 2015: Sending IP# update to DDNS server, connecting to ipv4.tunnelbroker.net(64.62.200.2)
    Mon Mar 30 10:17:16 2015: Sending alias table update to DDNS server:
    Mon Mar 30 10:17:16 2015: GET /nic/update?ip=<ip>&apikey=<user>&pass=<pass>&tid=<tunnelid> HTTP/1.0 Host: ipv4.tunnelbroker.net User-Agent: inadyn/1.99.4 troglobit@gmail.com

The correct update URL should instead be:

    https://<USERNAME>:<PASSWORD>@ipv4.tunnelbroker.net/nic/update?hostname=<TUNNEL_ID>

e.g.

    https://ipv4.tunnelbroker.net/nic/update?username=<USERNAME>&password=PASSWORD>&hostname=<TUNNEL_ID>

Please fix with add an --system "default@tunnelbroker.net" , using dyndns 2 prokoll with the correct URL (given by he.net wiki)

**Comment by troglobit** [comment]
Will look into it.  Unfortunately I have no account for tunnelbroker.net, so I cannot verify that a fix I do works.

On the other hand, I've wanted to try out IPv6 for a while now so ... 

Anyway, tested patches or pull requests are most welcome!

**Comment by troglobit** [comment]
@hvenzke there, fixed :smiley: 

I've tested it with my own tunnel, so it should work, but if you can it would be greatly appreciated if you could test the latest GIT master.

After having checked out the master branch you must do a `git submodule update --init` to have GIT download the new `libite` submodule.
