### ISSUE TITLE
When starting it tries to write to /run/inadyn/inadyn.pid as debian-inadyn

### ISSUE THREAD

**Issue by ilovewater** [troglobit/inadyn#85]
When starting it tries to write to /run/inadyn/inadyn.pid as debian-inadyn, and since it doesn't have permissions it dies.  I can not find in the configuration files where I can change this path.  I had to change the user in /etc/inadyn.conf to root to get it to run.

Version: 1.99.4-1
Ubuntu 14.04.2

**Comment by troglobit** [comment]
Hi, this looks like a distribution specific bug, please report such bugs to your distribution. The latest
version of Inadyn is v1.99.13, in which I believe this to be fixed.

Please reopen if you disagree and can reproduce the problem with the latest Inadyn.
